mapregion.MapPrms-queryStrs =   "select * from /DefaultRegion where ID < -1 AND ID > -2000"
                "select * from /DefaultRegion where ID > 0 AND ID < 10"
                "select * from /DefaultRegion where ID > 0 AND ID < 100"
                "select * from /DefaultRegion where ID > 0 AND ID < 1000"
                "select * from /DefaultRegion where ID > 0 AND ID < 1500"
                "select * from /DefaultRegion where ID > 3000 AND ID < 5000";
