CREATE TABLE C_BO_PRTY
(
  ROWID_OBJECT                CHAR(36)     NOT NULL,
  CREATE_DATE                 DATE         DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE            DATE,
  HUB_STATE_IND               INTEGER      DEFAULT 1 NOT NULL,
  PRTY_CUST_ROLE_FL           CHAR(1)      NOT NULL,
  PRTY_PERS_ROLE_FL           CHAR(1)      NOT NULL,
  PRTY_FST_NM                 VARCHAR(40),
  PRTY_MID_NM                 VARCHAR(40),
  PRTY_LAST_NM                VARCHAR(40),
  PRTY_FULL_NM                VARCHAR(120),
  PRTY_CUST_INFRML_NM         VARCHAR(40),
  PRTY_PERS_PREF_NM           VARCHAR(40),
  PRTY_TITL_SFX_CD            VARCHAR(40),
  PRTY_TKN_SSN_NUM            VARCHAR(32),
  PRTY_BIRTH_DT               DATE,
  PRTY_GNDR_CD                VARCHAR(3),
  PRTY_GNDR_DSC               VARCHAR(240),
  PRTY_TRUVUE_PIN_ID          VARCHAR(17),
  PRTY_ORIG_FST_NM            VARCHAR(40),
  PRTY_ORIG_MID_NM            VARCHAR(40),
  PRTY_ORIG_LST_NM            VARCHAR(40),
  PRTY_ORIG_TITL_SFX_CD       VARCHAR(40),
  PRTY_NA_SKEY                BIGINT,
  NAME_PFX_CD_FK              VARCHAR(32),
  NM_UPDT_RSN_ID              CHAR(14),
  NM_SFX_CD_FK                VARCHAR(32),
  PRTY_CNTCT_METH_TYP_CD      VARCHAR(32),
  PRTY_HIDE_SRC_TXT           VARCHAR(240),
  PRTY_RLNSHP_OKTOEMAIL_FL    CHAR(1)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT);

CREATE INDEX NI_C_BO_PRTY_6 ON C_BO_PRTY
(ROWID_OBJECT, PRTY_FST_NM, PRTY_LAST_NM);


CREATE INDEX SVR1_16X96N ON C_BO_PRTY
(PRTY_FST_NM, PRTY_LAST_NM, PRTY_PERS_ROLE_FL);


CREATE UNIQUE INDEX SVR1_2Q1R ON C_BO_PRTY
(ROWID_OBJECT);


CREATE TABLE  C_BO_PRTY_XREF 
(
  ROWID_XREF 			INTEGER NOT NULL,
  PKEY_SRC_OBJECT 		VARCHAR(255), 
  ROWID_OBJECT 			CHAR(36) NOT NULL, 
  ROWID_SYSTEM 			CHAR(14) NOT NULL,
  HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
  CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE 		DATE
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_PRTY);

CREATE UNIQUE INDEX SVR1_2Q67 ON C_BO_PRTY_XREF
(ROWID_XREF);

CREATE INDEX SVR1_3XEC ON C_BO_PRTY_XREF 
(ROWID_OBJECT ASC, ROWID_SYSTEM ASC);

CREATE UNIQUE INDEX SVR1_3XED ON C_BO_PRTY_XREF 
(PKEY_SRC_OBJECT ASC, ROWID_SYSTEM ASC, HUB_STATE_IND ASC); 

CREATE TABLE C_BO_POSTAL_ADDR
(
  ROWID_OBJECT           CHAR(36)	NOT NULL,
  CREATE_DATE            DATE 		DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE       DATE,
  HUB_STATE_IND          INTEGER 	DEFAULT 1 NOT NULL,
  PSTL_LN1_TXT           VARCHAR(100),
  PSTL_LN2_TXT           VARCHAR(100),
  PSTL_LN3_TXT           VARCHAR(100),
  PSTL_LN4_TXT           VARCHAR(100),
  PSTL_CITY_NM           VARCHAR(40),
  PSTL_CD                VARCHAR(32),
  PSTL_ORIG_LN1_TXT      VARCHAR(100),
  PSTL_ORIG_LN2_TXT      VARCHAR(100),
  PSTL_ORIG_LN3_TXT      VARCHAR(100),
  PSTL_ORIG_LN4_TXT      VARCHAR(100),
  PSTL_ORIG_CITY_NM      VARCHAR(36),
  PSTL_ORIGIN_REGN_NM    VARCHAR(40),
  PSTL_ORIG_CD           VARCHAR(32),
  PRTY_ID                CHAR(36)	NOT NULL,
  CUST_ADDR_DNU_RSN_ID   CHAR(14),
  ST_ID                  CHAR(14),
  CNTRY_ID               CHAR(14),
  REGN_ID                CHAR(14),
  ADDR_TYP_ID            CHAR(14),
  ADDR_RSDNCY_TYP_ID     CHAR(14)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE INDEX NI_C_BO_POSTAL_ADDR_0 ON C_BO_POSTAL_ADDR
(PSTL_CD);

CREATE INDEX SVR1_16X96Q ON C_BO_POSTAL_ADDR
(PSTL_CD, HUB_STATE_IND, PRTY_ID, ROWID_OBJECT);

CREATE UNIQUE INDEX SVR1_2H1L ON C_BO_POSTAL_ADDR
(ROWID_OBJECT);

CREATE INDEX SVR1_4GPS ON C_BO_POSTAL_ADDR 
(PRTY_ID);


CREATE TABLE C_BO_POSTAL_ADDR_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_POSTAL_ADDR);

CREATE UNIQUE INDEX SVR1_2H61 ON C_BO_POSTAL_ADDR_XREF
(ROWID_XREF);
 
CREATE INDEX SVR1_2H62 ON C_BO_POSTAL_ADDR_XREF
(ROWID_OBJECT, ROWID_SYSTEM);
 
CREATE UNIQUE INDEX SVR1_2H63 ON C_BO_POSTAL_ADDR_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);

CREATE TABLE C_BO_TPHN 
(
   ROWID_OBJECT 		CHAR(36) NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   TPHN_NUM 			VARCHAR(32),
   PRTY_ID 			CHAR(36),
   TPHN_MKTG_OKTOCALL_FL 	CHAR(1),
   CNTRY_ID 			CHAR(14),
   TPHN_TYP_ID 			CHAR(14), 
   TPHN_DVC_TYP_ID 		CHAR(14), 
   TPHN_USG_TYP_ID 		CHAR(14), 
   CUST_TPHN_DNU_RSN_ID 	CHAR(14)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE UNIQUE INDEX SVR1_2F2R ON C_BO_TPHN
(ROWID_OBJECT);

CREATE INDEX SVR1_6KQ9 ON C_BO_TPHN 
(PRTY_ID ASC);

CREATE INDEX NI_C_BO_TPHN_0 ON C_BO_TPHN
(TPHN_NUM, PRTY_ID, TPHN_MKTG_OKTOCALL_FL);


CREATE TABLE C_BO_TPHN_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
)  REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_TPHN);

CREATE UNIQUE INDEX SVR1_2F77 ON C_BO_TPHN_XREF
(ROWID_XREF);
 
CREATE INDEX SVR1_2F78 ON C_BO_TPHN_XREF
(ROWID_OBJECT, ROWID_SYSTEM);
 
CREATE UNIQUE INDEX SVR1_2F79 ON C_BO_TPHN_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);

CREATE TABLE C_BO_ELCTRNC_ADDR
(
   ROWID_OBJECT             CHAR(36)        NOT NULL,
   CREATE_DATE              DATE            DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE         DATE,
   HUB_STATE_IND            INTEGER         DEFAULT 1  NOT NULL,
   ELCTRNC_TXT              VARCHAR(60)    NOT NULL,
   ELCTRNC_HIDE_SRC_TXT     VARCHAR(240),
   ELCTRNC_OPT_IN_IND       VARCHAR(20),
   PRTY_ID                  CHAR(36),
   CUST_ADDR_DNU_RSN_ID     CHAR(14),
   ADDR_TYP_ID              CHAR(14),
   ADDR_USAGE_ID            CHAR(14)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE INDEX NI_C_BO_ELCTRNC_ADDR_0 ON C_BO_ELCTRNC_ADDR
(ROWID_OBJECT, ELCTRNC_TXT);
 
CREATE INDEX NI_C_BO_ELCTRNC_ADDR_1 ON C_BO_ELCTRNC_ADDR
(ELCTRNC_TXT, PRTY_ID);
 
CREATE UNIQUE INDEX SVR1_2JRI ON C_BO_ELCTRNC_ADDR
(ROWID_OBJECT);
 
CREATE INDEX SVR1_44WZ ON C_BO_ELCTRNC_ADDR
(PRTY_ID);

CREATE TABLE C_BO_ELCTRNC_ADDR_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_ELCTRNC_ADDR);

CREATE UNIQUE INDEX SVR1_2JVY ON C_BO_ELCTRNC_ADDR_XREF
(ROWID_XREF);

CREATE UNIQUE INDEX SVR1_4I0P ON C_BO_ELCTRNC_ADDR_XREF 
(PKEY_SRC_OBJECT ASC, ROWID_SYSTEM ASC, HUB_STATE_IND ASC);

CREATE INDEX SVR1_4I0O ON C_BO_ELCTRNC_ADDR_XREF 
(ROWID_OBJECT ASC, ROWID_SYSTEM ASC);

CREATE TABLE C_BO_CUST_TNDR_ACCT
(
   ROWID_OBJECT             	CHAR(36)        NOT NULL,
   CREATE_DATE              	DATE            DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE         	DATE,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CT_ACCT_NM               	VARCHAR(40),
   CT_ACCT_TKN_NUM          	VARCHAR(32)  NOT NULL,
   CT_ACCT_DFLT_FL          	CHAR(1),
   PRTY_ID                  	CHAR(36)      NOT NULL,
   CT_ACCT_END_DT           	DATE,
   T_ACCT_CARD_TYP_ID       	CHAR(14),
   CT_ACCT_PRNT_PK_SRC_IND    	VARCHAR(256) DEFAULT NULL,
   CT_ACCT_DATA_SRC_IND       	VARCHAR(20),
   PRS_CNT_ID                 	CHAR(14),
   CT_ACCT_EXPRTN_DT          	DATE,
   CT_ACCT_OP_DT              	DATE,
   CT_ACCT_CL_DT              	DATE,
   T_ACCT_CARD_SUBTYP_ID      	CHAR(14),
   CT_ACCT_SRC_ACCT_ID        	VARCHAR(32),
   CT_ACCT_STS_CD             	VARCHAR(32),
   C_ACCT_RLN_TYP_ID          	CHAR(14),
   CT_ACCT_BANK_ROUTING_NUM   	VARCHAR(32)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE INDEX NI_C_BO_CUST_TNDR_ACCT_0 ON  C_BO_CUST_TNDR_ACCT
(CT_ACCT_TKN_NUM, CT_ACCT_SRC_ACCT_ID, PRTY_ID);

CREATE INDEX NI_C_BO_CUST_TNDR_ACCT_1 ON C_BO_CUST_TNDR_ACCT
(PRTY_ID, CT_ACCT_DATA_SRC_IND);

CREATE UNIQUE INDEX SVR1_HSQS ON C_BO_CUST_TNDR_ACCT
(ROWID_OBJECT);

CREATE INDEX SVR1_I3ND ON C_BO_CUST_TNDR_ACCT
(PRTY_ID);

CREATE INDEX NI_C_BO_CUST_TNDR_ACCT_2 ON C_BO_CUST_TNDR_ACCT
(CT_ACCT_PRNT_PK_SRC_IND, CT_ACCT_DATA_SRC_IND);


CREATE TABLE C_BO_CUST_TNDR_ACCT_XREF 
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
)  REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_CUST_TNDR_ACCT);


CREATE UNIQUE INDEX  SVR1_HSV8 ON C_BO_CUST_TNDR_ACCT_XREF
(ROWID_XREF);

CREATE UNIQUE INDEX SVR1_3QED ON C_BO_CUST_TNDR_ACCT_XREF 
(PKEY_SRC_OBJECT ASC, ROWID_SYSTEM ASC, HUB_STATE_IND ASC);

CREATE INDEX SVR1_3QEC ON C_BO_CUST_TNDR_ACCT_XREF 
(ROWID_OBJECT ASC, ROWID_SYSTEM ASC);

CREATE TABLE C_BS_CUST_PRSNL_CNTCT
(
   ROWID_OBJECT             	CHAR(36)        NOT NULL,
   CREATE_DATE              	DATE            DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE         	DATE,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   PRTY_ID                    	CHAR(36)      NOT NULL,
   PRS_CNT_FST_NM             	VARCHAR(40),
   PRS_CNT_MID_NM             	VARCHAR(40),
   PRS_CNT_LST_NM             	VARCHAR(40),
   PRS_CNT_ADDR_LN1_TXT       	VARCHAR(240),
   PRS_CNT_ADDR_LN2_TXT       	VARCHAR(240),
   PRS_CNT_CITY_NM            	VARCHAR(36),
   PRS_CNT_PSTL_CD            	VARCHAR(36),
   ST_ID                      	CHAR(14),
   CNTRY_ID                   	CHAR(14),
   PRS_CNT_TPHN_NUM           	VARCHAR(32),
   PRSNL_CNTCT_TYP_ID         	CHAR(14),
   PRS_CNT_ELCTRNC_TXT        	VARCHAR(240),
   PRS_CNT_PRNT_PK_SRC_IND    	VARCHAR(256) DEFAULT NULL,
   PRS_CNT_DATA_SRC_IND       	VARCHAR(20),
   PRS_CNT_SHIPPING_ADDR_FL   	CHAR(1),
   PRS_CNT_BILLING_ADDR_FL    	CHAR(1),
   PRS_CNT_WISH_LIST_ADDR_FL  	CHAR(1),
   PRS_CNT_DFLT_BILLING_FL    	CHAR(1),
   PRS_CNT_DFLT_SHIPPING_FL   	CHAR(1)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE UNIQUE INDEX SVR1_HQPA ON C_BS_CUST_PRSNL_CNTCT
(ROWID_OBJECT);

CREATE INDEX SVR1_HZA2 ON C_BS_CUST_PRSNL_CNTCT
(PRTY_ID);

CREATE INDEX SVR1_I2F1 ON C_BS_CUST_PRSNL_CNTCT
(PRSNL_CNTCT_TYP_ID);

CREATE INDEX SVR1_I2YR ON C_BS_CUST_PRSNL_CNTCT
(ST_ID);

CREATE INDEX SVR1_16X96R ON C_BS_CUST_PRSNL_CNTCT
(PRS_CNT_PRNT_PK_SRC_IND, PRS_CNT_DATA_SRC_IND);


CREATE TABLE C_BS_CUST_PRSNL_CNTCT_XREF 
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
) REDUNDANCY 0 PERSISTENT  PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BS_CUST_PRSNL_CNTCT);

CREATE UNIQUE INDEX SVR1_HR2G ON C_BS_CUST_PRSNL_CNTCT_XREF
(ROWID_XREF);

CREATE INDEX SVR1_4MFF ON C_BS_CUST_PRSNL_CNTCT_XREF 
(ROWID_OBJECT ASC, ROWID_SYSTEM ASC);

CREATE UNIQUE INDEX SVR1_4MFG ON C_BS_CUST_PRSNL_CNTCT_XREF 
(PKEY_SRC_OBJECT ASC, ROWID_SYSTEM ASC, HUB_STATE_IND ASC);


CREATE TABLE C_BO_LYLTY_CUST_RLN 
(
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE DEFAULT CURRENT_DATE,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL, 
   PRTY_ID 			CHAR(36) NOT NULL, 
   PRG_ID 			CHAR(14) NOT NULL, 
   ELCTRNC_ID 			CHAR(14) NOT NULL, 
   TPHN_ID 			CHAR(14), 
   PSTL_ID 			CHAR(14) NOT NULL, 
   LYLTY_CUST_SRC_KEY 		VARCHAR(255) NOT NULL, 
   LYLTY_CUST_RLN_CONS_IND 	CHAR(18), 
   LYLTY_CUST_RLNSHP_EFF_DT 	DATE NOT NULL, 
   LYLTY_CUST_RLNSHP_END_DT 	DATE, 
   LYLTY_CUST_RLN_RCTVTD_DT 	DATE, 
   LYLTY_CUST_RLN_OPT_OUT_DT 	DATE, 
   LYLTY_CUST_RLN_DEC_REM_DT 	DATE, 
   PCPTN_STS_RSN_ID 		CHAR(14),  
   PCPTN_STS_ID 		CHAR(14)
) REDUNDANCY 0 PERSISTENT  PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);  
   
CREATE INDEX SVR1_1NU36 ON C_BO_LYLTY_CUST_RLN 
(PRTY_ID ASC); 



CREATE TABLE C_BS_LYLTY_WEB_PROF_RLN 
(
  ROWID_OBJECT 			CHAR(36) NOT NULL, 
  CREATE_DATE 			DATE  DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE 		DATE, 
  HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL, 
  LYLTY_CUST_RLN_ID 		CHAR(36) NOT NULL, 
  IDENTITY_ID 			CHAR(14) NOT NULL, 
  LYLTY_PROF_RLN_EFF_DT 	DATE NOT NULL, 
  LYLTY_PROF_RLN_END_DT 	DATE, 
  LYLTY_PROF_SRC_CRE_DT 	DATE, 
  LYLTY_PROF_SRC_CRE_TYP 	VARCHAR(60), 
  LYLTY_PROF_SRC_UPD_DT 	DATE, 
  LYLTY_PROF_SRC_UPD_TYP 	VARCHAR(60)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (LYLTY_CUST_RLN_ID) COLOCATE WITH (C_BO_LYLTY_CUST_RLN);

CREATE INDEX SVR1_1NT6Q ON C_BS_LYLTY_WEB_PROF_RLN 
(ROWID_OBJECT ASC);

CREATE INDEX SVR1_1NU2T ON C_BS_LYLTY_WEB_PROF_RLN 
(IDENTITY_ID ASC);

CREATE INDEX SVR1_1NU2E ON C_BS_LYLTY_WEB_PROF_RLN 
(LYLTY_CUST_RLN_ID ASC); 

  

CREATE TABLE C_BT_IDENTITY
(
  ROWID_OBJECT       CHAR(36)             NOT NULL,
  CREATE_DATE        DATE                 DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE   DATE,
  HUB_STATE_IND      INTEGER               DEFAULT 1                  NOT NULL,
  IDENTITY_TYP_CD    VARCHAR(32),
  IDENTITY_NM        VARCHAR(40),
  IDENTITY_BEG_DT    DATE                 DEFAULT CURRENT_DATE        NOT NULL,
  IDENTITY_END_DT    DATE,
  IDENTITY_TYP_DSC   VARCHAR(240)
)  PERSISTENT REPLICATE;

CREATE INDEX NI_C_BT_IDENTITY_0 ON C_BT_IDENTITY
(IDENTITY_NM);

CREATE UNIQUE INDEX SVR1_2SLD ON C_BT_IDENTITY
(ROWID_OBJECT);

CREATE TABLE C_BT_IDENTITY_XREF
(
  ROWID_XREF             INTEGER                NOT NULL,
  PKEY_SRC_OBJECT        VARCHAR(255 ),
  ROWID_OBJECT           CHAR(14 )          NOT NULL,
  ROWID_SYSTEM           CHAR(14 )          NOT NULL,
  HUB_STATE_IND          INTEGER                DEFAULT 1                     NOT NULL,
  CREATE_DATE            DATE DEFAULT CURRENT_DATE      ,
  LAST_UPDATE_DATE       DATE DEFAULT CURRENT_DATE,
  IDENTITY_TYP_CD        VARCHAR(32 ),
  IDENTITY_NM            VARCHAR(40 ),
  IDENTITY_BEG_DT        DATE,
  IDENTITY_END_DT        DATE,
  IDENTITY_TYP_DSC       VARCHAR(240 )
)  PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_2SWI ON C_BT_IDENTITY_XREF
(ROWID_XREF);

CREATE INDEX SVR1_2SWJ ON C_BT_IDENTITY_XREF
(ROWID_OBJECT, ROWID_SYSTEM);

CREATE UNIQUE INDEX SVR1_2SWK ON C_BT_IDENTITY_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);

CREATE TABLE C_BO_PRTY_IDENTITY
(
  ROWID_OBJECT               CHAR(36)      NOT NULL,
  CREATE_DATE                DATE               DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE           DATE,
  HUB_STATE_IND              INTEGER            DEFAULT 1                     NOT NULL,
  IDENTITY_ID                CHAR(14)      NOT NULL,
  PRTY_ID                    CHAR(36)      NOT NULL,
  PRTY_IDENTITY_UPDT_DT      DATE,
  PRTY_IDENTITY_UPDT_BY_TYP  VARCHAR(40),
  PRTY_IDENTITY_BEG_DT       DATE               NOT NULL,
  PRTY_IDENTITY_END_DT       DATE
) REDUNDANCY 0 PERSISTENT  PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);


CREATE UNIQUE INDEX SVR1_2UKD ON C_BO_PRTY_IDENTITY
(ROWID_OBJECT);

CREATE INDEX SVR1_3KM9 ON C_BO_PRTY_IDENTITY
(IDENTITY_ID);

CREATE INDEX SVR1_3KQA ON C_BO_PRTY_IDENTITY
(PRTY_ID);


CREATE TABLE C_BS_CUST_RLNSHP
(
  ROWID_OBJECT          CHAR(36)           NOT NULL,
  CREATE_DATE           DATE              DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE      DATE,
  HUB_STATE_IND         INTEGER                 DEFAULT 1                     NOT NULL,
  PRTY_ID_CUST_FK       CHAR(36),
  CR_STS_CD             VARCHAR(32)       NOT NULL,
  CR_APPL_ACTV_CD       VARCHAR(32),
  CR_CRE_DT             DATE,
  CR_CRE_BY_TYP         VARCHAR(60),
  CR_BEG_DT             DATE                    NOT NULL,
  CR_END_DT             DATE,
  PRTY_ID_SALESPERS_FK  CHAR(36),
  STOR_ID               CHAR(14)
) REDUNDANCY 0 PERSISTENT  PARTITION BY COLUMN (PRTY_ID_CUST_FK) COLOCATE WITH (C_BO_PRTY);

CREATE INDEX NI_C_BS_CUST_RLNSHP_0 ON C_BS_CUST_RLNSHP
(PRTY_ID_CUST_FK, PRTY_ID_SALESPERS_FK);

CREATE INDEX SVR1_16X96P ON C_BS_CUST_RLNSHP
(PRTY_ID_SALESPERS_FK, CR_STS_CD, PRTY_ID_CUST_FK);

CREATE UNIQUE INDEX SVR1_HVN3 ON C_BS_CUST_RLNSHP
(ROWID_OBJECT);

CREATE INDEX SVR1_HZMM ON C_BS_CUST_RLNSHP
(PRTY_ID_CUST_FK);

CREATE INDEX SVR1_I1K1 ON C_BS_CUST_RLNSHP
(PRTY_ID_SALESPERS_FK);

CREATE TABLE C_BS_CUST_RLNSHP_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
) REDUNDANCY 0 PERSISTENT  PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BS_CUST_RLNSHP);

CREATE UNIQUE INDEX SVR1_HVRJ ON C_BS_CUST_RLNSHP_XREF
(ROWID_XREF);

CREATE INDEX SVR1_HVRK ON C_BS_CUST_RLNSHP_XREF
(ROWID_OBJECT, ROWID_SYSTEM);

CREATE UNIQUE INDEX SVR1_HVRL ON C_BS_CUST_RLNSHP_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);


CREATE TABLE C_BS_ELCTRNC
(
   ROWID_OBJECT             CHAR(36)        NOT NULL,
   CREATE_DATE              DATE  DEFAULT CURRENT_DATE       ,
   LAST_UPDATE_DATE         DATE  DEFAULT CURRENT_DATE,
   HUB_STATE_IND            INTEGER              DEFAULT 1                     NOT NULL,
   ELCTRNC_SRC_UPDT_DT      DATE,
   ELCTRNC_BEG_DT           DATE,
   ELCTRNC_END_DT           DATE,
   PRTY_ID_SALESPERS_FK     CHAR(14)        NOT NULL,
   ELCTRNC_OPT_IN_IND       VARCHAR(20 ),
   ELCTRNC_SRC_UPDT_BY_TYP  VARCHAR(60 )    DEFAULT NULL,
   ELCTRNC_ID               CHAR(14)        NOT NULL,
   ELCTRNC_SRC_CRE_DT       DATE,
   ELCTRNC_SRC_CRE_BY_TYP   VARCHAR(60 )    DEFAULT NULL,
   PRTY_ID_CUST_FK          CHAR(36)        NOT NULL
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID_CUST_FK) COLOCATE WITH (C_BO_PRTY);

CREATE INDEX NI_C_BS_ELCTRNC_0 ON C_BS_ELCTRNC
(PRTY_ID_SALESPERS_FK, ELCTRNC_OPT_IN_IND, ELCTRNC_ID);
 
CREATE INDEX SVR1_16X96O ON C_BS_ELCTRNC
(PRTY_ID_SALESPERS_FK, PRTY_ID_CUST_FK, ELCTRNC_ID, ELCTRNC_OPT_IN_IND);
 
CREATE UNIQUE INDEX SVR1_39UK ON C_BS_ELCTRNC
(ROWID_OBJECT);
 
CREATE INDEX SVR1_3NW9 ON C_BS_ELCTRNC
(PRTY_ID_SALESPERS_FK);
 
CREATE INDEX SVR1_3X3A ON C_BS_ELCTRNC
(ELCTRNC_ID);
 
CREATE INDEX SVR1_I0ZW ON C_BS_ELCTRNC
(PRTY_ID_CUST_FK);

CREATE TABLE C_BS_ELCTRNC_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
)  REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BS_ELCTRNC);

CREATE UNIQUE INDEX SVR1_39Z0 ON C_BS_ELCTRNC_XREF
(ROWID_XREF);

CREATE INDEX SVR1_39Z1 ON C_BS_ELCTRNC_XREF
(ROWID_OBJECT, ROWID_SYSTEM);

CREATE UNIQUE INDEX SVR1_39Z2 ON C_BS_ELCTRNC_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);

CREATE TABLE C_BO_CUST_WSHLST
(
  ROWID_OBJECT             CHAR(36)        NOT NULL,
  CREATE_DATE              DATE                 DEFAULT CURRENT_DATE,
  LAST_UPDATE_DATE         DATE,
  HUB_STATE_IND            INTEGER              DEFAULT 1                     NOT NULL,
  CUST_WSHLST_CRE_DT       DATE,
  CUST_WSHLST_UPDT_DT      DATE,
  CUST_WSHLST_PUBLIC_FL    CHAR(1)         NOT NULL,
  CUST_WSHLST_FST_NM       VARCHAR(40),
  CUST_WSHLST_LST_NM       VARCHAR(40),
  CUST_WSHLST_CITY_NM      VARCHAR(36),
  CUST_WSHLST_ST_CD        VARCHAR(36),
  PRTY_ID                  CHAR(36),
  CUST_WSHLST_REGN_NM      VARCHAR(36),
  ELCTRNC_ID               CHAR(14),
  PRS_CNT_ID               CHAR(14)        DEFAULT NULL,
  CUST_WSHLST_STD_FST_NM   VARCHAR(40),
  CUST_WSHLST_STD_LST_NM   VARCHAR(40),
  CUST_WSHLST_STD_CITY_NM  VARCHAR(36),
  CUST_WSHLST_STD_REGN_NM  VARCHAR(36)
) REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (PRTY_ID) COLOCATE WITH (C_BO_PRTY);

CREATE UNIQUE INDEX SVR1_HUJS ON C_BO_CUST_WSHLST
(ROWID_OBJECT);

CREATE INDEX SVR1_I328 ON C_BO_CUST_WSHLST
(PRTY_ID);

CREATE INDEX SVR1_I3JG ON C_BO_CUST_WSHLST
(PRS_CNT_ID);

CREATE TABLE C_BO_CUST_WSHLST_XREF
(
   ROWID_XREF 			INTEGER NOT NULL,
   PKEY_SRC_OBJECT 		VARCHAR(255), 
   ROWID_OBJECT 		CHAR(36) NOT NULL, 
   ROWID_SYSTEM 		CHAR(14) NOT NULL,
   HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL,
   CREATE_DATE 			DATE DEFAULT CURRENT_DATE,
   LAST_UPDATE_DATE 		DATE
)  REDUNDANCY 0 PERSISTENT PARTITION BY COLUMN (ROWID_OBJECT) COLOCATE WITH (C_BO_CUST_WSHLST);

CREATE UNIQUE INDEX SVR1_HUV5 ON C_BO_CUST_WSHLST_XREF
(ROWID_XREF);

CREATE INDEX SVR1_HUV6 ON C_BO_CUST_WSHLST_XREF
(ROWID_OBJECT, ROWID_SYSTEM);

CREATE UNIQUE INDEX SVR1_HUV7 ON C_BO_CUST_WSHLST_XREF
(PKEY_SRC_OBJECT, ROWID_SYSTEM, HUB_STATE_IND);

CREATE TABLE C_BT_LYLTY_PCPTN_STS 
(
  ROWID_OBJECT 			CHAR(36) NOT NULL, 
  CREATOR 			VARCHAR(50) DEFAULT 'CMX', 
  CREATE_DATE 			DATE DEFAULT CURRENT_DATE, 
  UPDATED_BY 			VARCHAR(50), 
  LAST_UPDATE_DATE 		DATE, 
  CONSOLIDATION_IND 		INTEGER DEFAULT 4 NOT NULL, 
  DELETED_IND 			INTEGER, 
  DELETED_BY 			VARCHAR(50), 
  DELETED_DATE 			DATE, 
  LAST_ROWID_SYSTEM 		CHAR(14) NOT NULL, 
  DIRTY_IND 			INTEGER DEFAULT 1 NOT NULL, 
  INTERACTION_ID 		INTEGER, 
  HUB_STATE_IND 		INTEGER DEFAULT 1 NOT NULL, 
  CM_DIRTY_IND 			INTEGER, 
  PCPTN_STS_DSC 		VARCHAR(150), 
  PCPTN_STS_BEG_DT 		DATE NOT NULL, 
  PCPTN_STS_END_DT 		DATE, 
  PCPTN_STS_CD 			VARCHAR(32) DEFAULT NULL 
) PERSISTENT REPLICATE; 

CREATE INDEX SVR1_1NTD2 ON C_BT_LYLTY_PCPTN_STS 
(CONSOLIDATION_IND ASC, ROWID_OBJECT ASC);


CREATE TABLE C_BT_CNTRY
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE      ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  CNTRY_CD           VARCHAR(32 )          NOT NULL,
  CNTRY_NM           VARCHAR(100 )         NOT NULL,
  CNTRY_ISO_SHRT_CD  VARCHAR(32 ),
  CNTRY_BEG_DT       DATE                       NOT NULL,
  CNTRY_END_DT       DATE,
  CNTRY_TPHN_CD      VARCHAR(40 )
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_2EDH ON C_BT_CNTRY
(ROWID_OBJECT);

CREATE INDEX SVR1_3FSH ON C_BT_CNTRY
(CNTRY_NM);

CREATE TABLE C_BT_ST
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE      ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  ST_CD              VARCHAR(36 )          NOT NULL,
  ST_NM              VARCHAR(100 ),
  ST_USPS_CNTRY_CD   VARCHAR(32 ),
  ST_BEG_DT          DATE                       NOT NULL,
  ST_END_DT          DATE,
  ST_FIPS_NUM        INTEGER
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_2QLE ON C_BT_ST
(ROWID_OBJECT);


CREATE TABLE C_BT_REGN
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE                      ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  REGN_CD            VARCHAR(32 )          NOT NULL,
  REGN_NM            VARCHAR(100 ),
  REGN_CNTRY_CD      VARCHAR(36 )          NOT NULL,
  REGN_CNTRY_NM      VARCHAR(100 ),
  REGN_END_DT        DATE,
  REGN_BEG_DT        DATE                       NOT NULL
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_36FE ON C_BT_REGN
(ROWID_OBJECT);


CREATE TABLE C_BT_NM_PFX
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE                  ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  NM_PFX_BEG_DT      DATE                       NOT NULL,
  NM_PFX_END_DT      DATE,
  NM_PFX_CD          VARCHAR(32 )          NOT NULL,
  NM_PFX_DSC         VARCHAR(240 )
  ) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_2YUH ON C_BT_NM_PFX
(ROWID_OBJECT);


CREATE TABLE C_BT_NM_SFX
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE              ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  NM_SFX_DSC         VARCHAR(240 ),
  NM_SFX_BEG_DT      DATE                       NOT NULL,
  NM_SFX_CD          VARCHAR(32 )          NOT NULL,
  NM_SFX_END_DT      DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_356D ON C_BT_NM_SFX
(ROWID_OBJECT);


CREATE TABLE C_BT_NM_UPDT_RSN
(
  ROWID_OBJECT        CHAR(14 )             NOT NULL,
  CREATOR             VARCHAR(50 )         DEFAULT 'CMX',
  CREATE_DATE         DATE             ,
  UPDATED_BY          VARCHAR(50 ),
  LAST_UPDATE_DATE    DATE,
  CONSOLIDATION_IND   INTEGER                   DEFAULT 4                     NOT NULL,
  DELETED_IND         INTEGER,
  DELETED_BY          VARCHAR(50 ),
  DELETED_DATE        DATE,
  LAST_ROWID_SYSTEM   CHAR(14 )             NOT NULL,
  DIRTY_IND           INTEGER                   DEFAULT 1                     NOT NULL,
  INTERACTION_ID      INTEGER,
  HUB_STATE_IND       INTEGER                   DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND        INTEGER,
  NM_UPDT_RSN_DSC     VARCHAR(240 ),
  NM_UPDT_RSN_BEG_DT  DATE                      NOT NULL,
  NM_UPDT_RSN_END_DT  DATE,
  NM_UPDT_RSN_CD      VARCHAR(32 )         NOT NULL
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_3938 ON C_BT_NM_UPDT_RSN
(ROWID_OBJECT);


CREATE TABLE C_BT_CUST_TPHN_DNU_RSN
(
  ROWID_OBJECT           CHAR(14 )          NOT NULL,
  CREATOR                VARCHAR(50 )      DEFAULT 'CMX',
  CREATE_DATE            DATE                 ,
  UPDATED_BY             VARCHAR(50 ),
  LAST_UPDATE_DATE       DATE,
  CONSOLIDATION_IND      INTEGER                DEFAULT 4                     NOT NULL,
  DELETED_IND            INTEGER,
  DELETED_BY             VARCHAR(50 ),
  DELETED_DATE           DATE,
  LAST_ROWID_SYSTEM      CHAR(14 )          NOT NULL,
  DIRTY_IND              INTEGER                DEFAULT 1                     NOT NULL,
  INTERACTION_ID         INTEGER,
  HUB_STATE_IND          INTEGER                DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND           INTEGER,
  CUST_TPHN_DNU_RSN_DSC  VARCHAR(240 ),
  CUST_TPHN_DNU_RSN_CD   VARCHAR(32 )      NOT NULL
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_HO5P ON C_BT_CUST_TPHN_DNU_RSN
(ROWID_OBJECT);


CREATE TABLE C_BT_TPHN_DVC
(
  ROWID_OBJECT         CHAR(14 )            NOT NULL,
  CREATOR              VARCHAR(50 )        DEFAULT 'CMX',
  CREATE_DATE          DATE                  ,
  UPDATED_BY           VARCHAR(50 ),
  LAST_UPDATE_DATE     DATE,
  CONSOLIDATION_IND    INTEGER                  DEFAULT 4                     NOT NULL,
  DELETED_IND          INTEGER,
  DELETED_BY           VARCHAR(50 ),
  DELETED_DATE         DATE,
  LAST_ROWID_SYSTEM    CHAR(14 )            NOT NULL,
  DIRTY_IND            INTEGER                  DEFAULT 1                     NOT NULL,
  INTERACTION_ID       INTEGER,
  HUB_STATE_IND        INTEGER                  DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND         INTEGER,
  TPHN_DVC_TYP_CD      VARCHAR(32 )        NOT NULL,
  TPHN_DVC_TYP_DSC     VARCHAR(240 ),
  TPHN_DVC_BEG_DT      DATE                     NOT NULL,
  TPHN_DVC_END_DT      DATE,
  TPHN_DVC_TYP_BEG_DT  DATE                     NOT NULL,
  TPHN_DVC_TYP_END_DT  DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_321Q ON C_BT_TPHN_DVC
(ROWID_OBJECT);

CREATE TABLE C_BT_TPHN_USG
(
  ROWID_OBJECT         CHAR(14 )            NOT NULL,
  CREATOR              VARCHAR(50 )        DEFAULT 'CMX',
  CREATE_DATE          DATE                     ,
  UPDATED_BY           VARCHAR(50 ),
  LAST_UPDATE_DATE     DATE,
  CONSOLIDATION_IND    INTEGER                  DEFAULT 4                     NOT NULL,
  DELETED_IND          INTEGER,
  DELETED_BY           VARCHAR(50 ),
  DELETED_DATE         DATE,
  LAST_ROWID_SYSTEM    CHAR(14 )            NOT NULL,
  DIRTY_IND            INTEGER                  DEFAULT 1                     NOT NULL,
  INTERACTION_ID       INTEGER,
  HUB_STATE_IND        INTEGER                  DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND         INTEGER,
  TPHN_USG_TYP_CD      VARCHAR(32 )        NOT NULL,
  TPHN_USG_TYP_DSC     VARCHAR(240 ),
  TPHN_USG_TYP_BEG_DT  DATE                     NOT NULL,
  TPHN_USG_TYP_END_DT  DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_2J2C ON C_BT_TPHN_USG
(ROWID_OBJECT);

CREATE TABLE C_BT_TPHN
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE                     ,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  TPHN_TYP_CD        VARCHAR(32 )          NOT NULL,
  TPHN_TYP_DSC       VARCHAR(240 ),
  TPHN_TYP_BEG_DT    DATE                       NOT NULL,
  TPHN_TYP_END_DT    DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_2WVB ON C_BT_TPHN
(ROWID_OBJECT);



CREATE TABLE C_BT_CUST_ADDR_DNU_RSN
(
  ROWID_OBJECT              CHAR(14 )       NOT NULL,
  CREATOR                   VARCHAR(50 )   DEFAULT 'CMX',
  CREATE_DATE               DATE              ,
  UPDATED_BY                VARCHAR(50 ),
  LAST_UPDATE_DATE          DATE,
  CONSOLIDATION_IND         INTEGER             DEFAULT 4                     NOT NULL,
  DELETED_IND               INTEGER,
  DELETED_BY                VARCHAR(50 ),
  DELETED_DATE              DATE,
  LAST_ROWID_SYSTEM         CHAR(14 )       NOT NULL,
  DIRTY_IND                 INTEGER             DEFAULT 1                     NOT NULL,
  INTERACTION_ID            INTEGER,
  HUB_STATE_IND             INTEGER             DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND              INTEGER,
  CUST_ADDR_DNU_RSN_DSC     VARCHAR(240 ),
  CUST_ADDR_DNU_RSN_CD      VARCHAR(32 )   NOT NULL,
  CUST_ADDR_DNU_RSN_BEG_DT  DATE                NOT NULL,
  CUST_ADDR_DNU_RSN_END_DT  DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_HV9G ON C_BT_CUST_ADDR_DNU_RSN
(ROWID_OBJECT);


CREATE TABLE C_BT_ADDR_USAGE
(
  ROWID_OBJECT        CHAR(14 )             NOT NULL,
  CREATOR             VARCHAR(50 )         DEFAULT 'CMX',
  CREATE_DATE         DATE             ,
  UPDATED_BY          VARCHAR(50 ),
  LAST_UPDATE_DATE    DATE,
  CONSOLIDATION_IND   INTEGER                   DEFAULT 4                     NOT NULL,
  DELETED_IND         INTEGER,
  DELETED_BY          VARCHAR(50 ),
  DELETED_DATE        DATE,
  LAST_ROWID_SYSTEM   CHAR(14 )             NOT NULL,
  DIRTY_IND           INTEGER                   DEFAULT 1                     NOT NULL,
  INTERACTION_ID      INTEGER,
  HUB_STATE_IND       INTEGER                   DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND        INTEGER,
  ADDR_USAGE_CD       VARCHAR(32 )         NOT NULL,
  ADDR_USAGE_BEG_DT   DATE                      NOT NULL,
  ADDR_USAGE_END_DT   DATE,
  ADDR_USAGE_TYP_DSC  VARCHAR(240 )
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_2XXY ON C_BT_ADDR_USAGE
(ROWID_OBJECT);


CREATE TABLE C_BT_ACCT_CARD_SUB
(
  ROWID_OBJECT               CHAR(14 )      NOT NULL,
  CREATOR                    VARCHAR(50 )  DEFAULT 'CMX',
  CREATE_DATE                DATE               DEFAULT CURRENT_DATE,
  UPDATED_BY                 VARCHAR(50 ),
  LAST_UPDATE_DATE           DATE,
  CONSOLIDATION_IND          INTEGER            DEFAULT 4                     NOT NULL,
  DELETED_IND                INTEGER,
  DELETED_BY                 VARCHAR(50 ),
  DELETED_DATE               DATE,
  LAST_ROWID_SYSTEM          CHAR(14 )      NOT NULL,
  DIRTY_IND                  INTEGER            DEFAULT 1                     NOT NULL,
  INTERACTION_ID             INTEGER,
  HUB_STATE_IND              INTEGER            DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND               INTEGER,
  T_ACCT_CARD_SUBTYP_CD      VARCHAR(32 )  NOT NULL,
  T_ACCT_CARD_SUBTYP_DSC     VARCHAR(240 ),
  T_ACCT_CARD_SUBTYP_BEG_DT  DATE               NOT NULL,
  T_ACCT_CARD_SUBTYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HRWW ON C_BT_ACCT_CARD_SUB
(ROWID_OBJECT);

CREATE TABLE C_BT_ACCT_CARD
(
  ROWID_OBJECT            CHAR(14 )         NOT NULL,
  CREATOR                 VARCHAR(50 )     DEFAULT 'CMX',
  CREATE_DATE             DATE                  DEFAULT CURRENT_DATE,
  UPDATED_BY              VARCHAR(50 ),
  LAST_UPDATE_DATE        DATE,
  CONSOLIDATION_IND       INTEGER               DEFAULT 4                     NOT NULL,
  DELETED_IND             INTEGER,
  DELETED_BY              VARCHAR(50 ),
  DELETED_DATE            DATE,
  LAST_ROWID_SYSTEM       CHAR(14 )         NOT NULL,
  DIRTY_IND               INTEGER               DEFAULT 1                     NOT NULL,
  INTERACTION_ID          INTEGER,
  HUB_STATE_IND           INTEGER               DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND            INTEGER,
  T_ACCT_CARD_TYP_CD      VARCHAR(32 )     NOT NULL,
  T_ACCT_CARD_TYP_DSC     VARCHAR(240 ),
  T_ACCT_CARD_TYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HJNG ON C_BT_ACCT_CARD
(ROWID_OBJECT);

CREATE TABLE C_BT_ACCT
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE                       DEFAULT CURRENT_DATE,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  T_ACCT_TYP_CD      VARCHAR(32 )          NOT NULL,
  T_ACCT_TYP_DSC     VARCHAR(240 ),
  T_ACCT_TYP_BEG_DT  DATE                       NOT NULL,
  T_ACCT_TYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HSBV ON C_BT_ACCT
(ROWID_OBJECT);

CREATE TABLE C_BT_CUST_ACCT_RLN
(
  ROWID_OBJECT           CHAR(14 )          NOT NULL,
  CREATOR                VARCHAR(50 )      DEFAULT 'CMX',
  CREATE_DATE            DATE                   DEFAULT CURRENT_DATE,
  UPDATED_BY             VARCHAR(50 ),
  LAST_UPDATE_DATE       DATE,
  CONSOLIDATION_IND      INTEGER                DEFAULT 4                     NOT NULL,
  DELETED_IND            INTEGER,
  DELETED_BY             VARCHAR(50 ),
  DELETED_DATE           DATE,
  LAST_ROWID_SYSTEM      CHAR(14 )          NOT NULL,
  DIRTY_IND              INTEGER                DEFAULT 1                     NOT NULL,
  INTERACTION_ID         INTEGER,
  HUB_STATE_IND          INTEGER                DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND           INTEGER,
  C_ACCT_RLN_TYP_CD      VARCHAR(32 )      NOT NULL,
  C_ACCT_RLN_TYP_DSC     VARCHAR(240 ),
  C_ACCT_RLN_TYP_BEG_DT  DATE                   NOT NULL,
  C_ACCT_RLN_TYP_END_DT  DATE
) PERSISTENT REPLICATE;


CREATE UNIQUE INDEX SVR1_HPSR ON C_BT_CUST_ACCT_RLN
(ROWID_OBJECT);

CREATE TABLE C_BT_CUST_PRSNL_CNTCT
(
  ROWID_OBJECT            CHAR(14 )         NOT NULL,
  CREATOR                 VARCHAR(50 )     DEFAULT 'CMX',
  CREATE_DATE             DATE                  DEFAULT CURRENT_DATE,
  UPDATED_BY              VARCHAR(50 ),
  LAST_UPDATE_DATE        DATE,
  CONSOLIDATION_IND       INTEGER               DEFAULT 4                     NOT NULL,
  DELETED_IND             INTEGER,
  DELETED_BY              VARCHAR(50 ),
  DELETED_DATE            DATE,
  LAST_ROWID_SYSTEM       CHAR(14 )         NOT NULL,
  DIRTY_IND               INTEGER               DEFAULT 1                     NOT NULL,
  INTERACTION_ID          INTEGER,
  HUB_STATE_IND           INTEGER               DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND            INTEGER,
  PRSNL_CNTCT_TYP         VARCHAR(60 ),
  PRSNL_CNTCT_TYP_DSC     VARCHAR(240 ),
  PRSNL_CNTCT_TYP_BEG_DT  DATE                  NOT NULL,
  PRSNL_CNTCT_TYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HOIA ON C_BT_CUST_PRSNL_CNTCT
(ROWID_OBJECT);

CREATE TABLE C_BT_ADDR
(
  ROWID_OBJECT       CHAR(14 )              NOT NULL,
  CREATOR            VARCHAR(50 )          DEFAULT 'CMX',
  CREATE_DATE        DATE                       DEFAULT CURRENT_DATE,
  UPDATED_BY         VARCHAR(50 ),
  LAST_UPDATE_DATE   DATE,
  CONSOLIDATION_IND  INTEGER                    DEFAULT 4                     NOT NULL,
  DELETED_IND        INTEGER,
  DELETED_BY         VARCHAR(50 ),
  DELETED_DATE       DATE,
  LAST_ROWID_SYSTEM  CHAR(14 )              NOT NULL,
  DIRTY_IND          INTEGER                    DEFAULT 1                     NOT NULL,
  INTERACTION_ID     INTEGER,
  HUB_STATE_IND      INTEGER                    DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND       INTEGER,
  ADDR_TYP_CD        VARCHAR(32 )          NOT NULL,
  ADDR_TYP_DSC       VARCHAR(240 ),
  ADDR_TYP_BEG_DT    DATE                       NOT NULL,
  ADDR_TYP_END_DT    DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_2S1D ON C_BT_ADDR
(ROWID_OBJECT);


CREATE TABLE C_BT_ADDR_RSDNCY
(
  ROWID_OBJECT            CHAR(14 )         NOT NULL,
  CREATOR                 VARCHAR(50 )     DEFAULT 'CMX',
  CREATE_DATE             DATE                  DEFAULT CURRENT_DATE,
  UPDATED_BY              VARCHAR(50 ),
  LAST_UPDATE_DATE        DATE,
  CONSOLIDATION_IND       INTEGER               DEFAULT 4                     NOT NULL,
  DELETED_IND             INTEGER,
  DELETED_BY              VARCHAR(50 ),
  DELETED_DATE            DATE,
  LAST_ROWID_SYSTEM       CHAR(14 )         NOT NULL,
  DIRTY_IND               INTEGER               DEFAULT 1                     NOT NULL,
  INTERACTION_ID          INTEGER,
  HUB_STATE_IND           INTEGER               DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND            INTEGER,
  ADDR_RSDNCY_TYP_CD      VARCHAR(32 )     NOT NULL,
  ADDR_RSDNCY_TYP_DSC     VARCHAR(240 ),
  ADDR_RSDNCY_TYP_BEG_DT  DATE                  NOT NULL,
  ADDR_RSDNCY_TYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_2KNB ON C_BT_ADDR_RSDNCY
(ROWID_OBJECT);

CREATE TABLE C_BT_INFO_SHARE_PRTY
(
  ROWID_OBJECT              CHAR(14 )       NOT NULL,
  CREATOR                   VARCHAR(50 )   DEFAULT 'CMX',
  CREATE_DATE               DATE                DEFAULT CURRENT_DATE,
  UPDATED_BY                VARCHAR(50 ),
  LAST_UPDATE_DATE          DATE,
  CONSOLIDATION_IND         INTEGER             DEFAULT 4                     NOT NULL,
  DELETED_IND               INTEGER,
  DELETED_BY                VARCHAR(50 ),
  DELETED_DATE              DATE,
  LAST_ROWID_SYSTEM         CHAR(14 )       NOT NULL,
  DIRTY_IND                 INTEGER             DEFAULT 1                     NOT NULL,
  INTERACTION_ID            INTEGER,
  HUB_STATE_IND             INTEGER             DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND              INTEGER,
  INFO_SHR_PRTY_TYP_DSC     VARCHAR(240 ),
  INFO_SHR_PRTY_TYP_CD      VARCHAR(32 )   NOT NULL,
  INFO_SHR_PRTY_TYP_BEG_DT  DATE                NOT NULL,
  INFO_SHR_PRTY_TYP_END_DT  DATE,
  INFO_SHR_PREF_DN_SHR_FL   CHAR(1 )        NOT NULL
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HKHN ON C_BT_INFO_SHARE_PRTY
(ROWID_OBJECT);

CREATE TABLE C_BT_MKTG_EXCL
(
  ROWID_OBJECT          CHAR(14 )           NOT NULL,
  CREATOR               VARCHAR(50 )       DEFAULT 'CMX',
  CREATE_DATE           DATE                    DEFAULT CURRENT_DATE,
  UPDATED_BY            VARCHAR(50 ),
  LAST_UPDATE_DATE      DATE,
  CONSOLIDATION_IND     INTEGER                 DEFAULT 4                     NOT NULL,
  DELETED_IND           INTEGER,
  DELETED_BY            VARCHAR(50 ),
  DELETED_DATE          DATE,
  LAST_ROWID_SYSTEM     CHAR(14 )           NOT NULL,
  DIRTY_IND             INTEGER                 DEFAULT 1                     NOT NULL,
  INTERACTION_ID        INTEGER,
  HUB_STATE_IND         INTEGER                 DEFAULT 1                     NOT NULL,
  CM_DIRTY_IND          INTEGER,
  MKTG_EXCL_TYP_CD      VARCHAR(32 )       NOT NULL,
  MKTG_EXCL_TYP_DSC     VARCHAR(240 ),
  MKTG_EXCL_TYP_BEG_DT  DATE                    NOT NULL,
  MKTG_EXCL_TYP_END_DT  DATE
) PERSISTENT REPLICATE;

CREATE UNIQUE INDEX SVR1_HKTV ON C_BT_MKTG_EXCL
(ROWID_OBJECT);


CREATE VIEW FINDCUST as 
SELECT  B.HUB_STATE_IND,
            C.PSTL_LN1_TXT,
            C.PSTL_LN2_TXT,
            C.PSTL_LN3_TXT,
            C.PSTL_LN4_TXT,
            C.PSTL_CITY_NM,
            C.PSTL_CD,
            C.ST_ID,
            B.ROWID_OBJECT AS CUST_ID,
            B.PRTY_FST_NM,
            B.PRTY_LAST_NM,
            B.PRTY_CUST_INFRML_NM,
            B.PRTY_TITL_SFX_CD,
            B.NAME_PFX_CD_FK,
            B.NM_SFX_CD_FK,
            B.PRTY_HIDE_SRC_TXT,
            B.PRTY_CNTCT_METH_TYP_CD,
            C.PSTL_ORIG_LN1_TXT,
            C.PSTL_ORIG_LN2_TXT,
            C.PSTL_ORIG_LN3_TXT,
            C.PSTL_ORIG_LN4_TXT,
            B.PRTY_MID_NM,
            C.PSTL_ORIG_CITY_NM,
            C.PSTL_ORIG_CD,
            B.PRTY_ORIG_FST_NM,
            B.PRTY_ORIG_LST_NM,
            C.CUST_ADDR_DNU_RSN_ID,
            C.REGN_ID,
            C.LAST_UPDATE_DATE,
            C.CNTRY_ID,
            B.PRTY_ORIG_MID_NM
       FROM         C_BO_POSTAL_ADDR C
       INNER JOIN   C_BO_PRTY B ON B.ROWID_OBJECT = C.PRTY_ID;

CREATE VIEW WS_CUST_PKG as 
SELECT C.ROWID_OBJECT,
          C.HUB_STATE_IND,
          C.PRTY_CUST_ROLE_FL,
          C.PRTY_FST_NM,
          C.PRTY_MID_NM,
          C.PRTY_LAST_NM,
          C.PRTY_FULL_NM,
          C.PRTY_CUST_INFRML_NM,
          C.PRTY_BIRTH_DT,
          C.PRTY_GNDR_CD,
          C.PRTY_GNDR_DSC,
          C.PRTY_TRUVUE_PIN_ID,
          C.PRTY_TITL_SFX_CD,
          C.PRTY_TKN_SSN_NUM,
          C.NM_UPDT_RSN_ID,
          C.NAME_PFX_CD_FK,
          C.NM_SFX_CD_FK,
          C.PRTY_HIDE_SRC_TXT,
          C.PRTY_CNTCT_METH_TYP_CD,
          C.PRTY_RLNSHP_OKTOEMAIL_FL,
          C.PRTY_ORIG_FST_NM,
          C.PRTY_ORIG_LST_NM,
          C.PRTY_ORIG_MID_NM
    FROM C_BO_PRTY C
    WHERE C.HUB_STATE_IND = 1;

CREATE VIEW  WS_CUST_DETAIL_PKG as  
SELECT C.ROWID_OBJECT,
          C.HUB_STATE_IND,
          C.PRTY_FULL_NM,
          C.PRTY_CUST_INFRML_NM,
          C.PRTY_TKN_SSN_NUM,
          C.PRTY_BIRTH_DT,
          C.PRTY_TRUVUE_PIN_ID,
          C.PRTY_ORIG_FST_NM,
          C.PRTY_ORIG_MID_NM,
          C.PRTY_ORIG_LST_NM,
          C.PRTY_ORIG_TITL_SFX_CD,
          C.NAME_PFX_CD_FK,
          C.NM_UPDT_RSN_ID,
          C.NM_SFX_CD_FK,
          C.PRTY_CNTCT_METH_TYP_CD,
          B.IDENTITY_NM,
          C.PRTY_FST_NM,
          C.PRTY_MID_NM,
          C.PRTY_LAST_NM,
          C.PRTY_HIDE_SRC_TXT,
          P.IDENTITY_ID,
          C.PRTY_TITL_SFX_CD,
          C.PRTY_NA_SKEY
     FROM C_BO_PRTY C
          LEFT OUTER JOIN C_BO_PRTY_IDENTITY P ON C.ROWID_OBJECT = P.PRTY_ID
          LEFT OUTER JOIN C_BT_IDENTITY B ON P.IDENTITY_ID = B.ROWID_OBJECT
    WHERE C.HUB_STATE_IND = 1;
 
 CREATE VIEW BO_PRTY_XREF_PKG AS 
 SELECT ROWID_XREF, PKEY_SRC_OBJECT, 
 ROWID_OBJECT, ROWID_SYSTEM, HUB_STATE_IND, CREATE_DATE, LAST_UPDATE_DATE 
 FROM C_BO_PRTY_XREF; 

create table names (id bigint generated always as identity, fstnm varchar(50), lstnm varchar(50));
