INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = LINEITEM
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = ORDERS
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = CUSTOMER
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = PARTSUPP
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = SUPPLIER
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = PART
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = NATION
          ;
INITTASK  taskClass = gfxdperf.tpch.oracle.OracleClient
          taskMethod = dropTableTask
          threadGroups = client
          gfxdperf.tpch.TPCHPrms-tableName = REGION
          ;
