/*
 * Copyright (c) 2010-2015 Pivotal Software, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */
package com.pivotal.gemfirexd.jdbc;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import org.apache.derbyTesting.junit.JDBC;

import com.pivotal.gemfirexd.TestUtil;
import com.pivotal.gemfirexd.internal.engine.Misc;

import junit.framework.TestSuite;
import junit.textui.TestRunner;

public class LangScripts_ComparisonsTest extends JdbcTestBase {

  public static void main(String[] args) {
    TestRunner.run(new TestSuite(LangScripts_ComparisonsTest.class));
  }
  
  public LangScripts_ComparisonsTest(String name) {
    super(name); 
  }

  // This test is the as-is LangScript conversion, without any partitioning clauses
  public void testLangScript_ComparisonsTestNoPartitioning() throws Exception
  {
    // This is a JUnit conversion of the Derby Lang comparisons.sql script
    // without any GemFireXD extensions
	  
    // Catch exceptions from illegal syntax
    // Tests still not fixed marked FIXME
	  
    // Array of SQL text to execute and sqlstates to expect
    // The first object is a String, the second is either 
    // 1) null - this means query returns no rows and throws no exceptions
    // 2) a string - this means query returns no rows and throws expected SQLSTATE
    // 3) a String array - this means query returns rows which must match (unordered) given resultset
    //       - for an empty result set, an uninitialized size [0][0] array is used
    Object[][] Script_ComparisonsUT = {
	//first, do comparisons on the int type
	{ "create table inttab (c1 int, c2 int)", null },
	{ "insert into inttab values (0, 0)", null },
	{ "insert into inttab values (null, 5)", null },
	{ "insert into inttab values (1, 1)", null },
	{ "insert into inttab values (2147483647, 2147483647)", null },
	{ "select c1 from inttab where c1 = 0", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 = 1", new String [][] { {"1"} } },
	{ "select c1 from inttab where c1 = 2147483647", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 = 2", new String [0][0] },
	{ "select c1 from inttab where c1 = c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 is null", new String [][] { {null} } },
	{ "select c1 from inttab where c1 is not null", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where not c1 is null", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 0", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 1", new String [][] { {"0"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <> 2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> c1", new String [0][0] },
	{ "select c1 from inttab where c1 <> c2", new String [0][0] },
	{ "select c1 from inttab where c1 != 0", new String [][] { {"1"}, {"2147483647"} } },
	{ "select c1 from inttab where c1 != 1", new String [][] { {"0"}, {"2147483647"} } },
	{ "select c1 from inttab where c1 != 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 != 2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 != c1", new String [0][0] },
	{ "select c1 from inttab where c1 != c2", new String [0][0] },
	{ "select c1 from inttab where c1 < 0", new String [0][0] },
	{ "select c1 from inttab where c1 < 1", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 < 2", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 < 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 < c1", new String [0][0] },
	{ "select c1 from inttab where c1 < c2", new String [0][0] },
	{ "select c1 from inttab where c1 > 0", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 > 1", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 > 2", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 > 2147483647", new String [0][0] },
	{ "select c1 from inttab where c1 > c1", new String [0][0] },
	{ "select c1 from inttab where c1 > c2", new String [0][0] },
	{ "select c1 from inttab where c1 <= 0", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 <= 1", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <= 2", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <= 2147483647", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <= c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <= c2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 0", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 1", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 2", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 >= 2147483647", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 >= c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= c2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 = 0)", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 <> 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 != 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 < 0)", new String [][] { {"0"},{"1"}, {"2147483647"} } },
	{ "select c1 from inttab where not (c1 <= 0)", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 > 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 >= 0)", new String [0][0] },
	{ "create table smallinttab (c1 smallint, c2 smallint)", null },
	{ "insert into smallinttab values (0, 0)", null },
	{ "insert into smallinttab values (null, null)", null },
	{ "insert into smallinttab values (1, 1)", null },
	{ "insert into smallinttab values (32767, 32767)", null },
	{ "insert into smallinttab values (0, 9)", null },
	{ "insert into smallinttab values (null, 8)", null },
	{ "insert into smallinttab values (1, 7)", null },
	{ "insert into smallinttab values (32767, 6)", null },
	{ "select c1, c2 from smallinttab where c1 = c2", new String [][] { {"0","0"},{"1","1"},{"32767","32767"} } },
	{ "select c1 from smallinttab where c1 = 0", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 = 1", new String [][] { {"1"},{"1"} } },
	{ "select c1 from smallinttab where c1 = 32767", new String [][] { {"32767"},{"32767"} } },
	//FIXME
	// Throws data type cast exception (22018)
	// All usages of 65537 throw this exception
	//{ "select c1 from smallinttab where c1 = 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 = c1", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 1 = c1", new String [][] { {"1"},{"1"} } },
	{ "select c1 from smallinttab where 32767 = c1", new String [][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 = c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 <> c2", new String[][] { {"0","9"}, {"1","7"}, {"32767","6"} } },
	{ "select c1, c2 from smallinttab where c1 != c2", new String[][] { {"0","9"}, {"1","7"}, {"32767","6"} } },
	{ "select c1 from smallinttab where c1 <> 0", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 <> 1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where c1 <> 32767", new String [][] { {"1"},{"0"},{"1"},{"0"} } },
	{ "select c1 from smallinttab where c1 != 0", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 != 1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where c1 != 32767", new String [][] { {"1"},{"0"},{"1"},{"0"} } },
	//{ "select c1 from smallinttab where c1 <> 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 != 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 <> c1", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 <> c1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 <> c1", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where 0 != c1", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 != c1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 != c1", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where 65537 <> c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 != c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1, c2 from smallinttab where c1 < c2", new String[][] { {"0","9"}, {"1","7"} } },
	{ "select c1 from smallinttab where c1 < 0", new String[0][0] },
	{ "select c1 from smallinttab where c1 < 1", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 < 32767", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where c1 < 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 < c1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 < c1", new String[][] { {"32767"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 < c1", new String[0][0] },
	//{ "select c1 from smallinttab where 65537 < c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 > c2", new String[][] { {"32767","6"} } },
	{ "select c1 from smallinttab where c1 > 0", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 > 1", new String[][] { {"32767"},{"32767"} } },
	{ "select c1 from smallinttab where c1 > 32767", new String[0][0] },
	//{ "select c1 from smallinttab where c1 > 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 > c1", new String[0][0] },
	{ "select c1 from smallinttab where 1 > c1", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 32767 > c1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where 65537 > c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1, c2 from smallinttab where c1 <= c2", new String [][] {
		{"0","0"}, {"1","1"}, {"32767","32767"}, {"0","9"}, {"1","7"} } },
	{ "select c1 from smallinttab where c1 <= 0", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 <= 1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where c1 <= 32767", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 <= 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 <= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 <= c1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 <= c1", new String[][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 <= c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 >= c2", new String[][] {
		{"0","0"},{"1","1"},{"32767","32767"},{"32767","6"} } },
	{ "select c1 from smallinttab where c1 >= 0", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 >= 1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 >= 32767", new String[][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 >= 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 >= c1", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 1 >= c1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where 32767 >= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 is null", new String[][] { {null},{null} } },
	{ "select c1 from smallinttab where c1 is not null", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where not c1 is null", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 >= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "create table biginttab (c1 bigint, c2 bigint, c3 int, c4 smallint)", null },
	{ "insert into biginttab values (0, 0, 0, 0 )", null },
	{ "insert into biginttab values (null, null, null, null)", null },
	{ "insert into biginttab values (9223372036854775807, 9223372036854775807, 2147483647, 32767)", null },
	{ "insert into biginttab values (-9223372036854775808, -9223372036854775808, -2147483648, -32768)", null },
	{ "select c1, c2 from biginttab where c1 = c2", new String [][] {
		{"0","0"},{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 = 0", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c1 = c3", new String[][] { {"0"} } },
	{ "select c1 from biginttab where 0 = c1", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c3 = c1", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c1 = c4", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c4 = c1", new String[][] { {"0"} } },
	{ "select c1, c2 from biginttab where c1 <> c2", new String[0][0] },
	{ "select c1 from biginttab where c1 <> 0", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <> c3", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <> c4", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1, c2 from biginttab where c1 < c2", new String[0][0] },
	{ "select c1 from biginttab where c1 < 0", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 < c3", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c3 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 < c4", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1, c2 from biginttab where c1 > c2", new String[0][0] },
	{ "select c1 from biginttab where c1 > 0", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 > c3", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where 0 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 > c4", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c4 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1, c2 from biginttab where c1 <= c2", new String[][] { {"0","0"},
		{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <= 0", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <= c3", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c3 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 <= c4", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1, c2 from biginttab where c1 >= c2", new String[][] { {"0","0"},
		{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 >= 0", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 >= c3", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where 0 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 >= c4", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c4 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 is null", new String[][] { {null} } },
	{ "select c1 from biginttab where c1 is not null", new String[][] { {"0"}, {"9223372036854775807"}, {"-9223372036854775808"} } },
	{ "select c1 from biginttab where not c1 is null", new String[][] { {"0"}, {"9223372036854775807"}, {"-9223372036854775808"} } },
	// Char (result checking is done with trimming trailing blanks, but important test is count of rows returned
	// and verifying non-blank-padded values
	{ "create table chartab (c1 char(1), c2 char(5))", null },
	{ "insert into chartab values (' ', '     ')", null },
	{ "insert into chartab values ('a', 'a    ')", null },
	{ "insert into chartab values ('b', 'bcdef')", null },
	{ "insert into chartab values (null, null)", null },
	{ "select c1 from chartab where c1 = ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 = '     '", new String[][] { {"     "} } },
	{ "select c1 from chartab where c1 = 'a'", new String[][] { {"a"} } },
	{ "select c2 from chartab where c2 = 'a    '", new String[][] { {"a"} } },
	{ "select c1 from chartab where c1 = 'b'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 = 'bcdef'", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 = ''", new String[][] { {""} } },
	{ "select c1 from chartab where c1 = '                      '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 = ''", new String[][] { {"     "} } },
	{ "select c2 from chartab where c2 = ' '", new String[][] { {"     "} } },
	{ "select c2 from chartab where c2 = '                           '", new String[][] { {"     "} } },
	{ "select c1 from chartab where c1 = 'a        '", new String[][] { {"a"} } },
	{ "select c2 from chartab where c2 = 'a '", new String[][] { {"a"} } },
	{ "select c1 from chartab where c1 = 'b             '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 = 'bcdef                '", new String[][] { {"bcdef"} } },
	{ "select c2 from chartab where c2 = 'bcde       '", new String[0][0] },
	{ "select c1, c2 from chartab where c1 = c2", new String[][] { {" ","     "}, {"a","a"} } },
	{ "select c1 from chartab where c1 is null", new String[][] { {null} } },
	{ "select c1 from chartab where c1 is not null", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where not c1 is null", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where c1 <> ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 <> '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'a'", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 <> 'a    '", new String[][] { {"     "},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcdef'", new String[][] { {"     "},{"a"} } },
	{ "select c1 from chartab where c1 != ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 != '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 != 'a'", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 != 'a    '", new String[][] { {"     "},{"bcdef"} } },
	{ "select c1 from chartab where c1 != 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 != 'bcdef'", new String[][] { {"     "},{"a"} } },
	{ "select c1 from chartab where c1 <> ''", new String[][] { {"a"},{"b"} } },
	{ "select c1 from chartab where c1 <> '                      '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 <> ''", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <> ' '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <> '                           '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'a        '", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 <> 'a '", new String[][] { {" "},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'b             '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcdef                '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcde       '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1, c2 from chartab where c1 <> c2", new String[][] { {"b","bcdef"} } },
	{ "select c1 from chartab where c1 < ' '", new String[0][0] },
	{ "select c2 from chartab where c2 < '     '", new String[0][0] },
	{ "select c1 from chartab where c1 < 'a'", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 < 'a    '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 < 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcdef'", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 < ''", new String[0][0] },
	{ "select c1 from chartab where c1 < '                      '", new String[0][0] },
	{ "select c2 from chartab where c2 < ''", new String[0][0] },
	{ "select c2 from chartab where c2 < ' '", new String[0][0] },
	{ "select c2 from chartab where c2 < '                           '", new String[0][0] },
	{ "select c1 from chartab where c1 < 'a        '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 < 'a '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 < 'b             '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcdef                '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcde       '", new String[][] { {" "},{"a"} } },
	{ "select c1, c2 from chartab where c1 < c2", new String[][] { {"b","bcdef"} } },
	{ "select c1 from chartab where c1 > ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 > '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 > 'a'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 > 'a    '", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 > 'b'", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcdef'", new String[0][0] },
	{ "select c1 from chartab where c1 > ''", new String[][] { {"a"},{"b"} } },
	{ "select c1 from chartab where c1 > '                      '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 > ''", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 > ' '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 > '                           '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 > 'a        '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 > 'a '", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 > 'b             '", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcdef                '", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcde       '", new String[][] { {"bcdef"} } },
	{ "select c1, c2 from chartab where c1 > c2", new String[0][0] },
	{ "select c1 from chartab where c1 <= ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= '     '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= 'a'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <= 'a    '", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 <= 'b'", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 <= 'bcdef'", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <= ''", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= '                      '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= ''", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= '                           '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= 'a        '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <= 'a '", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 <= 'b             '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 <= 'bcdef                '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <= 'bcde       '", new String[][] { {" "},{"a"} } },
	{ "select c1, c2 from chartab where c1 <= c2", new String[][] { {" "," "},{"a","a"},{"b","bcdef"} } },
	{ "select c1 from chartab where c1 >= ' '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= '     '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'a'", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= 'a    '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'b'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 >= 'bcdef'", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 >= ''", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where c1 >= '                      '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= ''", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 >= ' '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 >= '                           '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'a        '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= 'a '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'b             '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 >= 'bcdef                '", new String[][] { {"bcdef"} } },
	{ "select c2 from chartab where c2 >= 'bcde       '", new String[][] { {"bcdef"} } },
	{ "select c1, c2 from chartab where c1 >= c2", new String[][] { {" "," "},{"a","a"} } },
	// Varchar
	{ "create table varchartab (c1 varchar(1), c2 varchar(1), c3 varchar(5),c4 varchar(5))", null },
	{ "insert into varchartab values ('', '', '', '')", null },
	{ "insert into varchartab values ('a', 'a', 'a', 'a')", null },
	{ "insert into varchartab values ('b', 'b', 'bcdef', 'bcdef')", null },
	{ "insert into varchartab values (null, null, null, null)", null },
	{ "insert into varchartab values ('', null, '', null)", null },
	{ "insert into varchartab values ('a', 'b', 'a', 'b')", null },
	{ "insert into varchartab values ('b', '', 'b', 'bcdef')", null },
	{ "select c1 from varchartab where c1 = c2", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 = c4", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from varchartab where c1 = '                 '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 = ''", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 = 'a '", new String[][] { {"a"},{"a"} } },
	{ "select c1 from varchartab where c1 = 'b                               '", new String[][] { {"b"},{"b"} } },
	// FIXME
	// This matches both rows due to truncation bug
	//{ "select c1 from varchartab where c1 = 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 = ' '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 = ''", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 = 'a    '", new String[][] { {"a"},{"a"} } },
	{ "select c3 from varchartab where c3 = 'bcdef                   '", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where c3 =  'bbbb'", new String[0][0] },
	{ "select c1 from varchartab where '                 ' = c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where '' = c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'a ' = c1", new String[][] { {"a"},{"a"} } },
	{ "select c1 from varchartab where 'b                               ' = c1", new String[][] { {"b"},{"b"} } },
	// FIXME
	//{ "select c1 from varchartab where 'bb' = c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' = c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where '' = c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'a    ' = c3", new String[][] { {"a"},{"a"} } },
	{ "select c3 from varchartab where 'bcdef                   ' = c3", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where 'bbbb' = c3", new String[0][0] },
	{ "select c1 from varchartab where c1 <> c2", new String[][] { {"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> c4", new String[][] { {"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> 'a '", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where c1 <> 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	// FIXME
	//{ "select c1 from varchartab where c1 <> 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'a    '", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'bbbb'", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != 'a '", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where c1 != 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where c1 != 'bb'",  new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != 'a    '", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where c3 != 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != 'bbbb'", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' <> c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' <> c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' <> c1", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' <> c1", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where 'bb' <> c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' <> c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' <> c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' <> c3", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' <> c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' <> c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 < c2", new String[][] { {"a"} } },
	{ "select c3 from varchartab where c3 < c4", new String[][] { {"a"},{"b"} } },
	{ "select c1 from varchartab where c1 < '                 '", new String[0][0] },
	{ "select c1 from varchartab where c1 < ''", new String[0][0] },
	{ "select c1 from varchartab where c1 < 'a '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 < 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where c1 < 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 < ' '", new String[0][0] },
	{ "select c3 from varchartab where c3 < ''", new String[0][0] },
	{ "select c3 from varchartab where c3 < 'a    '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 < 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 < 'bbbb'", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' < c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' < c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' < c1", new String[][] { {"b"},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' < c1", new String[0][0] },
	//{ "select c1 from varchartab where 'bb' < c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' < c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' < c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' < c3", new String[][] { {"bcdef"},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' < c3", new String[0][0] },
	{ "select c3 from varchartab where 'bbbb' < c3", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where c1 > c2", new String[][] { {"b"} } },
	{ "select c3 from varchartab where c3 > c4", new String[0][0] },
	{ "select c1 from varchartab where c1 > '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 > ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 > 'a '", new String[][] { {"b"},{"b"} } },
	{ "select c1 from varchartab where c1 > 'b                               '", new String[0][0] },
	//{ "select c1 from varchartab where c1 > 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 > ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 > ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 > 'a    '", new String[][] { {"bcdef"},{"b"} } },
	{ "select c3 from varchartab where c3 > 'bcdef                   '", new String[0][0] },
	{ "select c3 from varchartab where c3 > 'bbbb'", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where '                 ' > c1", new String[0][0] },
	{ "select c1 from varchartab where '' > c1", new String[0][0] },
	{ "select c1 from varchartab where 'a ' > c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'b                               ' > c1", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where 'bb' > c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' > c3", new String[0][0] },
	{ "select c3 from varchartab where '' > c3", new String[0][0] },
	{ "select c3 from varchartab where 'a    ' > c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'bcdef                   ' > c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' > c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <= c2", new String[][] { {""},{"a"},{"b"},{"a"} } },
	{ "select c3 from varchartab where c3 <= c4", new String[][] { {""},{"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <= '                 '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 <= ''", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 <= 'a '", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c1 from varchartab where c1 <= 'b                               '", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	//{ "select c1 from varchartab where c1 <= 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <= ' '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 <= ''", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 <= 'a    '", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c3 from varchartab where c3 <= 'bcdef                   '", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <= 'bbbb'", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' <= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' <= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' <= c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' <= c1", new String[][] { {"b"},{"b"} } },
	//{ "select c1 from varchartab where 'bb' <= c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' <= c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' <= c3",new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' <= c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' <= c3", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where 'bbbb' <= c3", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where c1 >= c2", new String[][] { {""},{"a"},{"b"},{"b"} } },
	{ "select c3 from varchartab where c3 >= c4", new String[][] { {""},{"a"},{"bcdef"} } },
	{ "select c1 from varchartab where c1 >= '                 '", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= ''", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= 'a '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= 'b                               '", new String[][] { {"b"},{"b"} } },
	//{ "select c1 from varchartab where c1 >= 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 >= ' '", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= ''", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= 'a    '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= 'bcdef                   '", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where c3 >= 'bbbb'", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where '                 ' >= c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where '' >= c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'a ' >= c1", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c1 from varchartab where 'b                               ' >= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	//{ "select c1 from varchartab where 'bb' >= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' >= c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where '' >= c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'a    ' >= c3", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c3 from varchartab where 'bcdef                   ' >= c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' >= c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 is null", new String[][] { {null} } },
	{ "select c1 from varchartab where c1 is not null", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where not c1 is null", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "drop table smallinttab", null },
	{ "drop table biginttab", null },
	{ "drop table chartab", null },
	{ "drop table varchartab", null },
	{ "drop table inttab", null }
    };

    // Do not use partitioning as default, use replicate
    // (Some results are expected to be different with partitioning)
    skipDefaultPartitioned = true;

    Connection conn = TestUtil.getConnection();
    Statement stmt = conn.createStatement();
    // Go through the array, execute each string[0], check sqlstate [1]
    // This will fail on the first one that succeeds where it shouldn't
    // or throws unknown exception
    JDBC.SQLUnitTestHelper(stmt,Script_ComparisonsUT);
  }
  
  // This test is the script enhanced with partitioning
  public void testLangScript_ComparisonsWithPartitioning() throws Exception
  {
    // This form of the comparisons.sql test has partitioning clauses
    Object[][] Script_ComparisonsUTPartitioning = {
	//first, do comparisons on the int type
	{ "create table inttab (c1 int, c2 int) partition by column(c1)", null },
	{ "insert into inttab values (0, 0)", null },
	{ "insert into inttab values (null, 5)", null },
	{ "insert into inttab values (1, 1)", null },
	{ "insert into inttab values (2147483647, 2147483647)", null },
	{ "select c1 from inttab where c1 = 0", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 = 1", new String [][] { {"1"} } },
	{ "select c1 from inttab where c1 = 2147483647", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 = 2", new String [0][0] },
	{ "select c1 from inttab where c1 = c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 is null", new String [][] { {null} } },
	{ "select c1 from inttab where c1 is not null", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where not c1 is null", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 0", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 1", new String [][] { {"0"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <> 2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <> c1", new String [0][0] },
	{ "select c1 from inttab where c1 <> c2", new String [0][0] },
	{ "select c1 from inttab where c1 != 0", new String [][] { {"1"}, {"2147483647"} } },
	{ "select c1 from inttab where c1 != 1", new String [][] { {"0"}, {"2147483647"} } },
	{ "select c1 from inttab where c1 != 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 != 2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 != c1", new String [0][0] },
	{ "select c1 from inttab where c1 != c2", new String [0][0] },
	{ "select c1 from inttab where c1 < 0", new String [0][0] },
	{ "select c1 from inttab where c1 < 1", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 < 2", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 < 2147483647", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 < c1", new String [0][0] },
	{ "select c1 from inttab where c1 < c2", new String [0][0] },
	{ "select c1 from inttab where c1 > 0", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 > 1", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 > 2", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 > 2147483647", new String [0][0] },
	{ "select c1 from inttab where c1 > c1", new String [0][0] },
	{ "select c1 from inttab where c1 > c2", new String [0][0] },
	{ "select c1 from inttab where c1 <= 0", new String [][] { {"0"} } },
	{ "select c1 from inttab where c1 <= 1", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <= 2", new String [][] { {"0"},{"1"} } },
	{ "select c1 from inttab where c1 <= 2147483647", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <= c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 <= c2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 0", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 1", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= 2", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 >= 2147483647", new String [][] { {"2147483647"} } },
	{ "select c1 from inttab where c1 >= c1", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where c1 >= c2", new String [][] { {"0"},{"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 = 0)", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 <> 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 != 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 < 0)", new String [][] { {"0"},{"1"}, {"2147483647"} } },
	{ "select c1 from inttab where not (c1 <= 0)", new String [][] { {"1"},{"2147483647"} } },
	{ "select c1 from inttab where not (c1 > 0)", new String [][] { {"0"} } },
	{ "select c1 from inttab where not (c1 >= 0)", new String [0][0] },
	{ "create table smallinttab (c1 smallint, c2 smallint) partition by column(c1)", null },
	{ "insert into smallinttab values (0, 0)", null },
	{ "insert into smallinttab values (null, null)", null },
	{ "insert into smallinttab values (1, 1)", null },
	{ "insert into smallinttab values (32767, 32767)", null },
	{ "insert into smallinttab values (0, 9)", null },
	{ "insert into smallinttab values (null, 8)", null },
	{ "insert into smallinttab values (1, 7)", null },
	{ "insert into smallinttab values (32767, 6)", null },
	{ "select c1, c2 from smallinttab where c1 = c2", new String [][] { {"0","0"},{"1","1"},{"32767","32767"} } },
	{ "select c1 from smallinttab where c1 = 0", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 = 1", new String [][] { {"1"},{"1"} } },
	{ "select c1 from smallinttab where c1 = 32767", new String [][] { {"32767"},{"32767"} } },
	//FIXME
	// Throws data type cast exception (22018)
	// All usages of 65537 throw this exception
	//{ "select c1 from smallinttab where c1 = 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 = c1", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 1 = c1", new String [][] { {"1"},{"1"} } },
	{ "select c1 from smallinttab where 32767 = c1", new String [][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 = c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 <> c2", new String[][] { {"0","9"}, {"1","7"}, {"32767","6"} } },
	{ "select c1, c2 from smallinttab where c1 != c2", new String[][] { {"0","9"}, {"1","7"}, {"32767","6"} } },
	{ "select c1 from smallinttab where c1 <> 0", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 <> 1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where c1 <> 32767", new String [][] { {"1"},{"0"},{"1"},{"0"} } },
	{ "select c1 from smallinttab where c1 != 0", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 != 1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where c1 != 32767", new String [][] { {"1"},{"0"},{"1"},{"0"} } },
	//{ "select c1 from smallinttab where c1 <> 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 != 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 <> c1", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 <> c1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 <> c1", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where 0 != c1", new String [][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 != c1", new String [][] { {"0"},{"32767"},{"0"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 != c1", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where 65537 <> c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 != c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1, c2 from smallinttab where c1 < c2", new String[][] { {"0","9"}, {"1","7"} } },
	{ "select c1 from smallinttab where c1 < 0", new String[0][0] },
	{ "select c1 from smallinttab where c1 < 1", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 < 32767", new String [][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where c1 < 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 < c1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 < c1", new String[][] { {"32767"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 < c1", new String[0][0] },
	//{ "select c1 from smallinttab where 65537 < c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 > c2", new String[][] { {"32767","6"} } },
	{ "select c1 from smallinttab where c1 > 0", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 > 1", new String[][] { {"32767"},{"32767"} } },
	{ "select c1 from smallinttab where c1 > 32767", new String[0][0] },
	//{ "select c1 from smallinttab where c1 > 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 > c1", new String[0][0] },
	{ "select c1 from smallinttab where 1 > c1", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 32767 > c1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	//{ "select c1 from smallinttab where 65537 > c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1, c2 from smallinttab where c1 <= c2", new String [][] {
		{"0","0"}, {"1","1"}, {"32767","32767"}, {"0","9"}, {"1","7"} } },
	{ "select c1 from smallinttab where c1 <= 0", new String[][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where c1 <= 1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where c1 <= 32767", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 <= 65537", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 0 <= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 1 <= c1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where 32767 <= c1", new String[][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 <= c1", new String[0][0] },
	{ "select c1, c2 from smallinttab where c1 >= c2", new String[][] {
		{"0","0"},{"1","1"},{"32767","32767"},{"32767","6"} } },
	{ "select c1 from smallinttab where c1 >= 0", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 >= 1", new String[][] { {"1"},{"32767"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 >= 32767", new String[][] { {"32767"},{"32767"} } },
	//{ "select c1 from smallinttab where c1 >= 65537", new String[0][0] },
	{ "select c1 from smallinttab where 0 >= c1", new String [][] { {"0"},{"0"} } },
	{ "select c1 from smallinttab where 1 >= c1", new String[][] { {"0"},{"1"},{"0"},{"1"} } },
	{ "select c1 from smallinttab where 32767 >= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where c1 is null", new String[][] { {null},{null} } },
	{ "select c1 from smallinttab where c1 is not null", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "select c1 from smallinttab where not c1 is null", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	//{ "select c1 from smallinttab where 65537 >= c1", new String[][] { {"0"},{"1"},{"32767"},{"0"},{"1"},{"32767"} } },
	{ "create table biginttab (c1 bigint, c2 bigint, c3 int, c4 smallint) partition by column(c1)", null },
	{ "insert into biginttab values (0, 0, 0, 0 )", null },
	{ "insert into biginttab values (null, null, null, null)", null },
	{ "insert into biginttab values (9223372036854775807, 9223372036854775807, 2147483647, 32767)", null },
	{ "insert into biginttab values (-9223372036854775808, -9223372036854775808, -2147483648, -32768)", null },
	{ "select c1, c2 from biginttab where c1 = c2", new String [][] {
		{"0","0"},{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 = 0", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c1 = c3", new String[][] { {"0"} } },
	{ "select c1 from biginttab where 0 = c1", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c3 = c1", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c1 = c4", new String[][] { {"0"} } },
	{ "select c1 from biginttab where c4 = c1", new String[][] { {"0"} } },
	{ "select c1, c2 from biginttab where c1 <> c2", new String[0][0] },
	{ "select c1 from biginttab where c1 <> 0", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <> c3", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <> c4", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 <> c1", new String[][] { {"9223372036854775807"},{"-9223372036854775808"} } },
	{ "select c1, c2 from biginttab where c1 < c2", new String[0][0] },
	{ "select c1 from biginttab where c1 < 0", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 < c3", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c3 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 < c4", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 < c1", new String[][] { {"9223372036854775807"} } },
	{ "select c1, c2 from biginttab where c1 > c2", new String[0][0] },
	{ "select c1 from biginttab where c1 > 0", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 > c3", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where 0 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 > c4", new String[][] { {"9223372036854775807"} } },
	{ "select c1 from biginttab where c4 > c1", new String[][] { {"-9223372036854775808"} } },
	{ "select c1, c2 from biginttab where c1 <= c2", new String[][] { {"0","0"},
		{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <= 0", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 <= c3", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where 0 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c3 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 <= c4", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c4 <= c1", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1, c2 from biginttab where c1 >= c2", new String[][] { {"0","0"},
		{"9223372036854775807","9223372036854775807"}, {"-9223372036854775808","-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 >= 0", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c1 >= c3", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where 0 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c3 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 >= c4", new String[][] { {"0"},{"9223372036854775807"} } },
	{ "select c1 from biginttab where c4 >= c1", new String[][] { {"0"},{"-9223372036854775808"} } },
	{ "select c1 from biginttab where c1 is null", new String[][] { {null} } },
	{ "select c1 from biginttab where c1 is not null", new String[][] { {"0"}, {"9223372036854775807"}, {"-9223372036854775808"} } },
	{ "select c1 from biginttab where not c1 is null", new String[][] { {"0"}, {"9223372036854775807"}, {"-9223372036854775808"} } },
	// Char (result checking is done with trimming trailing blanks, but important test is count of rows returned
	// and verifying non-blank-padded values
	{ "create table chartab (c1 char(1), c2 char(5)) partition by column(c1)", null },
	{ "insert into chartab values (' ', '     ')", null },
	{ "insert into chartab values ('a', 'a    ')", null },
	{ "insert into chartab values ('b', 'bcdef')", null },
	{ "insert into chartab values (null, null)", null },
	{ "select c1 from chartab where c1 = ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 = '     '", new String[][] { {"     "} } },
	{ "select c1 from chartab where c1 = 'a'", new String[][] { {"a"} } },
	{ "select c2 from chartab where c2 = 'a    '", new String[][] { {"a"} } },
	{ "select c1 from chartab where c1 = 'b'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 = 'bcdef'", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 = ''", new String[][] { {""} } },
	{ "select c1 from chartab where c1 = '                      '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 = ''", new String[][] { {"     "} } },
	{ "select c2 from chartab where c2 = ' '", new String[][] { {"     "} } },
	{ "select c2 from chartab where c2 = '                           '", new String[][] { {"     "} } },
	{ "select c1 from chartab where c1 = 'a        '", new String[][] { {"a"} } },
	{ "select c2 from chartab where c2 = 'a '", new String[][] { {"a"} } },
	{ "select c1 from chartab where c1 = 'b             '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 = 'bcdef                '", new String[][] { {"bcdef"} } },
	{ "select c2 from chartab where c2 = 'bcde       '", new String[0][0] },
	{ "select c1, c2 from chartab where c1 = c2", new String[][] { {" ","     "}, {"a","a"} } },
	{ "select c1 from chartab where c1 is null", new String[][] { {null} } },
	{ "select c1 from chartab where c1 is not null", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where not c1 is null", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where c1 <> ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 <> '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'a'", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 <> 'a    '", new String[][] { {"     "},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcdef'", new String[][] { {"     "},{"a"} } },
	{ "select c1 from chartab where c1 != ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 != '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 != 'a'", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 != 'a    '", new String[][] { {"     "},{"bcdef"} } },
	{ "select c1 from chartab where c1 != 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 != 'bcdef'", new String[][] { {"     "},{"a"} } },
	{ "select c1 from chartab where c1 <> ''", new String[][] { {"a"},{"b"} } },
	{ "select c1 from chartab where c1 <> '                      '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 <> ''", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <> ' '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <> '                           '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'a        '", new String[][] { {" "},{"b"} } },
	{ "select c2 from chartab where c2 <> 'a '", new String[][] { {" "},{"bcdef"} } },
	{ "select c1 from chartab where c1 <> 'b             '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcdef                '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <> 'bcde       '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1, c2 from chartab where c1 <> c2", new String[][] { {"b","bcdef"} } },
	{ "select c1 from chartab where c1 < ' '", new String[0][0] },
	{ "select c2 from chartab where c2 < '     '", new String[0][0] },
	{ "select c1 from chartab where c1 < 'a'", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 < 'a    '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 < 'b'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcdef'", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 < ''", new String[0][0] },
	{ "select c1 from chartab where c1 < '                      '", new String[0][0] },
	{ "select c2 from chartab where c2 < ''", new String[0][0] },
	{ "select c2 from chartab where c2 < ' '", new String[0][0] },
	{ "select c2 from chartab where c2 < '                           '", new String[0][0] },
	{ "select c1 from chartab where c1 < 'a        '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 < 'a '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 < 'b             '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcdef                '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 < 'bcde       '", new String[][] { {" "},{"a"} } },
	{ "select c1, c2 from chartab where c1 < c2", new String[][] { {"b","bcdef"} } },
	{ "select c1 from chartab where c1 > ' '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 > '     '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 > 'a'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 > 'a    '", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 > 'b'", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcdef'", new String[0][0] },
	{ "select c1 from chartab where c1 > ''", new String[][] { {"a"},{"b"} } },
	{ "select c1 from chartab where c1 > '                      '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 > ''", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 > ' '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 > '                           '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 > 'a        '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 > 'a '", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 > 'b             '", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcdef                '", new String[0][0] },
	{ "select c2 from chartab where c2 > 'bcde       '", new String[][] { {"bcdef"} } },
	{ "select c1, c2 from chartab where c1 > c2", new String[0][0] },
	{ "select c1 from chartab where c1 <= ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= '     '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= 'a'", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <= 'a    '", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 <= 'b'", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 <= 'bcdef'", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 <= ''", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= '                      '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= ''", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= ' '", new String[][] { {" "} } },
	{ "select c2 from chartab where c2 <= '                           '", new String[][] { {" "} } },
	{ "select c1 from chartab where c1 <= 'a        '", new String[][] { {" "},{"a"} } },
	{ "select c2 from chartab where c2 <= 'a '", new String[][] { {" "},{"a"} } },
	{ "select c1 from chartab where c1 <= 'b             '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 <= 'bcdef                '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 <= 'bcde       '", new String[][] { {" "},{"a"} } },
	{ "select c1, c2 from chartab where c1 <= c2", new String[][] { {" "," "},{"a","a"},{"b","bcdef"} } },
	{ "select c1 from chartab where c1 >= ' '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= '     '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'a'", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= 'a    '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'b'", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 >= 'bcdef'", new String[][] { {"bcdef"} } },
	{ "select c1 from chartab where c1 >= ''", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c1 from chartab where c1 >= '                      '", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= ''", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 >= ' '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c2 from chartab where c2 >= '                           '", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'a        '", new String[][] { {"a"},{"b"} } },
	{ "select c2 from chartab where c2 >= 'a '", new String[][] { {"a"},{"bcdef"} } },
	{ "select c1 from chartab where c1 >= 'b             '", new String[][] { {"b"} } },
	{ "select c2 from chartab where c2 >= 'bcdef                '", new String[][] { {"bcdef"} } },
	{ "select c2 from chartab where c2 >= 'bcde       '", new String[][] { {"bcdef"} } },
	{ "select c1, c2 from chartab where c1 >= c2", new String[][] { {" "," "},{"a","a"} } },
	// Varchar
	{ "create table varchartab (c1 varchar(1), c2 varchar(1), c3 varchar(5),c4 varchar(5)) partition by column(c1)", null },
	{ "insert into varchartab values ('', '', '', '')", null },
	{ "insert into varchartab values ('a', 'a', 'a', 'a')", null },
	{ "insert into varchartab values ('b', 'b', 'bcdef', 'bcdef')", null },
	{ "insert into varchartab values (null, null, null, null)", null },
	{ "insert into varchartab values ('', null, '', null)", null },
	{ "insert into varchartab values ('a', 'b', 'a', 'b')", null },
	{ "insert into varchartab values ('b', '', 'b', 'bcdef')", null },
	{ "select c1 from varchartab where c1 = c2", new String[][] { {" "},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 = c4", new String[][] { {" "},{"a"},{"bcdef"} } },
	{ "select c1 from varchartab where c1 = '                 '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 = ''", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 = 'a '", new String[][] { {"a"},{"a"} } },
	{ "select c1 from varchartab where c1 = 'b                               '", new String[][] { {"b"},{"b"} } },
	// FIXME
	// This matches both rows due to truncation bug
	//{ "select c1 from varchartab where c1 = 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 = ' '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 = ''", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 = 'a    '", new String[][] { {"a"},{"a"} } },
	{ "select c3 from varchartab where c3 = 'bcdef                   '", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where c3 =  'bbbb'", new String[0][0] },
	{ "select c1 from varchartab where '                 ' = c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where '' = c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'a ' = c1", new String[][] { {"a"},{"a"} } },
	{ "select c1 from varchartab where 'b                               ' = c1", new String[][] { {"b"},{"b"} } },
	// FIXME
	//{ "select c1 from varchartab where 'bb' = c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' = c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where '' = c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'a    ' = c3", new String[][] { {"a"},{"a"} } },
	{ "select c3 from varchartab where 'bcdef                   ' = c3", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where 'bbbb' = c3", new String[0][0] },
	{ "select c1 from varchartab where c1 <> c2", new String[][] { {"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> c4", new String[][] { {"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <> 'a '", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where c1 <> 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	// FIXME
	//{ "select c1 from varchartab where c1 <> 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'a    '", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <> 'bbbb'", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 != 'a '", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where c1 != 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where c1 != 'bb'",  new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != 'a    '", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where c3 != 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 != 'bbbb'", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' <> c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' <> c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' <> c1", new String[][] { {""},{"b"},{""},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' <> c1", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where 'bb' <> c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' <> c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' <> c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' <> c3", new String[][] { {""},{"bcdef"},{""},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' <> c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' <> c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 < c2", new String[][] { {"a"} } },
	{ "select c3 from varchartab where c3 < c4", new String[][] { {"a"},{"b"} } },
	{ "select c1 from varchartab where c1 < '                 '", new String[0][0] },
	{ "select c1 from varchartab where c1 < ''", new String[0][0] },
	{ "select c1 from varchartab where c1 < 'a '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 < 'b                               '", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where c1 < 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 < ' '", new String[0][0] },
	{ "select c3 from varchartab where c3 < ''", new String[0][0] },
	{ "select c3 from varchartab where c3 < 'a    '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 < 'bcdef                   '", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 < 'bbbb'", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' < c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' < c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' < c1", new String[][] { {"b"},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' < c1", new String[0][0] },
	//{ "select c1 from varchartab where 'bb' < c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' < c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' < c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' < c3", new String[][] { {"bcdef"},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' < c3", new String[0][0] },
	{ "select c3 from varchartab where 'bbbb' < c3", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where c1 > c2", new String[][] { {"b"} } },
	{ "select c3 from varchartab where c3 > c4", new String[0][0] },
	{ "select c1 from varchartab where c1 > '                 '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 > ''", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 > 'a '", new String[][] { {"b"},{"b"} } },
	{ "select c1 from varchartab where c1 > 'b                               '", new String[0][0] },
	//{ "select c1 from varchartab where c1 > 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 > ' '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 > ''", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 > 'a    '", new String[][] { {"bcdef"},{"b"} } },
	{ "select c3 from varchartab where c3 > 'bcdef                   '", new String[0][0] },
	{ "select c3 from varchartab where c3 > 'bbbb'", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where '                 ' > c1", new String[0][0] },
	{ "select c1 from varchartab where '' > c1", new String[0][0] },
	{ "select c1 from varchartab where 'a ' > c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'b                               ' > c1", new String[][] { {""},{"a"},{""},{"a"} } },
	//{ "select c1 from varchartab where 'bb' > c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' > c3", new String[0][0] },
	{ "select c3 from varchartab where '' > c3", new String[0][0] },
	{ "select c3 from varchartab where 'a    ' > c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'bcdef                   ' > c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' > c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <= c2", new String[][] { {""},{"a"},{"b"},{"a"} } },
	{ "select c3 from varchartab where c3 <= c4", new String[][] { {""},{"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 <= '                 '", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 <= ''", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where c1 <= 'a '", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c1 from varchartab where c1 <= 'b                               '", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	//{ "select c1 from varchartab where c1 <= 'bb'", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <= ' '", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 <= ''", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where c3 <= 'a    '", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c3 from varchartab where c3 <= 'bcdef                   '", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 <= 'bbbb'", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '                 ' <= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where '' <= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'a ' <= c1", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where 'b                               ' <= c1", new String[][] { {"b"},{"b"} } },
	//{ "select c1 from varchartab where 'bb' <= c1", new String[0][0] },
	{ "select c3 from varchartab where ' ' <= c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where '' <= c3",new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'a    ' <= c3", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bcdef                   ' <= c3", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where 'bbbb' <= c3", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where c1 >= c2", new String[][] { {""},{"a"},{"b"},{"b"} } },
	{ "select c3 from varchartab where c3 >= c4", new String[][] { {""},{"a"},{"bcdef"} } },
	{ "select c1 from varchartab where c1 >= '                 '", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= ''", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= 'a '", new String[][] { {"a"},{"b"},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 >= 'b                               '", new String[][] { {"b"},{"b"} } },
	//{ "select c1 from varchartab where c1 >= 'bb'", new String[0][0] },
	{ "select c3 from varchartab where c3 >= ' '", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= ''", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= 'a    '", new String[][] { {"a"},{"bcdef"},{"a"},{"b"} } },
	{ "select c3 from varchartab where c3 >= 'bcdef                   '", new String[][] { {"bcdef"} } },
	{ "select c3 from varchartab where c3 >= 'bbbb'", new String[][] { {"bcdef"} } },
	{ "select c1 from varchartab where '                 ' >= c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where '' >= c1", new String[][] { {""},{""} } },
	{ "select c1 from varchartab where 'a ' >= c1", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c1 from varchartab where 'b                               ' >= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	//{ "select c1 from varchartab where 'bb' >= c1", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where ' ' >= c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where '' >= c3", new String[][] { {""},{""} } },
	{ "select c3 from varchartab where 'a    ' >= c3", new String[][] { {""},{"a"},{""},{"a"} } },
	{ "select c3 from varchartab where 'bcdef                   ' >= c3", new String[][] { {""},{"a"},{"bcdef"},{""},{"a"},{"b"} } },
	{ "select c3 from varchartab where 'bbbb' >= c3", new String[][] { {""},{"a"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where c1 is null", new String[][] { {null} } },
	{ "select c1 from varchartab where c1 is not null", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "select c1 from varchartab where not c1 is null", new String[][] { {""},{"a"},{"b"},{""},{"a"},{"b"} } },
	{ "drop table smallinttab", null },
	{ "drop table biginttab", null },
	{ "drop table chartab", null },
	{ "drop table varchartab", null },
	{ "drop table inttab", null }
    };

    Connection conn = TestUtil.getConnection();
    Statement stmt = conn.createStatement();
    // Go through the array, execute each string[0], check sqlstate [1]
    // This will fail on the first one that succeeds where it shouldn't
    // or throws unknown exception
    JDBC.SQLUnitTestHelper(stmt,Script_ComparisonsUTPartitioning);

  }
}
