DROP TABLE OLTP_PNP_Subscriptions;

--CREATE TABLE OLTP_PNP_Subscriptions(
--id CHAR(100) PRIMARY KEY,
--msisdn VARCHAR(20) NOT NULL
--)
--PARTITION BY COLUMN(msisdn)
----SERVER GROUPS (sg)
--EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
--PERSISTENT 'OLTP_PNP_Subscriptions_DS' ;

CREATE DISKSTORE OLTP_PNP_Subscriptions_DS MAXLOGSIZE 1024 AUTOCOMPACT TRUE ALLOWFORCECOMPACTION  FALSE COMPACTIONTHRESHOLD 80 TIMEINTERVAL 223344 WRITEBUFFERSIZE 19292393 QUEUESIZE 17374('OLTP_PNP_Subscriptions_DS');

CREATE TABLE OLTP_PNP_Subscriptions(
id CHAR(100) PRIMARY KEY,
msisdn VARCHAR(20) NOT NULL,
brand VARCHAR(50) NOT NULL,
walletname VARCHAR(50) NOT NULL
)
PARTITION BY COLUMN(msisdn)
--SERVER GROUPS (sg)
EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
PERSISTENT 'OLTP_PNP_Subscriptions_DS' ;

ALTER TABLE OLTP_PNP_Subscriptions add column expirydate timestamp;

CREATE INDEX IX_PNP_SUBSCRIPTIONS_MSISDN_BRAND_WALLETNAME ON OLTP_PNP_Subscriptions (msisdn, brand, walletname);


