/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef LocatorService_H
#define LocatorService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>

#include "gfxd_types.h"
#include "gfxd_struct_FieldDescriptor.h"
#include "gfxd_struct_Decimal.h"
#include "gfxd_struct_Timestamp.h"
#include "gfxd_struct_FieldValue.h"
#include "gfxd_struct_PDXNode.h"
#include "gfxd_struct_PDXObject.h"
#include "gfxd_struct_PDXSchemaNode.h"
#include "gfxd_struct_PDXSchema.h"
#include "gfxd_struct_JSONField.h"
#include "gfxd_struct_JSONNode.h"
#include "gfxd_struct_JSONObject.h"
#include "gfxd_struct_BlobChunk.h"
#include "gfxd_struct_ClobChunk.h"
#include "gfxd_struct_ServiceMetaData.h"
#include "gfxd_struct_ServiceMetaDataArgs.h"
#include "gfxd_struct_OpenConnectionArgs.h"
#include "gfxd_struct_ConnectionProperties.h"
#include "gfxd_struct_HostAddress.h"
#include "gfxd_struct_GFXDExceptionData.h"
#include "gfxd_struct_StatementAttrs.h"
#include "gfxd_struct_DateTime.h"
#include "gfxd_struct_ColumnValue.h"
#include "gfxd_struct_ColumnDescriptor.h"
#include "gfxd_struct_Row.h"
#include "gfxd_struct_OutputParameter.h"
#include "gfxd_struct_RowSet.h"
#include "gfxd_struct_PrepareResult.h"
#include "gfxd_struct_UpdateResult.h"
#include "gfxd_struct_StatementResult.h"
#include "gfxd_struct_EntityId.h"

#include "gfxd_struct_GFXDException.h"


namespace com { namespace pivotal { namespace gemfirexd { namespace thrift {

class LocatorServiceIf {
 public:
  virtual ~LocatorServiceIf() {}
  virtual void getPreferredServer(HostAddress& _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers) = 0;
  virtual void getAllServersWithPreferredServer(std::vector<HostAddress> & _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers) = 0;
  virtual void closeConnection() = 0;
};

class LocatorServiceIfFactory {
 public:
  typedef LocatorServiceIf Handler;

  virtual ~LocatorServiceIfFactory() {}

  virtual LocatorServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(LocatorServiceIf* /* handler */) = 0;
};

class LocatorServiceIfSingletonFactory : virtual public LocatorServiceIfFactory {
 public:
  LocatorServiceIfSingletonFactory(const boost::shared_ptr<LocatorServiceIf>& iface) : iface_(iface) {}
  virtual ~LocatorServiceIfSingletonFactory() {}

  virtual LocatorServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(LocatorServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<LocatorServiceIf> iface_;
};

class LocatorServiceNull : virtual public LocatorServiceIf {
 public:
  virtual ~LocatorServiceNull() {}
  void getPreferredServer(HostAddress& /* _return */, const std::set<ServerType::type> & /* serverTypes */, const std::set<std::string> & /* serverGroups */, const std::set<HostAddress> & /* failedServers */) {
    return;
  }
  void getAllServersWithPreferredServer(std::vector<HostAddress> & /* _return */, const std::set<ServerType::type> & /* serverTypes */, const std::set<std::string> & /* serverGroups */, const std::set<HostAddress> & /* failedServers */) {
    return;
  }
  void closeConnection() {
    return;
  }
};

typedef struct _LocatorService_getPreferredServer_args__isset {
  _LocatorService_getPreferredServer_args__isset() : serverTypes(false), serverGroups(false), failedServers(false) {}
  bool serverTypes;
  bool serverGroups;
  bool failedServers;
} _LocatorService_getPreferredServer_args__isset;

class LocatorService_getPreferredServer_args {
 public:

  LocatorService_getPreferredServer_args() {
  }

  virtual ~LocatorService_getPreferredServer_args() throw() {}

  std::set<ServerType::type>  serverTypes;
  std::set<std::string>  serverGroups;
  std::set<HostAddress>  failedServers;

  _LocatorService_getPreferredServer_args__isset __isset;

  void __set_serverTypes(const std::set<ServerType::type> & val) {
    serverTypes = val;
  }

  void __set_serverGroups(const std::set<std::string> & val) {
    serverGroups = val;
  }

  void __set_failedServers(const std::set<HostAddress> & val) {
    failedServers = val;
  }

  bool operator == (const LocatorService_getPreferredServer_args & rhs) const
  {
    if (!(serverTypes == rhs.serverTypes))
      return false;
    if (!(serverGroups == rhs.serverGroups))
      return false;
    if (!(failedServers == rhs.failedServers))
      return false;
    return true;
  }
  bool operator != (const LocatorService_getPreferredServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocatorService_getPreferredServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LocatorService_getPreferredServer_pargs {
 public:


  virtual ~LocatorService_getPreferredServer_pargs() throw() {}

  const std::set<ServerType::type> * serverTypes;
  const std::set<std::string> * serverGroups;
  const std::set<HostAddress> * failedServers;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LocatorService_getPreferredServer_result__isset {
  _LocatorService_getPreferredServer_result__isset() : success(false), error(false) {}
  bool success;
  bool error;
} _LocatorService_getPreferredServer_result__isset;

class LocatorService_getPreferredServer_result {
 public:

  LocatorService_getPreferredServer_result() {
  }

  virtual ~LocatorService_getPreferredServer_result() throw() {}

  HostAddress success;
  GFXDException error;

  _LocatorService_getPreferredServer_result__isset __isset;

  void __set_success(const HostAddress& val) {
    success = val;
  }

  void __set_error(const GFXDException& val) {
    error = val;
  }

  bool operator == (const LocatorService_getPreferredServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const LocatorService_getPreferredServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocatorService_getPreferredServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LocatorService_getPreferredServer_presult__isset {
  _LocatorService_getPreferredServer_presult__isset() : success(false), error(false) {}
  bool success;
  bool error;
} _LocatorService_getPreferredServer_presult__isset;

class LocatorService_getPreferredServer_presult {
 public:


  virtual ~LocatorService_getPreferredServer_presult() throw() {}

  HostAddress* success;
  GFXDException error;

  _LocatorService_getPreferredServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _LocatorService_getAllServersWithPreferredServer_args__isset {
  _LocatorService_getAllServersWithPreferredServer_args__isset() : serverTypes(false), serverGroups(false), failedServers(false) {}
  bool serverTypes;
  bool serverGroups;
  bool failedServers;
} _LocatorService_getAllServersWithPreferredServer_args__isset;

class LocatorService_getAllServersWithPreferredServer_args {
 public:

  LocatorService_getAllServersWithPreferredServer_args() {
  }

  virtual ~LocatorService_getAllServersWithPreferredServer_args() throw() {}

  std::set<ServerType::type>  serverTypes;
  std::set<std::string>  serverGroups;
  std::set<HostAddress>  failedServers;

  _LocatorService_getAllServersWithPreferredServer_args__isset __isset;

  void __set_serverTypes(const std::set<ServerType::type> & val) {
    serverTypes = val;
  }

  void __set_serverGroups(const std::set<std::string> & val) {
    serverGroups = val;
  }

  void __set_failedServers(const std::set<HostAddress> & val) {
    failedServers = val;
  }

  bool operator == (const LocatorService_getAllServersWithPreferredServer_args & rhs) const
  {
    if (!(serverTypes == rhs.serverTypes))
      return false;
    if (!(serverGroups == rhs.serverGroups))
      return false;
    if (!(failedServers == rhs.failedServers))
      return false;
    return true;
  }
  bool operator != (const LocatorService_getAllServersWithPreferredServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocatorService_getAllServersWithPreferredServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LocatorService_getAllServersWithPreferredServer_pargs {
 public:


  virtual ~LocatorService_getAllServersWithPreferredServer_pargs() throw() {}

  const std::set<ServerType::type> * serverTypes;
  const std::set<std::string> * serverGroups;
  const std::set<HostAddress> * failedServers;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LocatorService_getAllServersWithPreferredServer_result__isset {
  _LocatorService_getAllServersWithPreferredServer_result__isset() : success(false), error(false) {}
  bool success;
  bool error;
} _LocatorService_getAllServersWithPreferredServer_result__isset;

class LocatorService_getAllServersWithPreferredServer_result {
 public:

  LocatorService_getAllServersWithPreferredServer_result() {
  }

  virtual ~LocatorService_getAllServersWithPreferredServer_result() throw() {}

  std::vector<HostAddress>  success;
  GFXDException error;

  _LocatorService_getAllServersWithPreferredServer_result__isset __isset;

  void __set_success(const std::vector<HostAddress> & val) {
    success = val;
  }

  void __set_error(const GFXDException& val) {
    error = val;
  }

  bool operator == (const LocatorService_getAllServersWithPreferredServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const LocatorService_getAllServersWithPreferredServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocatorService_getAllServersWithPreferredServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _LocatorService_getAllServersWithPreferredServer_presult__isset {
  _LocatorService_getAllServersWithPreferredServer_presult__isset() : success(false), error(false) {}
  bool success;
  bool error;
} _LocatorService_getAllServersWithPreferredServer_presult__isset;

class LocatorService_getAllServersWithPreferredServer_presult {
 public:


  virtual ~LocatorService_getAllServersWithPreferredServer_presult() throw() {}

  std::vector<HostAddress> * success;
  GFXDException error;

  _LocatorService_getAllServersWithPreferredServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class LocatorService_closeConnection_args {
 public:

  LocatorService_closeConnection_args() {
  }

  virtual ~LocatorService_closeConnection_args() throw() {}


  bool operator == (const LocatorService_closeConnection_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const LocatorService_closeConnection_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const LocatorService_closeConnection_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class LocatorService_closeConnection_pargs {
 public:


  virtual ~LocatorService_closeConnection_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class LocatorServiceClient : virtual public LocatorServiceIf {
 public:
  LocatorServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  LocatorServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getPreferredServer(HostAddress& _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers);
  void send_getPreferredServer(const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers);
  void recv_getPreferredServer(HostAddress& _return);
  void getAllServersWithPreferredServer(std::vector<HostAddress> & _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers);
  void send_getAllServersWithPreferredServer(const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers);
  void recv_getAllServersWithPreferredServer(std::vector<HostAddress> & _return);
  void closeConnection();
  void send_closeConnection();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class LocatorServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<LocatorServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (LocatorServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getPreferredServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getAllServersWithPreferredServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_closeConnection(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  LocatorServiceProcessor(boost::shared_ptr<LocatorServiceIf> iface) :
    iface_(iface) {
    processMap_["getPreferredServer"] = &LocatorServiceProcessor::process_getPreferredServer;
    processMap_["getAllServersWithPreferredServer"] = &LocatorServiceProcessor::process_getAllServersWithPreferredServer;
    processMap_["closeConnection"] = &LocatorServiceProcessor::process_closeConnection;
  }

  virtual ~LocatorServiceProcessor() {}
};

class LocatorServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  LocatorServiceProcessorFactory(const ::boost::shared_ptr< LocatorServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< LocatorServiceIfFactory > handlerFactory_;
};

class LocatorServiceMultiface : virtual public LocatorServiceIf {
 public:
  LocatorServiceMultiface(std::vector<boost::shared_ptr<LocatorServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~LocatorServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<LocatorServiceIf> > ifaces_;
  LocatorServiceMultiface() {}
  void add(boost::shared_ptr<LocatorServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getPreferredServer(HostAddress& _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getPreferredServer(_return, serverTypes, serverGroups, failedServers);
    }
    ifaces_[i]->getPreferredServer(_return, serverTypes, serverGroups, failedServers);
    return;
  }

  void getAllServersWithPreferredServer(std::vector<HostAddress> & _return, const std::set<ServerType::type> & serverTypes, const std::set<std::string> & serverGroups, const std::set<HostAddress> & failedServers) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getAllServersWithPreferredServer(_return, serverTypes, serverGroups, failedServers);
    }
    ifaces_[i]->getAllServersWithPreferredServer(_return, serverTypes, serverGroups, failedServers);
    return;
  }

  void closeConnection() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->closeConnection();
    }
    ifaces_[i]->closeConnection();
  }

};

}}}} // namespace

#endif
