hct.HctPrms-regionName = tierTest;
hct.HctPrms-whatToKill = cacheserver;
hct.HctPrms-killInterval = 180000;
hct.HctPrms-toggleKill = false;

hct.HctPrms-getIntervalMs = 10;
hct.HctPrms-hitsPerMiss = 4;
hct.HctPrms-getBatchSize = 100;
hct.HctPrms-restartWaitSec = 2;
hct.HctPrms-dbLoadTimeMs = 10;
hct.HctPrms-objectType = bytearray;
hct.HctPrms-debug = false;

hct.HctPrms-blackboardType = "RMI";
hct.HctPrms-blackboardName = "Lookup";

hct.HctPrms-receiveValuesAsInvalidates = true;
