SET SCHEMA TPCHGFXD;

--CREATE INDEX I_P_SIZE ON PART (P_SIZE);
--CREATE INDEX I_P_TYPE ON PART (P_TYPE);
--CREATE INDEX I_L_ORDERKEY ON LINEITEM (L_ORDERKEY);
--CREATE INDEX I_L_RETURNFLAG ON LINEITEM (L_RETURNFLAG);
CREATE INDEX I_O_ORDERDATE ON ORDERS (O_ORDERDATE);
--CREATE TABLE TEMP_Q1 AS SELECT * FROM LINEITEM WITH NO DATA;
--insert into TEMP_Q1 select * from LINEITEM where l_shipdate <= cast({fn timestampadd(SQL_TSI_DAY, -90, timestamp('1998-12-01 23:59:59'))} as DATE);
