CREATE GATEWAYSENDER GW_SENDER_BASME_BASETL
(
  REMOTEDSID 14
  ENABLEPERSISTENCE true
)SERVER GROUPS (channeldatagrp);

ALTER TABLE SECL_CHN_DATA_STATUS_HIST SET GATEWAYSENDER (GW_SENDER_BASME_BASETL);

CREATE GATEWAYRECEIVER RECEIVER_BASETL_TO_BASME(startport 1730 endport 1841) server groups (channeldatagrp);
