CREATE GATEWAYSENDER ETLBAS_TO_ETLRDC_PRIMARY
(
  REMOTEDSID 12
  ENABLEPERSISTENCE true
)SERVER GROUPS (channeldatagrp);


CREATE GATEWAYSENDER ETLBAS_TO_MEBAS_PRIMARY
(
  REMOTEDSID 13
  ENABLEPERSISTENCE true
)SERVER GROUPS (channeldatagrp);

ALTER TABLE SECT_CHANNEL_DATA SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECT_CHANNEL_RAW_DATA SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_BACKOFFICE_ONBOARDED SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_BO_MESSAGE_TAG_MAPPING SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_BS_DETERMINATION_GENERAL SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_BS_DETERMINATION_PAIN001 SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_CATEGORIZATION SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_DATA_DESTINATION SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FILE_CATEGORY SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FILE_TYPE_ONBOARDED SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FILE_WATCHER SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FILE_WATCHER_CONFIGS SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FIRCOSOFT_HEADER_MAPPING SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_FIRCOSOFT_XML_TAGS SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_HIT_STATUS_MAP SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_KEY_LIST SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_LOCATION SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_MATCHING_KEY_INFO SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_MQ SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_MQ_BO_MAP SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_MQ_MGR SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_OFAC_MQ_ROUTING SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_PARSER_CONFIGURATION SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_PREMATCH_TRANSFORMATION SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_PROCESS_CONFIG SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_STATUS_DECISION_DATA SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_TXN_MANAGEMENT SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_XML_TAG_MAPPINGS SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_CHANNEL_ONBOARDED SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_TEMPLATE SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ACTION_HANDLER SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ERROR_CODES SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_USER SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_GROUP SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_COUNTRY SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ERROR_TEMPLATE SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ERROR_ACTION_HANDLER SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ERROR_MESSAGE SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_USER_GROUP SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECM_ERROR_MAIL_CONFIG SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);
ALTER TABLE SECL_CHN_ORPHAN_DATA_STATUS SET GATEWAYSENDER (ETLBAS_TO_ETLRDC_PRIMARY,ETLBAS_TO_MEBAS_PRIMARY);

CREATE GATEWAYRECEIVER RECEIVER_RDCETL_TO_BASETL(startport 1630 endport 1641) server groups (channeldatagrp);
CREATE GATEWAYRECEIVER RECEIVER_BASME_TO_BASETL(startport 1730 endport 1741) server groups (channeldatagrp);
