CREATE GATEWAYSENDER GW_SENDER_RDCME_RDCETL
(
  REMOTEDSID 12
  ENABLEPERSISTENCE true
)SERVER GROUPS (channeldatagrp);

ALTER TABLE SECL_CHN_DATA_STATUS_HIST SET GATEWAYSENDER (GW_SENDER_RDCME_RDCETL);

CREATE GATEWAYRECEIVER RECEIVER_RDCETL_TO_RDCME(startport 1730 endport 1841) server groups (channeldatagrp);
