CREATE TABLE T.TABLE_DATA
(
ID VARCHAR (36) NOT NULL ,
F1 VARCHAR (100) ,
F2 VARCHAR (100) ,
F3 VARCHAR (100) ,
F4 VARCHAR (100) ,
F5 VARCHAR (100) ,
F6 TIMESTAMP ,
F7 DECIMAL (16,2) ,
F8 VARCHAR (20) ,
F9 VARCHAR (100) ,
F10 VARCHAR (100) ,
F11 VARCHAR (100) ,
F12 VARCHAR (100) WITH DEFAULT 'UNKNOWN' ,
F13 VARCHAR (100) ,
F14 VARCHAR (100) ,
F15 VARCHAR (100) ,
F16 VARCHAR (100) ,
F17 VARCHAR (100) ,
F18 VARCHAR (256) ,
F19 VARCHAR (100) ,
F20 TIMESTAMP ,
F21 TIMESTAMP ,
F22 CLOB NOT NULL ,
F23 SMALLINT NOT NULL ,
F24 SMALLINT WITH DEFAULT 1 ,
F25 TIMESTAMP ,
F26 INTEGER ,
F27 CHAR (1) WITH DEFAULT 'N' ,
F28 CHAR (1) WITH DEFAULT 'N' ,
F29 VARCHAR (36) NOT NULL ,
F30 INTEGER NOT NULL ,
F31 VARCHAR (100) WITH DEFAULT 'UNKNOWN' ,
F32 VARCHAR (30) WITH DEFAULT 'UNKNOWN' ,
F34 SMALLINT ,
F35 TIMESTAMP ,
F36 TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP ,
CONSTRAINT DATA_PK PRIMARY KEY(ID)
) PARTITION BY PRIMARY KEY REDUNDANCY 1 EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW PERSISTENT ASYNCHRONOUS OFFHEAP;

CREATE INDEX IDX_F1 on T.TABLE_DATA(F1) -- gemfirexd-properties caseSensitive=false
;
CREATE INDEX IDX_F2_F3_F4 on T.TABLE_DATA(F2, F3, F4) -- gemfirexd-properties caseSensitive=false
;
CREATE INDEX IDX_F5 on T.TABLE_DATA(F5) -- gemfirexd-properties caseSensitive=false
;
CREATE INDEX IDX_F9 on T.TABLE_DATA(F9)
;
CREATE INDEX IDX_F8 on T.TABLE_DATA(F8) -- gemfirexd-properties caseSensitive=false
;
CREATE INDEX IDX_F8_F9_F10 on T.TABLE_DATA(F8, F9, F10) -- gemfirexd-properties caseSensitive=false
;
