SET CURRENT SCHEMA=SEC_OWNER;

insert into SECM_OFAC_MQ_ROUTING values('AAA-001', 'IPAY', 'BO1LE', 'CIB', 'MSG', 'DOLLAR', 'OFAC1.REQ.OUT.QUEUE', 'BO1.ACK.OUT.QUEUE', 'BO1.DECISION.OUT.QUEUE', 'BO1.STOP.OUT.QUEUE', CURRENT_TIMESTAMP,{fn TIMESTAMPADD(SQL_TSI_DAY, 10000, CURRENT_TIMESTAMP)},'SEC_SYS',CURRENT TIMESTAMP);


insert into SECM_OFAC_MQ_ROUTING values('AAA-002', 'LG_ORPHAN', 'BO2LE', 'CIB', 'MSG', 'DOLLAR', 'OFAC.TATICAL.REQ.OUT.QUEUE', 'ackMqId', 'decisionMqId', 'stopMqId', CURRENT_TIMESTAMP,{fn TIMESTAMPADD(SQL_TSI_DAY, 10000, CURRENT_TIMESTAMP)},'SEC_SYS',CURRENT TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-009','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO2.ACK.OUT.QUEUE','BO2.DECISION.OUT.QUEUE','BO2.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-010','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO3.ACK.OUT.QUEUE','BO3.DECISION.OUT.QUEUE','BO3.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-011','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO4.ACK.OUT.QUEUE','BO4.DECISION.OUT.QUEUE','BO4.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-012','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO5.ACK.OUT.QUEUE','BO5.DECISION.OUT.QUEUE','BO5.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-013','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO6.ACK.OUT.QUEUE','BO6.DECISION.OUT.QUEUE','BO6.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-014','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO7.ACK.OUT.QUEUE','BO7.DECISION.OUT.QUEUE','BO7.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-015','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO8.ACK.OUT.QUEUE','BO8.DECISION.OUT.QUEUE','BO8.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-016','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO9.ACK.OUT.QUEUE','BO9.DECISION.OUT.QUEUE','BO9.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID,LOB,LEGAL_ENTITY,BUSINESS_TYPE,MSG_TYPE,CURRENCY,FIRCOSOFT_MQ_ID,ACK_MQ_ID,DECISION_MQ_ID,STOP_MQ_ID,ONBOARD_DATE,END_DATE,LAST_UPADTE_BY,LAST_UPDATE_DATE) VALUES ('AAA-017','IPAY','BO1LE','CIB','MSG','DOLLAR','OFAC1.REQ.OUT.QUEUE','BO10.ACK.OUT.QUEUE','BO10.DECISION.OUT.QUEUE','BO10.STOP.OUT.QUEUE',{ts '2013-02-26 15:30:19'},{ts '2040-07-14 15:30:19'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_OFAC_MQ_ROUTING (INPUT_MQ_ID, LOB, LEGAL_ENTITY, BUSINESS_TYPE, MSG_TYPE,CURRENCY, FIRCOSOFT_MQ_ID, ACK_MQ_ID, DECISION_MQ_ID, STOP_MQ_ID,ONBOARD_DATE, END_DATE, LAST_UPADTE_BY, LAST_UPDATE_DATE)VALUES ('AAA-045', 'IPAY', 'BO1LE', 'CIB', 'MSG','DOLLAR', 'OFAC1.REQ.OUT.QUEUE', 'BO1.ACK.OUT.QUEUE.HV', 'BO1.DECISION.OUT.QUEUE.HV', 'BO1.STOP.OUT.QUEUE.HV','2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);
