SET CURRENT SCHEMA=SEC_OWNER;

INSERT
INTO SECM_MQ_MGR
  (
    MGR_NAME, PROCESS_ID, CONNECTOR_CONFIG, MQ_MGR, MQ_FACTORY_NAME,
    HOSTNAME, CHANNEL, MQ_PORT, TRANSPORT_TYPE, SSL_CIPHER,
    ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE
  )
  VALUES
  ('TEST_MGR','PROC_1','<vm:connector name="vmConnector" />','BO1.MqFac','TEST_FAC1', 
   'WMQ_HOSTNAME','TEST_CHNL','1234','1','TEST', 
   CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS',CURRENT_TIMESTAMP);

