SET CURRENT SCHEMA=SEC_OWNER;

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-001','TEST_MGR','BO1.REQ.IN.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-002','TEST_MGR','OFAC1.REQ.OUT.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-003','TEST_MGR','OFAC1.ACK.IN.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-004','TEST_MGR','BO1.ACK.OUT.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-005','TEST_MGR','OFAC1.DECISION.IN.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
   	MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-006','TEST_MGR','BO1.DECISION.OUT.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
   MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-007','TEST_MGR','OFAC1.STOP.IN.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

INSERT
INTO SECM_MQ
  (
    MQ_ID,
    MGR_NAME,
    MQ_NAME,
    MQ_STATUS,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE,
    EXCHANGE_PATTERN
  )
  VALUES
  ('AAA-008','TEST_MGR','BO1.STOP.OUT.QUEUE','ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'SEC_SYS', CURRENT_TIMESTAMP, 'ABC');

  
INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-009','TEST_MGR','BO2.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-010','TEST_MGR','BO3.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-011','TEST_MGR','BO4.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-012','TEST_MGR','BO5.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-013','TEST_MGR','BO6.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-014','TEST_MGR','BO7.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-015','TEST_MGR','BO8.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-016','TEST_MGR','BO9.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-017','TEST_MGR','BO10.REQ.IN.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-018','TEST_MGR','BO2.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-019','TEST_MGR','BO3.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-020','TEST_MGR','BO4.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-021','TEST_MGR','BO5.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-022','TEST_MGR','BO6.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-023','TEST_MGR','BO7.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-024','TEST_MGR','BO8.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-025','TEST_MGR','BO9.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-026','TEST_MGR','BO10.ACK.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-027','TEST_MGR','BO2.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-028','TEST_MGR','BO3.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-029','TEST_MGR','BO4.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-030','TEST_MGR','BO5.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-031','TEST_MGR','BO6.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-032','TEST_MGR','BO7.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-033','TEST_MGR','BO8.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-034','TEST_MGR','BO9.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-035','TEST_MGR','BO10.STOP.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-036','TEST_MGR','BO2.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-037','TEST_MGR','BO3.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-038','TEST_MGR','BO4.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-039','TEST_MGR','BO5.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-040','TEST_MGR','BO6.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-041','TEST_MGR','BO7.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-042','TEST_MGR','BO8.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-043','TEST_MGR','BO9.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID,MGR_NAME,MQ_NAME,TXN_ACTION,TRANSFORMER_REFS,EXCHANGE_PATTERN,MQ_STATUS,ONBOARD_DATE,END_DATE,LAST_UPDATE_BY,LAST_UPDATE_DATE) VALUES ('AAA-044','TEST_MGR','BO10.DECISION.OUT.QUEUE',null,null,'ABC','ACTIVE',{ts '2013-01-28 06:51:31'},{ts '2020-01-28 06:51:31'},'SEC_SYS',CURRENT_TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-045', 'TEST_MGR', 'BO1.REQ.IN.QUEUE.HV', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-046', 'TEST_MGR', 'BO1.RES.IN.QUEUE.HV', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-047', 'TEST_MGR', 'BO1.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-048', 'TEST_MGR', 'BO2.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-049', 'TEST_MGR', 'BO3.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-050', 'TEST_MGR', 'BO4.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-051', 'TEST_MGR', 'BO5.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-052', 'TEST_MGR', 'BO6.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-053', 'TEST_MGR', 'BO7.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-054', 'TEST_MGR', 'BO8.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-055', 'TEST_MGR', 'BO9.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);

INSERT INTO SECM_MQ (MQ_ID, MGR_NAME, MQ_NAME,TXN_ACTION,TRANSFORMER_REFS, EXCHANGE_PATTERN, MQ_STATUS, ONBOARD_DATE, END_DATE, LAST_UPDATE_BY, LAST_UPDATE_DATE) VALUES ('AAA-056', 'TEST_MGR', 'BO10.RES.IN.QUEUE', null,null,'ABC', 'ACTIVE', '2013-03-08 00:00:00.0', '2020-03-08 00:00:00.0', 'SEC_SYS', CURRENT TIMESTAMP);
