SET CURRENT SCHEMA SEC_OWNER;

run 'CORE_ENGINE_SECM_LOCATION_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_BACKOFFICE_ONBOARDED_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_CHANNEL_ONBOARDED_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_KEY_LIST_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_PREMATCH_TRANSFORMATION_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_MATCHING_KEY_INFO_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_TXN_MANAGEMENT_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_CATEGORIZATION_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_DATA_DESTINATION_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_PARSER_CONFIGURATION _DAT_Sample.sql';
run 'CORE_ENGINE_SECM_BO_MESSAGE_TAG_MAPPING_DAT_Sample.sql';

--added data for these tables (all these scripts need to be added to the 0.89 scripts list)
run 'CORE_ENGINE_SEC_CHANNEL_DATA_SAMPLE.sql';
run 'CORE_ENGINE_SECM_PROCESS_CONFIG_Sample.sql';
run 'CORE_ENGINE_SECM_MQ_MGR_Sample.sql';
run 'CORE_ENGINE_SECM_MQ_Sample.sql';
run 'CORE_ENGINE_SECM_MQ_BO_MAP_Sample.sql';
run 'CORE_ENGINE_SECM_OFAC_MQ_ROUTING_Sample.sql';
run 'CORE_ENGINE_QRTZ_LOCKS_DATA.sql';

run 'CORE_ENGINE_SECM_COUNTRY_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_ERROR_CODES_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_ERROR_MAIL_CONFIG_DAT_Sample.sql';
run 'CORE_ENGINE_SECM_ERROR_MESSAGE_DAT_Sample.sql';

