SET CURRENT SCHEMA=SEC_OWNER;

INSERT INTO qrtz_locks VALUES ('TRIGGER_ACCESS');
INSERT INTO qrtz_locks VALUES ('JOB_ACCESS');
INSERT INTO qrtz_locks VALUES ('CALENDAR_ACCESS');
INSERT INTO qrtz_locks VALUES ('STATE_ACCESS');
INSERT INTO qrtz_locks VALUES ('MISFIRE_ACCESS');

