SET CURRENT SCHEMA=SEC_OWNER;

INSERT
INTO SECM_PARSER_CONFIGURATION
  (
    PARSER_ID,
    BACKOFFICE_CODE,
    PARSER_NAME,
    MESSAGE_TYPE,
    ONBOARD_DATE,
    END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
  )
  VALUES
  (
    1,
    'IPAY',
    'IPAYPARSER',
    NULL,
    CURRENT_TIMESTAMP,
    TIMESTAMP('2020-03-19', '00:00:00'),
    'SEC_SYS',
    CURRENT_TIMESTAMP
  ) ;
