SET CURRENT SCHEMA=SEC_OWNER;

INSERT
INTO SECM_BACKOFFICE_ONBOARDED
  (
    BACKOFFICE_CODE,
    BACKOFFICE_NAME,
    DESCRIPTION,
    BACKOFFICE_LOC,
    ONBOARD_DATE,
	END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
  )
  VALUES
  ('IPAY','iPay','The iPay application','EMEA', current timestamp,TIMESTAMP('2020-03-19', '00:00:00'),'SEC_SYS', CURRENT_TIMESTAMP);

 INSERT
INTO SECM_BACKOFFICE_ONBOARDED
  (
    BACKOFFICE_CODE,
    BACKOFFICE_NAME,
    DESCRIPTION,
    BACKOFFICE_LOC,
    ONBOARD_DATE,
	END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
  )
  VALUES
  ('UNKNOWN','UNKNOWN','Cannot deternimate the back office name','UNKNOWN',current timestamp,TIMESTAMP('2020-03-19', '00:00:00'),'SEC_SYS',CURRENT_TIMESTAMP);
  
 INSERT
INTO SECM_BACKOFFICE_ONBOARDED
  (
    BACKOFFICE_CODE,
    BACKOFFICE_NAME,
    DESCRIPTION,
    BACKOFFICE_LOC,
    ONBOARD_DATE,
	END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
  )
  VALUES
  ('PAY METHOD DEFAULT','PAY METHOD DEFAULT','Determined as PMD as backoffice code by etl','UNKNOWN',current timestamp,TIMESTAMP('2020-03-19', '00:00:00'),'SEC_SYS',CURRENT_TIMESTAMP);
  
  INSERT
INTO SECM_BACKOFFICE_ONBOARDED
  (
    BACKOFFICE_CODE,
    BACKOFFICE_NAME,
    DESCRIPTION,
    BACKOFFICE_LOC,
    ONBOARD_DATE,
	END_DATE,
    LAST_UPDATE_BY,
    LAST_UPDATE_DATE
  )
  VALUES
  ('Unknown BackOffice System','Unknown BackOffice System','Cannot deternimate the back office name by etl','UNKNOWN',current timestamp,TIMESTAMP('2020-03-19', '00:00:00'),'SEC_SYS',CURRENT_TIMESTAMP);
