/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package com.pivotal.gemfirexd.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class JSONNode implements org.apache.thrift.TBase<JSONNode, JSONNode._Fields>, java.io.Serializable, Comparable<JSONNode> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JSONNode");

  private static final org.apache.thrift.protocol.TField PAIRS_FIELD_DESC = new org.apache.thrift.protocol.TField("pairs", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField SINGLE_FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("singleField", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField REF_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("refId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new JSONNodeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new JSONNodeTupleSchemeFactory());
  }

  public Map<String,JSONField> pairs; // optional
  public JSONField singleField; // optional
  public int refId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PAIRS((short)1, "pairs"),
    SINGLE_FIELD((short)2, "singleField"),
    REF_ID((short)3, "refId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PAIRS
          return PAIRS;
        case 2: // SINGLE_FIELD
          return SINGLE_FIELD;
        case 3: // REF_ID
          return REF_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REFID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.PAIRS,_Fields.SINGLE_FIELD};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PAIRS, new org.apache.thrift.meta_data.FieldMetaData("pairs", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, JSONField.class))));
    tmpMap.put(_Fields.SINGLE_FIELD, new org.apache.thrift.meta_data.FieldMetaData("singleField", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, JSONField.class)));
    tmpMap.put(_Fields.REF_ID, new org.apache.thrift.meta_data.FieldMetaData("refId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JSONNode.class, metaDataMap);
  }

  public JSONNode() {
  }

  public JSONNode(
    int refId)
  {
    this();
    this.refId = refId;
    setRefIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JSONNode(JSONNode other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetPairs()) {
      Map<String,JSONField> __this__pairs = new HashMap<String,JSONField>(other.pairs.size());
      for (Map.Entry<String, JSONField> other_element : other.pairs.entrySet()) {

        String other_element_key = other_element.getKey();
        JSONField other_element_value = other_element.getValue();

        String __this__pairs_copy_key = other_element_key;

        JSONField __this__pairs_copy_value = new JSONField(other_element_value);

        __this__pairs.put(__this__pairs_copy_key, __this__pairs_copy_value);
      }
      this.pairs = __this__pairs;
    }
    if (other.isSetSingleField()) {
      this.singleField = new JSONField(other.singleField);
    }
    this.refId = other.refId;
  }

  public JSONNode deepCopy() {
    return new JSONNode(this);
  }

  @Override
  public void clear() {
    this.pairs = null;
    this.singleField = null;
    setRefIdIsSet(false);
    this.refId = 0;
  }

  public int getPairsSize() {
    return (this.pairs == null) ? 0 : this.pairs.size();
  }

  public void putToPairs(String key, JSONField val) {
    if (this.pairs == null) {
      this.pairs = new HashMap<String,JSONField>();
    }
    this.pairs.put(key, val);
  }

  public Map<String,JSONField> getPairs() {
    return this.pairs;
  }

  public JSONNode setPairs(Map<String,JSONField> pairs) {
    this.pairs = pairs;
    return this;
  }

  public void unsetPairs() {
    this.pairs = null;
  }

  /** Returns true if field pairs is set (has been assigned a value) and false otherwise */
  public boolean isSetPairs() {
    return this.pairs != null;
  }

  public void setPairsIsSet(boolean value) {
    if (!value) {
      this.pairs = null;
    }
  }

  public JSONField getSingleField() {
    return this.singleField;
  }

  public JSONNode setSingleField(JSONField singleField) {
    this.singleField = singleField;
    return this;
  }

  public void unsetSingleField() {
    this.singleField = null;
  }

  /** Returns true if field singleField is set (has been assigned a value) and false otherwise */
  public boolean isSetSingleField() {
    return this.singleField != null;
  }

  public void setSingleFieldIsSet(boolean value) {
    if (!value) {
      this.singleField = null;
    }
  }

  public int getRefId() {
    return this.refId;
  }

  public JSONNode setRefId(int refId) {
    this.refId = refId;
    setRefIdIsSet(true);
    return this;
  }

  public void unsetRefId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REFID_ISSET_ID);
  }

  /** Returns true if field refId is set (has been assigned a value) and false otherwise */
  public boolean isSetRefId() {
    return EncodingUtils.testBit(__isset_bitfield, __REFID_ISSET_ID);
  }

  public void setRefIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REFID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PAIRS:
      if (value == null) {
        unsetPairs();
      } else {
        setPairs((Map<String,JSONField>)value);
      }
      break;

    case SINGLE_FIELD:
      if (value == null) {
        unsetSingleField();
      } else {
        setSingleField((JSONField)value);
      }
      break;

    case REF_ID:
      if (value == null) {
        unsetRefId();
      } else {
        setRefId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PAIRS:
      return getPairs();

    case SINGLE_FIELD:
      return getSingleField();

    case REF_ID:
      return Integer.valueOf(getRefId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PAIRS:
      return isSetPairs();
    case SINGLE_FIELD:
      return isSetSingleField();
    case REF_ID:
      return isSetRefId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof JSONNode)
      return this.equals((JSONNode)that);
    return false;
  }

  public boolean equals(JSONNode that) {
    if (that == null)
      return false;

    boolean this_present_pairs = true && this.isSetPairs();
    boolean that_present_pairs = true && that.isSetPairs();
    if (this_present_pairs || that_present_pairs) {
      if (!(this_present_pairs && that_present_pairs))
        return false;
      if (!this.pairs.equals(that.pairs))
        return false;
    }

    boolean this_present_singleField = true && this.isSetSingleField();
    boolean that_present_singleField = true && that.isSetSingleField();
    if (this_present_singleField || that_present_singleField) {
      if (!(this_present_singleField && that_present_singleField))
        return false;
      if (!this.singleField.equals(that.singleField))
        return false;
    }

    boolean this_present_refId = true;
    boolean that_present_refId = true;
    if (this_present_refId || that_present_refId) {
      if (!(this_present_refId && that_present_refId))
        return false;
      if (this.refId != that.refId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(JSONNode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPairs()).compareTo(other.isSetPairs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPairs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pairs, other.pairs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSingleField()).compareTo(other.isSetSingleField());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSingleField()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.singleField, other.singleField);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRefId()).compareTo(other.isSetRefId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRefId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.refId, other.refId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("JSONNode(");
    boolean first = true;

    if (isSetPairs()) {
      sb.append("pairs:");
      if (this.pairs == null) {
        sb.append("null");
      } else {
        sb.append(this.pairs);
      }
      first = false;
    }
    if (isSetSingleField()) {
      if (!first) sb.append(", ");
      sb.append("singleField:");
      if (this.singleField == null) {
        sb.append("null");
      } else {
        sb.append(this.singleField);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("refId:");
    sb.append(this.refId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'refId' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
    if (singleField != null) {
      singleField.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JSONNodeStandardSchemeFactory implements SchemeFactory {
    public JSONNodeStandardScheme getScheme() {
      return new JSONNodeStandardScheme();
    }
  }

  private static class JSONNodeStandardScheme extends StandardScheme<JSONNode> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JSONNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PAIRS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map120 = iprot.readMapBegin();
                struct.pairs = new HashMap<String,JSONField>(2*_map120.size);
                for (int _i121 = 0; _i121 < _map120.size; ++_i121)
                {
                  String _key122;
                  JSONField _val123;
                  _key122 = iprot.readString();
                  _val123 = new JSONField();
                  _val123.read(iprot);
                  struct.pairs.put(_key122, _val123);
                }
                iprot.readMapEnd();
              }
              struct.setPairsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SINGLE_FIELD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.singleField = new JSONField();
              struct.singleField.read(iprot);
              struct.setSingleFieldIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REF_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.refId = iprot.readI32();
              struct.setRefIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetRefId()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'refId' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JSONNode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.pairs != null) {
        if (struct.isSetPairs()) {
          oprot.writeFieldBegin(PAIRS_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.pairs.size()));
            for (Map.Entry<String, JSONField> _iter124 : struct.pairs.entrySet())
            {
              oprot.writeString(_iter124.getKey());
              _iter124.getValue().write(oprot);
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.singleField != null) {
        if (struct.isSetSingleField()) {
          oprot.writeFieldBegin(SINGLE_FIELD_FIELD_DESC);
          struct.singleField.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(REF_ID_FIELD_DESC);
      oprot.writeI32(struct.refId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JSONNodeTupleSchemeFactory implements SchemeFactory {
    public JSONNodeTupleScheme getScheme() {
      return new JSONNodeTupleScheme();
    }
  }

  private static class JSONNodeTupleScheme extends TupleScheme<JSONNode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JSONNode struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.refId);
      BitSet optionals = new BitSet();
      if (struct.isSetPairs()) {
        optionals.set(0);
      }
      if (struct.isSetSingleField()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPairs()) {
        {
          oprot.writeI32(struct.pairs.size());
          for (Map.Entry<String, JSONField> _iter125 : struct.pairs.entrySet())
          {
            oprot.writeString(_iter125.getKey());
            _iter125.getValue().write(oprot);
          }
        }
      }
      if (struct.isSetSingleField()) {
        struct.singleField.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JSONNode struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.refId = iprot.readI32();
      struct.setRefIdIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map126 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.pairs = new HashMap<String,JSONField>(2*_map126.size);
          for (int _i127 = 0; _i127 < _map126.size; ++_i127)
          {
            String _key128;
            JSONField _val129;
            _key128 = iprot.readString();
            _val129 = new JSONField();
            _val129.read(iprot);
            struct.pairs.put(_key128, _val129);
          }
        }
        struct.setPairsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.singleField = new JSONField();
        struct.singleField.read(iprot);
        struct.setSingleFieldIsSet(true);
      }
    }
  }

}

