DROP INDEX IF EXISTS RTRADM.REPL_CUSTOMER_CUST_NUM;
DROP INDEX IF EXISTS RTRADM.REPL_CUSTOMER_CUST_ID;
DROP INDEX IF EXISTS RTRADM.REPL_CUSTOMER_ROW_WID;

DROP INDEX IF EXISTS RTRADM.REPL_PRODUCT_CUR_ROW_WID;
DROP INDEX IF EXISTS RTRADM.REPL_PRODUCT_CUR_ITEM_11I_ID;
DROP INDEX IF EXISTS RTRADM.REPL_PRODUCT_CUR_ITEM_NUM;

DROP INDEX IF EXISTS RTRADM.REPL_RESOURCE_ROLE_REF_RSRC_ID;
DROP INDEX IF EXISTS RTRADM.RESOURCE_ROLE_REF_W_CRNT_FLG;

DROP INDEX IF EXISTS RTRADM.REPL_CUST_SITE_LOCATION_ROW_WID;
DROP INDEX IF EXISTS RTRADM.REPL_CUST_SITE_LOCATION_CUST_ID;
DROP INDEX IF EXISTS RTRADM.REPL_CUST_SITE_PARTNER_EXT_ROW_WID;
DROP INDEX IF EXISTS RTRADM.REPL_CUST_SITE_PARTNER_EXT_CUST_ID;

DROP INDEX IF EXISTS RTRADM.REPL_TERRITORY_ASSIGNMENT_USR_NM;
DROP INDEX IF EXISTS RTRADM.REPL_TERRITORY_ASSIGNMENT_ROW_WID;
DROP INDEX IF EXISTS RTRADM.REPL_TERRITORY_ASSIGNMENT_DSTRCT_TERR_ID;
DROP INDEX IF EXISTS RTRADM.TERRITORY_ASSIGNMENT_DST_GP_ID;
DROP INDEX IF EXISTS RTRADM.TERRITORY_ASSIGNMENT_SEQ_NUM;

DROP INDEX IF EXISTS RTRADM.SALES_GEOGRAPHY_REF_DISTRICT_ID;

DROP INDEX IF EXISTS RTRADM.REPL_CUSTOMER_DENORM_HASH_ID;

DROP INDEX IF EXISTS RTRADM.REPL_SALES_CREDITS_DISTRICT_ID;
DROP INDEX IF EXISTS RTRADM.REPL_SALES_CREDITS_SALESREP_ID;
DROP INDEX IF EXISTS RTRADM.REPL_SALES_CREDITS_SO_NUMBER;
DROP INDEX IF EXISTS RTRADM.SALES_CREDITS_THTR;
DROP INDEX IF EXISTS RTRADM.SALES_CREDITS_EFCT_END_DATE;
DROP INDEX IF EXISTS RTRADM.SALES_GEOGRAPHY_REF_Q_FLG;
DROP INDEX IF EXISTS RTRADM.SALES_GEOGRAPHY_REF_CRNT_FLG;

DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_HASH_ID;
DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_ORD_NUM;
DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_RPTG_DT_WID;
DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_PROD_CUR_WID;
DROP INDEX IF EXISTS RTRADM.RTR_REPORT_DATA_BUCKET; 
DROP INDEX IF EXISTS RTRADM.RTR_REPORT_DATA_RCD_STUS;
DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_OPP_NO;
DROP INDEX IF EXISTS RTRADM.REPL_RTR_REPORT_DATA_QTE_NUM;

--INDEX CREATION FOR REPLICATED TABLES IN GFXD GDW TABLES 

-- CUSTOMER
CREATE INDEX REPL_CUSTOMER_CUST_NUM ON RTRADM.CUSTOMER (CUST_NUM);
CREATE INDEX REPL_CUSTOMER_CUST_ID ON RTRADM.CUSTOMER (CUST_ID);
CREATE INDEX REPL_CUSTOMER_ROW_WID ON RTRADM.CUSTOMER (ROW_WID);
--  PRODUCT_CUR
CREATE INDEX REPL_PRODUCT_CUR_ROW_WID ON RTRADM.PRODUCT_CUR (ROW_WID);
CREATE INDEX REPL_PRODUCT_CUR_ITEM_11I_ID ON RTRADM.PRODUCT_CUR (ITEM_11I_ID);
CREATE INDEX REPL_PRODUCT_CUR_ITEM_NUM ON RTRADM.PRODUCT_CUR (ITEM_NUM);
-- RESOURCE_ROLE_REF
CREATE INDEX REPL_RESOURCE_ROLE_REF_RSRC_ID ON RTRADM.RESOURCE_ROLE_REF (RSRC_ID);
CREATE INDEX RTRADM.RESOURCE_ROLE_REF_W_CRNT_FLG on RTRADM.RESOURCE_ROLE_REF(W_CURRENT_FLG);

-- CUST_SITE_LOCATION
CREATE INDEX REPL_CUST_SITE_LOCATION_ROW_WID ON RTRADM.CUST_SITE_LOCATION (ROW_WID);
CREATE INDEX REPL_CUST_SITE_LOCATION_CUST_ID ON RTRADM.CUST_SITE_LOCATION (CUST_ID);
-- CUST_SITE_PARTNER_EXT
CREATE INDEX REPL_CUST_SITE_PARTNER_EXT_ROW_WID ON RTRADM.CUST_SITE_PARTNER_EXT (ROW_WID);
CREATE INDEX REPL_CUST_SITE_PARTNER_EXT_CUST_ID ON RTRADM.CUST_SITE_PARTNER_EXT (CUST_ID);
-- TERRITORY_ASSIGNMENT
CREATE INDEX REPL_TERRITORY_ASSIGNMENT_USR_NM ON RTRADM.TERRITORY_ASSIGNMENT (USR_NM);
CREATE INDEX REPL_TERRITORY_ASSIGNMENT_ROW_WID ON RTRADM.TERRITORY_ASSIGNMENT (ROW_WID);
CREATE INDEX REPL_TERRITORY_ASSIGNMENT_DSTRCT_TERR_ID ON RTRADM.TERRITORY_ASSIGNMENT (DSTRCT_TERR_ID);
CREATE INDEX RTRADM.TERRITORY_ASSIGNMENT_DST_GP_ID on  RTRADM.TERRITORY_ASSIGNMENT(DSTRCT_GP_ID);
CREATE INDEX RTRADM.TERRITORY_ASSIGNMENT_SEQ_NUM on RTRADM.TERRITORY_ASSIGNMENT(SEQ_NUM);

CREATE INDEX SALES_GEOGRAPHY_REF_DISTRICT_ID ON RTRADM.SALES_GEOGRAPHY_REF(DSTRCT_ID);
CREATE INDEX RTRADM.SALES_GEOGRAPHY_REF_Q_FLG on RTRADM.SALES_GEOGRAPHY_REF(QUOTA_FLG);
CREATE INDEX RTRADM.SALES_GEOGRAPHY_REF_CRNT_FLG on  RTRADM.SALES_GEOGRAPHY_REF(W_CURRENT_FLG);
-- CUSTOMER_DENORM
CREATE INDEX REPL_CUSTOMER_DENORM_HASH_ID ON RTRADM.CUSTOMER_DENORM (CUSTOMER_HASH_ID);

CREATE INDEX REPL_RTR_REPORT_DATA_HASH_ID ON RTRADM.RTR_REPORT_DATA (CUSTOMER_HASH_ID);
CREATE INDEX REPL_RTR_REPORT_DATA_ORD_NUM ON RTRADM.RTR_REPORT_DATA (ORD_NUM);
CREATE INDEX REPL_RTR_REPORT_DATA_RPTG_DT_WID ON RTRADM.RTR_REPORT_DATA (RPTG_DT_WID);
CREATE INDEX REPL_RTR_REPORT_DATA_PROD_CUR_WID ON RTRADM.RTR_REPORT_DATA (PROD_CUR_WID);
CREATE INDEX RTRADM.RTR_REPORT_DATA_BUCKET on RTRADM.RTR_REPORT_DATA(BUCKET); 
CREATE INDEX RTRADM.RTR_REPORT_DATA_RCD_STUS on RTRADM.RTR_REPORT_DATA(RECORD_STATUS);
CREATE INDEX REPL_RTR_REPORT_DATA_OPP_NO ON RTRADM.RTR_REPORT_DATA (OPP_NO);
CREATE INDEX REPL_RTR_REPORT_DATA_QTE_NUM ON RTRADM.RTR_REPORT_DATA (QTE_NUM);

CREATE INDEX REPL_SALES_CREDITS_DISTRICT_ID ON RTRADM.SALES_CREDITS (DISTRICT_ID);
CREATE INDEX REPL_SALES_CREDITS_SALESREP_ID ON RTRADM.SALES_CREDITS (SALESREP_ID);
CREATE INDEX REPL_SALES_CREDITS_SO_NUMBER ON RTRADM.SALES_CREDITS (SO_NUMBER);
CREATE INDEX SALES_CREDITS_THTR  ON RTRADM.SALES_CREDITS(THEATER);
CREATE INDEX RTRADM.SALES_CREDITS_EFCT_END_DATE on RTRADM.SALES_CREDITS(EFFECTIVE_END_DATE);
