
CREATE TABLE CLIENTE ( 
            ID_CLIENTE                 BIGINT NOT NULL,
            NOMBRE                     VARCHAR(20) NOT NULL,
            ID_PROTOCOLO                       DECIMAL(2,0) NOT NULL,
            MONEDA                     DECIMAL(2,0) NOT NULL,
            TIMEOUT_CLIENTE                   DECIMAL(10,0) NOT NULL,
            TIMEOUT_PPAS                       DECIMAL(10,0) NOT NULL,
            TTL_REVERSO                         DECIMAL(10,0) DEFAULT 0 NOT NULL,
            CVE_GSM_ABO                       VARCHAR(10) NOT NULL,
            CVE_GSM_REV                        VARCHAR(10) NOT NULL,
            CVE_GSM_COMISION              VARCHAR(10) NOT NULL,
            CVE_GSM_COMISION_REV                  VARCHAR(10) NOT NULL,
            UP_DATE_BY                           VARCHAR(10) NOT NULL,
            TRANS_NUMBER_ABO             VARCHAR(10) NOT NULL,
            TRANS_NUMBER_REV             VARCHAR(10) NOT NULL,
            ADJ_SHORT_DESC_COMISION             VARCHAR(15) NOT NULL,
            ADJ_COMMENT_COMISION                  VARCHAR(60) NOT NULL,
            ADJ_SHORT_DESC_COMISION_REV    VARCHAR(15) NOT NULL,
            ADJ_COMMENT_COMISION_REV          VARCHAR(60) NOT NULL,
            COMISION                   DECIMAL(10,2) DEFAULT 0 NOT NULL,
            ACCIONES_VALIDAS                VARCHAR(100) NOT NULL,
            MONTOS_VALIDOS                  VARCHAR(100) NOT NULL,
            REGIONES_VALIDAS                VARCHAR(100) NOT NULL,
            NOTIFICA_ACCION                    DECIMAL(1,0) DEFAULT 0 NOT NULL,
            TIEMPO_PAUSA                       DECIMAL(10,0) DEFAULT 0 NOT NULL,
            MAINT_ACCION                        VARCHAR(100) NOT NULL,
            MAINT_UNDO                           VARCHAR(100) NOT NULL,
            TIPO_BOLSA                            DECIMAL(2,0) DEFAULT 0 NOT NULL,
            FLAGS                         DECIMAL(16,0) NOT NULL,
            RFC                              VARCHAR(15) NULL,
            ORIGIN_NODE_TYPE                VARCHAR(20) NULL 
            ) 
PARTITION BY COLUMN (ID_CLIENTE);

CREATE TABLE ACCION ( 
            ID_ACCION                   DECIMAL(10,0) NOT NULL,
            TIPO_ACCION               DECIMAL(3,0) NOT NULL,
            INTERNA                      DECIMAL(1,0) NOT NULL,
            PRINCIPAL                   DECIMAL(10,2) NULL,
            SUB_CTA1                    DECIMAL(10,2) NULL,
            SUB_CTA2                    DECIMAL(10,2) NULL,
            SUB_CTA3                    DECIMAL(10,2) NULL,
            SUB_CTA4                    DECIMAL(10,2) NULL,
            SUB_CTA5                    DECIMAL(10,2) NULL,
            SUB_CTA6                    DECIMAL(10,2) NULL,
            SUB_CTA7                    DECIMAL(10,2) NULL,
            SUB_CTA8                    DECIMAL(10,2) NULL,
            SUB_CTA9                    DECIMAL(10,2) NULL,
            SUB_CTA10                  DECIMAL(10,2) NULL,
            SUPERVISION_DATE                DECIMAL(10,0) NULL,
            SERVICE_FEE_DATE               DECIMAL(10,0) NULL,
            SERVICE_REMOVAL_DATE      DECIMAL(10,0) NULL,
            CREDIT_CLEARANCE_DATE     DECIMAL(10,0) NULL,
            SUB_CTA1_DATE        DECIMAL(10,0) NULL,
            SUB_CTA2_DATE        DECIMAL(10,0) NULL,
            SUB_CTA3_DATE        DECIMAL(10,0) NULL,
            SUB_CTA4_DATE        DECIMAL(10,0) NULL,
            SUB_CTA5_DATE        DECIMAL(10,0) NULL,
            SUB_CTA6_DATE        DECIMAL(10,0) NULL,
            SUB_CTA7_DATE        DECIMAL(10,0) NULL,
            SUB_CTA8_DATE        DECIMAL(10,0) NULL,
            SUB_CTA9_DATE        DECIMAL(10,0) NULL,
            SUB_CTA10_DATE       DECIMAL(10,0) NULL,
            TIPO_CAMBIO              DECIMAL(10,2) NULL,
            COMISION                    DECIMAL(10,2) NULL,
            BOLSA                         DECIMAL(17,2) NULL,
            FECHA                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            MES                             DECIMAL(2,0) NULL,
			ID_CLIENTE              BIGINT NOT NULL
            ) 
PARTITION BY COLUMN (ID_CLIENTE)
COLOCATE WITH (CLIENTE);

CREATE TABLE ADMINISTRACION ( 
            PARAMETRO    VARCHAR(20) NOT NULL,
            DESCRIPCION  VARCHAR(100) NOT NULL,
            VALOR             VARCHAR(100) NOT NULL,
            ARGS               VARCHAR(100) NULL,
            ESTATUS         DECIMAL(2,0) DEFAULT 0 NOT NULL 
            )
REPLICATE;

CREATE TABLE AUTENTICA ( 
            PUERTO_SERVICIO      DECIMAL(5,0) NOT NULL,
            IP_CLIENTE                  VARCHAR(23) NOT NULL,
            CODIGO_CLIENTE        VARCHAR(10) NOT NULL,
            ID_CLIENTE                  BIGINT NOT NULL,
            ESTATUS_CONEXION   DECIMAL(2,0) DEFAULT 0 NOT NULL 
            )
REPLICATE;

CREATE TABLE BALANCE ( 
            ID_BALANCE                DECIMAL(10,0) NOT NULL,
            PRINCIPAL                   DECIMAL(10,2) NOT NULL,
            SUB_CTA1                    DECIMAL(10,2) NULL,
            SUB_CTA2                    DECIMAL(10,2) NULL,
            SUB_CTA3                    DECIMAL(10,2) NULL,
            SUB_CTA4                    DECIMAL(10,2) NULL,
            SUB_CTA5                    DECIMAL(10,2) NULL,
            SUB_CTA6                    DECIMAL(10,2) NULL,
            SUB_CTA7                    DECIMAL(10,2) NULL,
            SUB_CTA8                    DECIMAL(10,2) NULL,
            SUB_CTA9                    DECIMAL(10,2) NULL,
            SUB_CTA10                  DECIMAL(10,2) NULL,
            SUPERVISION_DATE                VARCHAR(14) NOT NULL,
            SERVICE_FEE_DATE               VARCHAR(14) NULL,
            SERVICE_REMOVAL_DATE      VARCHAR(14) NULL,
            CREDIT_CLEARANCE_DATE     VARCHAR(14) NULL,
            SUB_CTA1_DATE        VARCHAR(14) NULL,
            SUB_CTA2_DATE        VARCHAR(14) NULL,
            SUB_CTA3_DATE        VARCHAR(14) NULL,
            SUB_CTA4_DATE        VARCHAR(14) NULL,
            SUB_CTA5_DATE        VARCHAR(14) NULL,
            SUB_CTA6_DATE        VARCHAR(14) NULL,
            SUB_CTA7_DATE        VARCHAR(14) NULL,
            SUB_CTA8_DATE        VARCHAR(14) NULL,
            SUB_CTA9_DATE        VARCHAR(14) NULL,
            SUB_CTA10_DATE       VARCHAR(14) NULL,
            ESTATUS                     DECIMAL(2,0) NOT NULL,
            PLAN                            DECIMAL(8,0) NOT NULL,
            FECHA                         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            MES                             DECIMAL(2,0) NULL,
			ID_CLIENTE              BIGINT NOT NULL
            )
PARTITION BY COLUMN (ID_CLIENTE)
COLOCATE WITH (CLIENTE);

CREATE TABLE BUZON ( 
            TELEFONO      DECIMAL(12,0) NOT NULL,
            TIPO_ACCION               DECIMAL(3,0) NOT NULL,
            AUTORIZADOR             DECIMAL(7,0) DEFAULT 0 NULL,
            ID_TRANSACCION        BIGINT DEFAULT 0 NULL,
            ESTATUS         DECIMAL(10,0) DEFAULT 0 NULL 
            )
REPLICATE;

CREATE TABLE DPROMOCION ( 
            ID_PROMOCION           DECIMAL(10,0) NOT NULL,
            ID_GRUPO        DECIMAL(10,0) NOT NULL 
            )
REPLICATE;

CREATE TABLE GRUPO ( 
            ID_GRUPO        DECIMAL(10,0) NOT NULL,
            DESCRIPCION  VARCHAR(100) NOT NULL 
            )
REPLICATE;

CREATE TABLE DRESULTADO ( 
            ID_CLIENTE      BIGINT NOT NULL,
            ID_RESULTADO            DECIMAL(10,0) NOT NULL,
            CODIGO           CHAR(2) NOT NULL 
            )
PARTITION BY COLUMN (ID_CLIENTE)
COLOCATE WITH (CLIENTE);

CREATE TABLE PLAN ( 
            ID_GRUPO        DECIMAL(10,0) NOT NULL,
            PLAN                DECIMAL(8,0) NOT NULL,
            REGION            DECIMAL(2,0) NOT NULL,
            TECNOLOGIA   DECIMAL(2,0) NOT NULL,
            DESCRIPCION  VARCHAR(50) NOT NULL,
            SUB_CTAS       DECIMAL(1,0) NOT NULL 
            )
REPLICATE;

CREATE TABLE PROMOCION ( 
            ID_PROMOCION           DECIMAL(10,0) NOT NULL,
            MONEDA          DECIMAL(2,0) NOT NULL,
            MONTO_INI       DECIMAL(10,2) NOT NULL,
            MONTO_FIN      DECIMAL(10,2) NOT NULL,
            REGION_INI      DECIMAL(2,0) NOT NULL,
            REGION_FIN     DECIMAL(2,0) NOT NULL,
            TECNOLOGIA  DECIMAL(2,0) NOT NULL,
            VG_NORMAL   VARCHAR(5) NOT NULL,
            VG_SUB_CTA  VARCHAR(5) NOT NULL,
            VIGENCIA         DECIMAL(5,0) NOT NULL,
            SUB_CTA1        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA2        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA3        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA4        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA5        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA6        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA7        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA8        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA9        DECIMAL(10,2) DEFAULT 0 NOT NULL,
            SUB_CTA10      DECIMAL(10,2) DEFAULT 0 NOT NULL,
            FECHA             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL 
            )
REPLICATE;

CREATE TABLE RESULTADO ( 
            ID_RESULTADO            DECIMAL(10,0) NOT NULL,
            DESCRIPCION VARCHAR(100) NOT NULL 
            )
REPLICATE;

CREATE TABLE SERVIDOR ( 
            ID_SERVIDOR   DECIMAL(10,0) NOT NULL,
            TECNOLOGIA   DECIMAL(2,0) NOT NULL,
            REGION            DECIMAL(2,0) NOT NULL,
            ESTATUS         DECIMAL(2,0) NOT NULL,
            IP                     VARCHAR(23) NOT NULL,
            PUERTO           DECIMAL(5,0) NOT NULL,
            INSTANCIA       VARCHAR(50) NULL,
            USUARIO          VARCHAR(65) NULL,
            PASSWORD     VARCHAR(65) NULL 
            )
REPLICATE;

CREATE TABLE TRANSACCION ( 
            ID_TRANSACCION        BIGINT NOT NULL,  --original 38   max 31
            ID_CLIENTE      BIGINT NOT NULL,
            FOLIO               DECIMAL(6,0) NOT NULL,
            FECHA_TELCEL           TIMESTAMP NOT NULL,
            TELEFONO      DECIMAL(12,0) NOT NULL,
            REGION            DECIMAL(2,0) NULL,
            TECNOLOGIA               DECIMAL(2,0) NULL,
            MONTO            DECIMAL(10,2) NOT NULL,
            FECHA             DECIMAL(8,0) NOT NULL,
            HORA               DECIMAL(6,0) NOT NULL,
            FECHA_LOCAL             DECIMAL(8,0) NOT NULL,
            HORA_LOCAL               DECIMAL(6,0) NOT NULL,
            ID_MENSAJE                VARCHAR(30) NOT NULL,
            ID_CCOMERCIAL          VARCHAR(30) NOT NULL,
            ID_TIENDA        VARCHAR(30) NOT NULL,
            ID_CAJA           VARCHAR(30) NOT NULL,
            SECUENCIA                 VARCHAR(12) NOT NULL,
            ID_RESULTADO            DECIMAL(10,0) NOT NULL,
            TTL                   DECIMAL(10,0) NULL,
            ID_ACCION       DECIMAL(10,0) NULL,
            ID_ACCION_REV           DECIMAL(10,0) NULL,
            ID_BALANCE                DECIMAL(10,0) NULL,
            ID_BALANCE_REV        DECIMAL(10,0) NULL,
            FECHA_REVERSO       TIMESTAMP NULL,
            MES                 DECIMAL(2,0) NULL,
            NHORA             DECIMAL(2,0) NULL 
            )
PARTITION BY COLUMN (ID_CLIENTE)
COLOCATE WITH (CLIENTE);

CREATE TABLE HISTORICO_REVERSOS ( 
            ID_TRANSACCION        BIGINT NOT NULL,
            FECHA_TELCEL           TIMESTAMP NOT NULL,
            INTERNO          VARCHAR(1) NOT NULL,
            PUERTO           DECIMAL(8,0) NOT NULL 
            )
PARTITION BY COLUMN (ID_TRANSACCION)
COLOCATE WITH (TRANSACCION);

CREATE TABLE REVERSOS ( 
            ID_TRANSACCION        BIGINT NOT NULL,
            FECHA_TELCEL           TIMESTAMP NOT NULL,
            PUERTO           DECIMAL(8,0) NOT NULL 
            )
PARTITION BY COLUMN (ID_TRANSACCION)
COLOCATE WITH (TRANSACCION);


CREATE TABLE TRANSACCION2 ( 
            ID_TRANSACCION        BIGINT NOT NULL,  --original 38   max 31
            ID_CLIENTE      BIGINT NOT NULL,
            FOLIO               DECIMAL(6,0) NOT NULL,
            FECHA_TELCEL           TIMESTAMP NOT NULL,
            TELEFONO      DECIMAL(12,0) NOT NULL,
            REGION            DECIMAL(2,0) NULL,
            TECNOLOGIA               DECIMAL(2,0) NULL,
            MONTO            DECIMAL(10,2) NOT NULL,
            FECHA             DECIMAL(8,0) NOT NULL,
            HORA               DECIMAL(6,0) NOT NULL,
            FECHA_LOCAL             DECIMAL(8,0) NOT NULL,
            HORA_LOCAL               DECIMAL(6,0) NOT NULL,
            ID_MENSAJE                VARCHAR(30) NOT NULL,
            ID_CCOMERCIAL          VARCHAR(30) NOT NULL,
            ID_TIENDA        VARCHAR(30) NOT NULL,
            ID_CAJA           VARCHAR(30) NOT NULL,
            SECUENCIA                 VARCHAR(12) NOT NULL,
            ID_RESULTADO            DECIMAL(10,0) NOT NULL,
            TTL                   DECIMAL(10,0) NULL,
            ID_ACCION       DECIMAL(10,0) NULL,
            ID_ACCION_REV           DECIMAL(10,0) NULL,
            ID_BALANCE                DECIMAL(10,0) NULL,
            ID_BALANCE_REV        DECIMAL(10,0) NULL,
            FECHA_REVERSO       TIMESTAMP NULL,
            MES                 DECIMAL(2,0) NULL,
            NHORA             DECIMAL(2,0) NULL 
            )
PARTITION BY COLUMN (ID_CLIENTE);

CREATE TABLE REVERSOS2 ( 
            ID_TRANSACCION        BIGINT NOT NULL primary key,
            FECHA_TELCEL           TIMESTAMP NOT NULL,
            PUERTO           DECIMAL(8,0) NOT NULL 
            )
PARTITION BY COLUMN (ID_TRANSACCION)
COLOCATE WITH (TRANSACCION2);



CREATE INDEX IDX_ACCION
        ON ACCION(TIPO_ACCION, INTERNA);
CREATE INDEX UK_ADMINISTRACION
        ON ADMINISTRACION(ESTATUS);
CREATE INDEX IDX_AUTENTICA_2
        ON AUTENTICA(ESTATUS_CONEXION);
CREATE INDEX IDX_AUTENTICA_1
        ON AUTENTICA(ID_CLIENTE);
CREATE UNIQUE INDEX UIDX_BALANCE
        ON BALANCE(ID_BALANCE);
CREATE INDEX IDX_PLAN_BALANCE
        ON BALANCE(PLAN);
CREATE INDEX IDX_BUZON
        ON BUZON(AUTORIZADOR);
CREATE INDEX FK_IDX_DPROMOCION_1
        ON DPROMOCION(ID_GRUPO);
CREATE INDEX FK_IDX_DPROMOCION_2
        ON DPROMOCION(ID_PROMOCION);
CREATE INDEX FK_IDX_DRESULTADO_2
        ON DRESULTADO(ID_RESULTADO);
CREATE INDEX IDX_DRESULTADO
        ON DRESULTADO(CODIGO);
CREATE INDEX FK_IDX_DRESULTADO_1
        ON DRESULTADO(ID_CLIENTE);
CREATE INDEX IDX_FEC_HIST_REVERSOS
        ON HISTORICO_REVERSOS(FECHA_TELCEL);
CREATE UNIQUE INDEX SYS_C0026539
        ON HISTORICO_REVERSOS(ID_TRANSACCION);
CREATE INDEX FK_PLAN
        ON PLAN(ID_GRUPO);
CREATE INDEX IDX_PROMOCION
        ON PROMOCION(MONEDA, MONTO_INI, MONTO_FIN, REGION_INI, REGION_FIN, TECNOLOGIA);
CREATE UNIQUE INDEX SYS_C0026543
        ON REVERSOS(ID_TRANSACCION);
CREATE INDEX IDX_SERVIDOR
        ON SERVIDOR(TECNOLOGIA, REGION, ESTATUS);
CREATE UNIQUE INDEX UK_SERVIDOR
        ON SERVIDOR(TECNOLOGIA, REGION, IP, PUERTO);
CREATE INDEX IDX_TRANSACCION_3
        ON TRANSACCION(FECHA_TELCEL, TTL);
CREATE INDEX IDX_TRANSACCION_2
        ON TRANSACCION(FECHA_TELCEL, ID_RESULTADO);
CREATE INDEX IDX_CLIENTE
        ON TRANSACCION(ID_CLIENTE);
CREATE INDEX IDX_TRANSACCION_4
        ON TRANSACCION(FECHA_TELCEL, ID_RESULTADO, REGION, TECNOLOGIA);
CREATE INDEX IDX_TRANSACCION_6
        ON TRANSACCION(FOLIO);
CREATE INDEX IDX_TRANSACCION_1
        ON TRANSACCION(FECHA_TELCEL);
CREATE UNIQUE INDEX UK_TRANSACCION
        ON TRANSACCION(ID_CLIENTE, TELEFONO, MONTO, FECHA_LOCAL, HORA_LOCAL, SECUENCIA);
CREATE INDEX IDX_TRANSACCION_5
        ON TRANSACCION(TELEFONO);

ALTER TABLE GRUPO
        ADD CONSTRAINT PK_GRUPO
        PRIMARY KEY (ID_GRUPO)
        ;
ALTER TABLE ADMINISTRACION
        ADD CONSTRAINT PK_ADMINISTRACION
        PRIMARY KEY (PARAMETRO)
        ;
ALTER TABLE AUTENTICA
        ADD CONSTRAINT PK_AUTENTICA
        PRIMARY KEY (PUERTO_SERVICIO, IP_CLIENTE, CODIGO_CLIENTE)
        ;
ALTER TABLE BUZON
        ADD CONSTRAINT PK_BUZON
        PRIMARY KEY (TELEFONO)
        ;
ALTER TABLE CLIENTE
        ADD CONSTRAINT PK_CLIENTE
        PRIMARY KEY (ID_CLIENTE)
        ;
ALTER TABLE DPROMOCION
        ADD CONSTRAINT PK_DPROMOCION
        PRIMARY KEY (ID_PROMOCION, ID_GRUPO)
        ;
ALTER TABLE DRESULTADO
        ADD CONSTRAINT PK_DRESULTADO
        PRIMARY KEY (ID_CLIENTE, ID_RESULTADO)
        ;
ALTER TABLE HISTORICO_REVERSOS
        ADD CONSTRAINT SYS_C0026539
        PRIMARY KEY (ID_TRANSACCION)
        ;
ALTER TABLE PLAN
        ADD CONSTRAINT PK_PLAN
        PRIMARY KEY (PLAN, REGION, TECNOLOGIA)
        ;
ALTER TABLE PROMOCION
        ADD CONSTRAINT PK_PROMOCION
        PRIMARY KEY (ID_PROMOCION)
        ;
ALTER TABLE RESULTADO
        ADD CONSTRAINT PK_RESULTADO
        PRIMARY KEY (ID_RESULTADO)
        ;
ALTER TABLE REVERSOS
        ADD CONSTRAINT SYS_C0026543
        PRIMARY KEY (ID_TRANSACCION)
        ;
ALTER TABLE SERVIDOR
        ADD CONSTRAINT PK_SERVIDOR
        PRIMARY KEY (ID_SERVIDOR)
        ;

ALTER TABLE ACCION
        ADD CONSTRAINT PK_ACCION
        PRIMARY KEY (ID_ACCION);

ALTER TABLE BALANCE
        ADD CONSTRAINT PK_BALANCE
        PRIMARY KEY (ID_BALANCE);


/*
ALTER TABLE AUTENTICA
        ADD CONSTRAINT FK_AUTENTICA_CLIENTE
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
        ;
ALTER TABLE DPROMOCION
        ADD CONSTRAINT FK_DPROMOCION_PROMOCION
        FOREIGN KEY(ID_PROMOCION)
        REFERENCES PROMOCION(ID_PROMOCION)
        ;
ALTER TABLE DPROMOCION
        ADD CONSTRAINT FK_DPROMOCION_GRUPO
        FOREIGN KEY(ID_GRUPO)
        REFERENCES GRUPO(ID_GRUPO)
        ;
ALTER TABLE DRESULTADO
        ADD CONSTRAINT FK_DRESULTADO_RESULTADO
        FOREIGN KEY(ID_RESULTADO)
        REFERENCES RESULTADO(ID_RESULTADO)
        ;
ALTER TABLE DRESULTADO
        ADD CONSTRAINT FK_DRESULTADO_CLIENTE
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
        ;
ALTER TABLE PLAN
        ADD CONSTRAINT FK_PLAN_GRUPO
        FOREIGN KEY(ID_GRUPO)
        REFERENCES GRUPO(ID_GRUPO)
        ;
ALTER TABLE TRANSACCION
        ADD CONSTRAINT FK_TRANSACCION_CLIENTE
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
        ;

ALTER TABLE ACCION
        ADD CONSTRAINT FK_ACCION_CLIENTE
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
        ;

ALTER TABLE BALANCE
        ADD CONSTRAINT FK_BALANCE_CLIENTE
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
        ;
*/
/* comentados por el momento
ALTER TABLE TRANSACCION
        ADD CONSTRAINT FK_TRANSACCION_ACCION
        FOREIGN KEY(ID_ACCION)
        REFERENCES ACCION(ID_ACCION)
        ;

ALTER TABLE TRANSACCION
        ADD CONSTRAINT FK_TRANSACCION_BALANCE
        FOREIGN KEY(ID_BALANCE)
        REFERENCES BALANCE(ID_BALANCE)
        ;

ALTER TABLE TRANSACCION
        ADD CONSTRAINT FK_TRANSACCION_ACCION_REV
        FOREIGN KEY(ID_ACCION_REV)
        REFERENCES ACCION(ID_ACCION)
        ;

ALTER TABLE TRANSACCION
        ADD CONSTRAINT FK_TRANSACCION_BALANCE_REV
        FOREIGN KEY(ID_BALANCE_REV)
        REFERENCES BALANCE(ID_BALANCE)
        ;
*/

CREATE TABLE DUAL
(SYSDATE timestamp);
