DROP TABLE IF EXISTS RTRADM.SALES_CREDITS;
CREATE TABLE RTRADM.SALES_CREDITS
(
SALES_CREDIT_ID                         BIGINT,
SALES_CREDIT_TYPE_ID            VARCHAR(2),
SALESREP_ID                             BIGINT,
SO_NUMBER                                       VARCHAR(40),
DISTRICT_ID                         BIGINT,
PERCENT                                     DOUBLE,
LAST_UPDATE_DATE                        DATE,
EFFECTIVE_END_DATE                      DATE,
SALESREP_NUMBER                         VARCHAR(100),
GDW_PROCESS_FLAG            CHAR(1) DEFAULT 'N',
SOURCE_BUCKET                           VARCHAR(20),
AIC_LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
THEATER                     VARCHAR(50)
) EVICTION BY LRUMEMSIZE 1024 EVICTACTION OVERFLOW PERSISTENT 'RTRADM_DATA01' ASYNCHRONOUS
