CREATE TABLE TX_PL_POSITION 
  (	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(16,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_MNEM_CD VARCHAR(16), 
	CUSIP_CD VARCHAR(30), 
	CORPUS_ID NUMERIC(21,0) NOT NULL, 
	CCY_CD VARCHAR(3), 
	LNG_SHRT_CD VARCHAR(1), 
	BRKR_CD VARCHAR(2), 
	TRAN_TYP_CD VARCHAR(30), 
	REGIS_COUP_CD VARCHAR(1), 
	SUB_ACCT_CD VARCHAR(1), 
	SRC_SYS_CD VARCHAR(20), 
	RGN_CD VARCHAR(2), 
	ORIG_FIRM_ACCT_ID NUMERIC(21,0), 
	SCR_FI_CD NUMERIC(21,0), 
	CCY_ID NUMERIC(21,0) NOT NULL, 
	SRC_SYS_ID NUMERIC(21,0), 
	POSN_EXT_KEY_ID NUMERIC(21,0) NOT NULL, 
	RGN_ID NUMERIC(21,0), 
	LTD_OFS_TM_ID NUMERIC(21,0), 
	STRC_DESC VARCHAR(64), 
	CUSIP_SRC_CD VARCHAR(20)
   ) PARTITION BY COLUMN (PL_POSN_ID) REDUNDANCY 1;

CREATE TABLE TF_PL_POSITION_DLY 
  (	TM_ID NUMERIC(21,0) NOT NULL, 
	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	OBJ_INST_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	INSM_ID NUMERIC(21,0) NOT NULL, 
	CCY_ID NUMERIC(21,0) NOT NULL, 
	POSN_EXT_KEY_ID NUMERIC(21,0) NOT NULL, 
	TRDR_ID NUMERIC(21,0), 
	SRC_SYS_ID NUMERIC(21,0) NOT NULL, 
	RGN_ID NUMERIC(21,0) NOT NULL, 
	TD_PL_POSN_INDIC_ID NUMERIC(21,0) NOT NULL, 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	REC_STA_CD VARCHAR(1), 
	DLY_GL_RLZD_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_ADMIN_EXPN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_PYDN_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_UNACRTD_PYDN_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_PYDN_RLZD_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_OCI_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_OCI_ACRTN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_IMPRMT_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_UNACRTD_RLZD_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_UNACRTD_PYDN_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_PYDN_RLZD_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	UREL_DISP_FAC NUMERIC(1,0) DEFAULT 1, 
	UREL_CALC_FAC NUMERIC(1,0) DEFAULT 1
   ) PARTITION BY COLUMN (PL_POSN_ID)
   COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE TABLE TF_EQRMS_PAA
 (
    TM_ID                NUMERIC(21,0) NOT NULL,
    PL_POSN_ID           NUMERIC(21,0),
    POSITION_ID          VARCHAR(99),
    COMPOUND_POS_ID      VARCHAR(99),
    OASYSDEALID          VARCHAR(30),
    OASYSTRANSACTIONID   NUMERIC(21,0),
    CORPUSID             NUMERIC(21,0),
    CUSIP                VARCHAR(30),
    PACKAGE_NUMERIC       VARCHAR(99),
    COMPONENT_MNEM       VARCHAR(99),
    FIRMACCOUNTMNEMONIC  VARCHAR(99),
    EXPIRY               VARCHAR(99),
    STRIKE               NUMERIC(31,8),
    PC1                  VARCHAR(10),
    SECURITY_TYPE        VARCHAR(99),
    MODEL_NAME           VARCHAR(99),
    AVERAGE_COST         NUMERIC(31,8),
    CURRENCY             VARCHAR(99),
    FX_RATE              NUMERIC(31,8),
    QUANTITY_T2          NUMERIC(31,8),
    QUANTITY_T1          NUMERIC(31,8),
    TRADE_QUANTITY       NUMERIC(31,8),
    FAIR_VALUE           NUMERIC(31,8),
    COB_PRICE            NUMERIC(31,8),
    UNDERLYING_PRICE_T2  NUMERIC(31,8),
    UNDERLYING_PRICE_T1  NUMERIC(31,8),
    TOTAL_DELTA          NUMERIC(31,8),
    TOTAL_GAMMA          NUMERIC(31,8),
    VEGA                 NUMERIC(31,8),
    PV01_BP              NUMERIC(31,8),
    CR01                 NUMERIC(31,8),
    DELTA                NUMERIC(31,8),
    GAMMA                NUMERIC(31,8),
    OTHER_SPOT           NUMERIC(31,8),
    SPOT_PAA             NUMERIC(31,8),
    SPOT_VOL             NUMERIC(31,8),
    SPOT_INTRATE         NUMERIC(31,8),
    SPOT_THETA           NUMERIC(31,8),
    DVD_PL               NUMERIC(31,8),
    VOLATILITY           NUMERIC(31,8),
    RATE                 NUMERIC(31,8),
    CORRELATION          NUMERIC(31,8),
    ASSET_FX_CORRELATION NUMERIC(31,8),
    DIVIDEND             NUMERIC(31,8),
    BORROW_COST          NUMERIC(31,8),
    THETA                NUMERIC(31,8),
    FX_DELTA             NUMERIC(31,8),
    MARK_TO_MKT          NUMERIC(31,8),
    STATIC_PAA_TOTAL     NUMERIC(31,8),
    SECURITY_CHANGE      NUMERIC(31,8),
    KO_TRADES            NUMERIC(31,8),
    EXTROADINARY_PL_T1   NUMERIC(31,8),
    NEW_TRADES           NUMERIC(31,8),
    DAY_TRADING          NUMERIC(31,8),
    UPSIZE_DOWNSIZE      NUMERIC(31,8),
    TERMINATED_TRADES    NUMERIC(31,8),
    INTRADAY_TRADING_PL  NUMERIC(31,8),
    FINANCING_T1         NUMERIC(31,8),
    TOTAL_PAA            NUMERIC(31,8),
    FAIR_ECONOMIC_PL     NUMERIC(31,8),
    RESIDUAL             NUMERIC(31,8),
    UNDERLYINGMNEM       VARCHAR(99),
    PL_CURRENCY          VARCHAR(99),
    UNDERLYINGRIC        VARCHAR(99),
    UNDERLYINGISSUERIC   VARCHAR(99),
    COMPANY_NAME         VARCHAR(99),
    IR_VOL_CUBE          NUMERIC(31,8),
    OSYS                 VARCHAR(99),
    DLY_FX_IMPACT        NUMERIC(31,8),
    MTD_OFF_ECONOM_DFX   NUMERIC(31,8),
    MTD_OFF_ECONOM_USD   NUMERIC(31,8),
    POSN_ALT_STR1        VARCHAR(99),
    POSN_ALT_STR2        VARCHAR(99),
    POSN_ALT_COM2        VARCHAR(99),
    COMPONENT_MNEM_RIC   VARCHAR(99),
    FAIR_VOL             NUMERIC(31,8),
    SECURITY_MNEM        VARCHAR(99),
    ACCOUNT_ENTITY       VARCHAR(99),
    EXOTIC_TYPE          VARCHAR(99),
    SECURITY_CLASS       VARCHAR(99),
    UNDERLYING_TYPE      VARCHAR(99),
    REALISED             NUMERIC(31,8),
    DIVIDEND_PL          NUMERIC(31,8),
    INTEREST_PL          NUMERIC(31,8),
    COMMISSION_PL        NUMERIC(31,8),
    EXTRAORDINARY_PL     NUMERIC(31,8),
    COUPON_PL            NUMERIC(31,8),
    FAIR_ECONOMIC        NUMERIC(31,8),
    FAIR_VALUE_UCCY      NUMERIC(31,8),
    PL_CURR_ID           NUMERIC(21,0),
    CCY_ID               NUMERIC(21,0),
    FIRM_ACCT_ID         NUMERIC(21,0),
    INSM_ID              NUMERIC(21,0),
    LOAD_FILE_NAME       VARCHAR(64),
    LOAD_LINE_NO         NUMERIC(21,0),
    REC_MDFY_USER_ID     VARCHAR(16),
    REC_MDFY_DTM TIMESTAMP,
    REC_MDFY_METH_DESC VARCHAR(30),
    PROC_LOG_ID        NUMERIC(16,0),
    ERR_ID             NUMERIC(21,0),
    PAA_ID             NUMERIC(21,0),
    RGN_ID             NUMERIC(21,0),
    DESCRIPTION        VARCHAR(99)
  ) PARTITION BY COLUMN (PL_POSN_ID)
  COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE INDEX TF_EQRMS_PAA_ID ON 
  TF_EQRMS_PAA
 (
    TM_ID, PAA_ID, RGN_ID
  );

CREATE
    INDEX TF_EQRMS_PAA_NUI ON TF_EQRMS_PAA
   (
      TM_ID,
      PL_POSN_ID,
      RGN_ID
    );

CREATE TABLE TF_EDEALER_PAA
 (
    TM_ID               NUMERIC(21,0) NOT NULL,
    PL_POSN_ID          NUMERIC(21,0),
    FIRMACCOUNTMNEMONIC VARCHAR(99),
    CURRENCY            VARCHAR(99),
    CURRENCYPAIR        VARCHAR(99),
    OASYSDEALID         VARCHAR(30),
    OASYSTRANSACTIONID  NUMERIC(21,0),
    CORPUSID            NUMERIC(21,0),
    DELTASPOT           NUMERIC(31,8),
    DELTAFORWARD        NUMERIC(31,8),
    THETA               NUMERIC(31,8),
    NEWTRADES           NUMERIC(31,8),
    TRADEADJUSTMENTS    NUMERIC(31,8),
    CARRYONCHARGE       NUMERIC(31,8),
    NRFFFUNDING         NUMERIC(31,8),
    RESIDUE             NUMERIC(31,8),
    CCY_ID              NUMERIC(21,0),
    FIRM_ACCT_ID        NUMERIC(21,0),
    INSM_ID             NUMERIC(21,0),
    LOAD_FILE_NAME      VARCHAR(64),
    LOAD_LINE_NO        NUMERIC(21,0),
    REC_MDFY_USER_ID    VARCHAR(16),
    REC_MDFY_DTM TIMESTAMP,
    REC_MDFY_METH_DESC VARCHAR(30),
    PROC_LOG_ID        NUMERIC(16,0),
    ERR_ID             NUMERIC(21,0),
    PAA_ID             NUMERIC(21,0),
    RGN_ID             NUMERIC(21,0)
  )PARTITION BY COLUMN (PL_POSN_ID)
  COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE INDEX TF_EDEALER_PAA_ID ON 
  TF_EDEALER_PAA
 (
    TM_ID, PAA_ID, RGN_ID
  );

CREATE INDEX TF_EDEALER_PAA_NUI ON TF_EDEALER_PAA
   (
      TM_ID,
      PL_POSN_ID,
      RGN_ID
    );

CREATE TABLE TX_PL_USER_POSN_MAP 
  (	TM_ID NUMERIC(21,0) NOT NULL, 
	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(16,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	USER_DEFN_1 VARCHAR(255), 
	USER_DEFN_2 VARCHAR(255), 
	USER_DEFN_3 VARCHAR(255), 
	USER_DEFN_4 VARCHAR(255), 
	USER_DEFN_5 VARCHAR(255), 
	PC_RGN VARCHAR(50), 
	STRC_DESC VARCHAR(64), 
	COUP_RT NUMERIC(31,19), 
	TRD_CLAS_CD VARCHAR(1), 
	MDTS_SCR_TYP_ID NUMERIC(21,0), 
	MDTS_SCR_TYP_DESC VARCHAR(30), 
	SETL_ACCT_PRD_NO NUMERIC(5,0), 
	OBJ_INST_ID NUMERIC(21,0), 
	FIRM_ACCT_ID NUMERIC(21,0), 
	INSM_ID NUMERIC(21,0), 
	CCY_ID NUMERIC(21,0), 
	POSN_EXT_KEY_ID NUMERIC(21,0), 
	SRC_SYS_ID NUMERIC(21,0), 
	RGN_ID NUMERIC(21,0), 
	TD_PL_POSN_INDIC_ID NUMERIC(21,0), 
	FUNC_CURX_FAC NUMERIC(31,19), 
	USD_CURX_FAC NUMERIC(31,19), 
	PRC_FAC NUMERIC(31,19), 
	USER_DEFN_MAT_DT DATE, 
	GFRN_CD VARCHAR(100), 
	LN_EFF_DT DATE, 
	PRNT_CUSIP_CD VARCHAR(30), 
	PRNT_INSM_ID NUMERIC(21,0), 
	PROOF_CD VARCHAR(10), 
	PRNT_ID VARCHAR(30), 
	SUB_CAT_DESC VARCHAR(40)
   ) PARTITION BY (PL_POSN_ID)
   COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE TABLE TL_SOURCE_SYSTEM 
  (	SRC_SYS_ID NUMERIC(21,0), 
	SRC_SYS_CD VARCHAR(20), 
	SRC_SYS_DESC VARCHAR(30), 
	VARTN_CD VARCHAR(2), 
	CMPO_SRC1_DESC VARCHAR(30), 
	CMPO_SRC2_DESC VARCHAR(30), 
	CMPO_SRC3_DESC VARCHAR(30), 
	CMPO_SRC4_DESC VARCHAR(30), 
	CMPO_SRC5_DESC VARCHAR(30), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(21,0), 
	ERR_ID NUMERIC(21,0), 
	RACE_CORR_CD VARCHAR(1)
   ) REPLICATE;

CREATE TABLE TL_REGION 
  (	RGN_ID NUMERIC(21,0) NOT NULL, 
	RGN_CD VARCHAR(10), 
	RGN_NM VARCHAR(50), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	 PRIMARY KEY(RGN_ID)

   ) REPLICATE;

CREATE TABLE TL_CURRENCY 
  (	CCY_ID NUMERIC(21,0) NOT NULL, 
	OBJ_ID NUMERIC(21,0) NOT NULL, 
	CCY_CD VARCHAR(3) NOT NULL, 
	CCY_DESC VARCHAR(255), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL
   ) REPLICATE;

CREATE TABLE TF_PL_POSITION_YTD 
  (	TM_ID NUMERIC(21,0) NOT NULL, 
	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	QTD_USD_SD_ACCRETION_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_USD_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_CR_COST_WRTOFF_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_RTL_SC_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_MIDMKT_SC_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_IIG_SC_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_PRIN_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_FLR_BRKG_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_AGY_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_CPS_INST_AGY_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_REV_SHR_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_SD_ACCRETION_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	REC_STA_CD VARCHAR(1), 
	YTD_GL_RLZD_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_UREL_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_UREL_PL_FX_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_UREL_PL_PREM_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_FUNC_SELL_CNCES_POT2_AMT NUMERIC(31,8) DEFAULT 0, 
	UREL_DISP_FAC NUMERIC, 
	UREL_CALC_FAC NUMERIC,
	FIRM_ACCT_ID NUMERIC(21,0) DEFAULT -1,
	YTD_FX_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_POSN_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_DIV_INCM_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_FUNC_TRAN_TAX_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_FUNC_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	YTD_FUNC_SD_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_GL_RLZD_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_DIV_INCM_AMT NUMERIC(31,8) DEFAULT 0, 
	QTD_FUNC_SD_ACCRETION_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	CCY_ID NUMERIC(21,0) DEFAULT -1, 
	OBJ_INST_ID NUMERIC(21,0), 
	QTD_FUNC_NET_ECON_OCI_PL_AMT NUMERIC(31,8)
   ) PARTITION BY COLUMN (PL_POSN_ID)
   COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE TABLE TF_PL_POSITION_PTD 
  (	TM_ID NUMERIC(21,0) NOT NULL, 
	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	OBJ_INST_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	INSM_ID NUMERIC(21,0) NOT NULL, 
	CCY_ID NUMERIC(21,0) NOT NULL, 
	POSN_EXT_KEY_ID NUMERIC(21,0) NOT NULL, 
	SRC_SYS_ID NUMERIC(21,0) NOT NULL, 
	PTD_DIV_INCM_AMT NUMERIC(31,8) DEFAULT 0, 
	ERY_TRMT_DTM TIMESTAMP, 
	LTD_OFS_TM_ID NUMERIC(21,0),
	AMORT_AMT NUMERIC(31,8) DEFAULT 0, 
	IMPRMT_IND NUMERIC(1,0), 
	PTD_RTL_SC_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_USD_SD_ACCRETION_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	LTD_USD_UREL_PL_PREM_AMT NUMERIC(31,8)
   ) PARTITION BY COLUMN (PL_POSN_ID)
     COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE TABLE TF_PL_POSITION_FUNC 
  (	TM_ID NUMERIC(21,0) NOT NULL, 
	PL_POSN_ID NUMERIC(21,0) NOT NULL, 
	OBJ_INST_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	INSM_ID NUMERIC(21,0) NOT NULL, 
	CCY_ID NUMERIC(21,0) NOT NULL, 
	POSN_EXT_KEY_ID NUMERIC(21,0) NOT NULL, 
	TRDR_ID NUMERIC(21,0), 
	SRC_SYS_ID NUMERIC(21,0) NOT NULL, 
	RGN_ID NUMERIC(21,0) NOT NULL, 
	TD_PL_POSN_INDIC_ID NUMERIC(21,0) NOT NULL, 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	PTD_FUNC_TRAN_TAX_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_FUNC_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_FUNC_LEAD_SPRD_AMT NUMERIC(31,8) DEFAULT 0, 
	LTD_FUNC_OCI_INV_AMT NUMERIC(31,8) DEFAULT 0, 
	LTD_FUNC_UAMRD_FEE_AMT NUMERIC(31,8) DEFAULT 0, 
	LTD_FUNC_UREL_PL_PREM_AMT NUMERIC(31,8) DEFAULT 0
   ) PARTITION BY COLUMN (PL_POSN_ID)
   COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1 ;

 
CREATE  TABLE TF_PL_ADJ_REPORT 
  (	TM_ID NUMERIC(21,0), 
	PL_POSN_ID NUMERIC(21,0), 
	RGN_ID NUMERIC(21,0), 
	DLY_USD_SD_FIN_INCM_EXPN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_DIV_INCM_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_REV_SHR_INT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_REV_OFS_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_PRIN_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_FLR_BRKG_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_AGY_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_CPS_INST_AGY_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_REV_SHR_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_RTL_SC_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_MIDMKT_SC_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_IIG_SC_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_RTL_CMSN_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_MIDMKT_CMSN_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_IIG_CMSN_RBT_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_FX_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_OCI_ACRTN_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_IMPRMT_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	DLY_USD_PYDN_RLZD_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_POSN_PL_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_TRD_FEE_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_CUM_MARKDOWN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_GL_RLZD_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SYND_RLZD_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_MGT_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_UNDWR_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_PRCPM_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SELL_CNCES_POT_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SELL_CNCES_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_INVT_BANK_SHR_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_OTH_GL_REV_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_GL_REV_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_LEAD_MGT_CSHFL_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_HDGE_ALOC_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_DEAL_EXPN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_OVRSL_EXPN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_LGL_RSRVE_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_TRD_SELL_CNCES_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_REV_TRF_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_AGED_RSRVE_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_MBDDO_CMSN_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_EXPN_RSRVE_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SELL_CNCES_POT2_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SELL_CNCES_POT3_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_SELL_CNCES_POT4_AMT NUMERIC(31,8) DEFAULT 0, 
	PTD_CPS_REV_TRD_AMT NUMERIC(31,8) DEFAULT 0,
	PTD_DIV_INCM_AMT NUMERIC(31,8) DEFAULT 0,
	ERR_ID NUMERIC(21,0), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	PTD_FUNC_UREL_PL_AMT NUMERIC(31,8) DEFAULT 0,
	PTD_FUNC_UREL_PL_FX_AMT NUMERIC(31,8) DEFAULT 0,
	PTD_FUNC_UREL_PL_PREM_AMT NUMERIC(31,8) DEFAULT 0,
	UREL_DISP_FAC NUMERIC(1,0) DEFAULT 1, 
	UREL_CALC_FAC NUMERIC(1,0) DEFAULT 1
   ) PARTITION BY COLUMN (PL_POSN_ID)
   COLOCATE WITH (TX_PL_POSITION) REDUNDANCY 1;

CREATE TABLE TD_TRADER_SCD 
  (	TRDR_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	CCY_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_MNEM_CD VARCHAR(16) NOT NULL, 
	CCY_CD VARCHAR(3), 
	ORIG_FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_NO VARCHAR(8), 
	SUB_MICRO_ID NUMERIC(21,0) NOT NULL, 
	SUB_MICRO_CD VARCHAR(7), 
	STGY_ID NUMERIC(21,0) NOT NULL, 
	STGY_CD VARCHAR(3), 
	LE_ID NUMERIC(21,0) NOT NULL, 
	LE_CD VARCHAR(3), 
	LE_MNEM_CD VARCHAR(20), 
	COM_FIRM_ACCT_MNEM_CD VARCHAR(16),
	HOLDING_CORP_CD VARCHAR(1) DEFAULT '?'
   ) REPLICATE;

CREATE TABLE TD_POSN_EXTENDED_KEY 
  (	POSN_EXT_KEY_ID NUMERIC(21,0) NOT NULL, 
	LNG_SHRT_ID NUMERIC(21,0) NOT NULL, 
	LNG_SHRT_CD VARCHAR(1) NOT NULL, 
	LNG_SHRT_DESC VARCHAR(30), 
	BRKR_ID NUMERIC(21,0) NOT NULL, 
	BRKR_CD VARCHAR(2) NOT NULL, 
	BRKR_DESC VARCHAR(30), 
	REGIS_COUP_ID NUMERIC(21,0) NOT NULL, 
	REGIS_COUP_CD VARCHAR(1) NOT NULL, 
	RGST_COUP_DESC VARCHAR(30), 
	SUB_ACCT_ID NUMERIC(21,0) NOT NULL, 
	SUB_ACCT_CD VARCHAR(1) NOT NULL, 
	CORPUS_ID NUMERIC(5,0) NOT NULL, 
	TRAN_TYP_CD VARCHAR(30) NOT NULL, 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(16,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	TRAN_TYP_DESC VARCHAR(40), 
	SUB_ACCT_DESC VARCHAR(40)
   ) REPLICATE ;

CREATE TABLE TD_PL_POSITION_INDICATIVE 
  (	TD_PL_POSN_INDIC_ID NUMERIC(21,0) NOT NULL, 
	CTP_ACCT VARCHAR(8), 
	CTP_LE_CD VARCHAR(3), 
	CTP_NM VARCHAR(30), 
	PAY_SIDE_NOTNL_CCY_CD VARCHAR(3), 
	RECV_SIDE_NOTNL_CCY_CD VARCHAR(3), 
	RAP_NOTNL_CCY_CD VARCHAR(3), 
	DEF_SWAP_REF_ENTY VARCHAR(255), 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	CUST_NM VARCHAR(255), 
	GFCID_CD VARCHAR(15), 
	SIC_CD VARCHAR(20), 
	CTP_CONDI_CD VARCHAR(15), 
	QMEMO_PROD_CD VARCHAR(15), 
	QMEMO_PROD_DESC VARCHAR(255), 
	TRD_STATUS_IND_CD VARCHAR(15)
   ) REPLICATE ;

CREATE TABLE TD_INSTRUMENT_SCD 
  (	INSM_ID NUMERIC(21,0) NOT NULL, 
	STRT_EFF_DT DATE, 
	END_EFF_DT DATE, 
	CURR_IND NUMERIC(1,0) NOT NULL, 
	SCR_FI_CD NUMERIC(21,0) NOT NULL, 
	CUSIP_CD VARCHAR(30) NOT NULL, 
	CUSIP_SRC_CD VARCHAR(10) NOT NULL, 
	CUSIP_DESC VARCHAR(50) NOT NULL, 
	UNDL_CUSIP_CD VARCHAR(30), 
	INSM_MAT_DT DATE, 
	COUP_RT NUMERIC(31,19), 
	UNIT_OF_PRC NUMERIC(31,8), 
	UNIT_OF_TRD NUMERIC(31,8), 
	CURR_RT NUMERIC(31,19), 
	NO_OF_CON_RT NUMERIC(31,19), 
	STRK_PRC NUMERIC(31,8), 
	FIT_CD VARCHAR(3), 
	FIT_DESC VARCHAR(42), 
	GCT_CD VARCHAR(5), 
	GCT_DESC VARCHAR(255), 
	PUT_CALL_IND VARCHAR(1), 
	SCR_NO_CD VARCHAR(30) NOT NULL, 
	SCR_IND_CD VARCHAR(7), 
	SCR_TYP_CD VARCHAR(10), 
	SCR_TYP_DESC VARCHAR(42), 
	SCR_SUB_TYP_CD VARCHAR(10), 
	SCR_TICKR_CD VARCHAR(40), 
	SCR_OFFR_CD VARCHAR(1), 
	SCR_CLAS_DESC VARCHAR(42), 
	BNCHMARK_CUSIP_CD VARCHAR(30), 
	BNCHMARK_DESC VARCHAR(50), 
	BNCHMARK_MAT_DT DATE, 
	BNCHMARK_SPRD_AMT NUMERIC(31,8), 
	PROD_CLAS_CD VARCHAR(30), 
	QUICK_CD VARCHAR(9), 
	CDS_PROD_CD VARCHAR(10), 
	LON_PROD_CD VARCHAR(3), 
	TRESTEL_PROD_CD VARCHAR(4), 
	EXPR_DT DATE, 
	CUSIP_DEAL_TRAN_CD VARCHAR(30), 
	TRAN_ID NUMERIC(21,0) NOT NULL, 
	DEAL_CD VARCHAR(30) NOT NULL, 
	CORPUS_ID NUMERIC(21,0) NOT NULL, 
	OTC_CUSIP_CD VARCHAR(30), 
	REC_STA_CD VARCHAR(1), 
	REC_MDFY_USER_ID VARCHAR(16), 
	REC_MDFY_DTM TIMESTAMP, 
	REC_MDFY_METH_DESC VARCHAR(30), 
	PROC_LOG_ID NUMERIC(21,0) NOT NULL, 
	ERR_ID NUMERIC(21,0) NOT NULL, 
	CON_CD VARCHAR(6), 
	VER_NO NUMERIC(21,0), 
	EXCH_CD VARCHAR(6), 
	GEO_CLAS_CD VARCHAR(8), 
	GEO_CLAS_DESC VARCHAR(35), 
	POOL_NO VARCHAR(16), 
	MDY_RTNG VARCHAR(8), 
	SNP_RTNG VARCHAR(8), 
	SCR_OFFR_DESC VARCHAR(42), 
	CCY_CD VARCHAR(3) DEFAULT 'N/A', 
	RIC_CD VARCHAR(40) DEFAULT 'N/A', 
	ISIN_CD VARCHAR(40) DEFAULT 'N/A', 
	OCC_CD VARCHAR(40) DEFAULT 'N/A', 
	ISS_ISIN_CD VARCHAR(40) DEFAULT 'N/A', 
	MSD_CUSIP_CD VARCHAR(40) DEFAULT 'N/A', 
	SEDOL_CD VARCHAR(40) DEFAULT 'N/A', 
	MSD_TAX_CD VARCHAR(8) DEFAULT 'N/A' 

   ) REPLICATE ;

CREATE TABLE TD_FIRM_ACCOUNT_SCD 
  (	FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_MNEM_CD VARCHAR(16), 
	STRT_EFF_DT DATE, 
	END_EFF_DT DATE, 
	CURR_IND NUMERIC(1,0), 
	ORIG_FIRM_ACCT_ID NUMERIC(21,0) NOT NULL, 
	FIRM_ACCT_NO VARCHAR(8), 
	FIRM_ACCT_DESC VARCHAR(30), 
	FIRM_ACCT_TYP_CD VARCHAR(1), 
	FIRM_ACCT_SUB_TYP_CD VARCHAR(1), 
	SUPER_BSUNIT_ID NUMERIC(21,0) NOT NULL, 
	STGY_ID NUMERIC(21,0) NOT NULL, 
	STGY_CD VARCHAR(3), 
	STGY_NM VARCHAR(30), 
	LE_ID NUMERIC(21,0) NOT NULL, 
	EXPN_CD VARCHAR(8), 
	CONDI_ID NUMERIC(21,0) NOT NULL, 
	CONDI_CD VARCHAR(10), 
	PROF_CTR_ID NUMERIC(21,0) NOT NULL, 
	TMS_FIRM_ACCT_CKDG VARCHAR(1) DEFAULT '?', 
	GOC_RGN_CD VARCHAR(10) DEFAULT 'N/A', 
	GOC_RGN_DESC VARCHAR(60) DEFAULT 'N/A', 
	HOLDING_CORP_CD VARCHAR(1) DEFAULT '?'
   ) REPLICATE;


   CREATE VIEW VD_TRADER_SCD AS
   SELECT
     FIRM_ACCT_ID,
     CCY_ID,
     COM_FIRM_ACCT_MNEM_CD FIRM_ACCT_MNEM_CD,
     CCY_CD,
     LE_MNEM_CD,
     SUB_MICRO_ID,
     SUB_MICRO_CD,
     STGY_CD,

     CASE WHEN
       CASE WHEN LE_CD = 'N/A' THEN '' WHEN LE_CD is NULL THEN '' ELSE LE_CD END || CASE WHEN SUB_MICRO_CD = 'N/A' THEN '' WHEN SUB_MICRO_CD is NULL THEN '' ELSE SUB_MICRO_CD END = '' THEN 'N/A'
       ELSE CASE WHEN LE_CD = 'N/A' THEN '' WHEN LE_CD is NULL THEN '' ELSE LE_CD END || CASE WHEN SUB_MICRO_CD = 'N/A' THEN '' WHEN SUB_MICRO_CD is NULL THEN '' ELSE SUB_MICRO_CD END 
     END HYPERION_CD,
     HOLDING_CORP_CD
   FROM TD_TRADER_SCD;


   CREATE VIEW VD_POSN_EXTENDED_KEY AS 
   SELECT
     POSN_EXT_KEY_ID,
     LNG_SHRT_CD,
     LNG_SHRT_DESC,
     BRKR_CD,
     BRKR_DESC,
     REGIS_COUP_CD,
     RGST_COUP_DESC,
     SUB_ACCT_CD,
     CASE WHEN CORPUS_ID = -1 THEN NULL ELSE CORPUS_ID END CORPUS_ID,
     CASE WHEN TRAN_TYP_CD = 'NA' THEN NULL ELSE TRAN_TYP_CD END TRAN_TYP_CD,
     TRAN_TYP_DESC,
     SUB_ACCT_DESC
   FROM TD_POSN_EXTENDED_KEY;


   CREATE VIEW VF_PL_POSITION_PTD_BASE  AS 
   SELECT
     TM_ID,
     PL_POSN_ID,
     FIRM_ACCT_ID,
     INSM_ID,
     CCY_ID,
     POSN_EXT_KEY_ID,
     SRC_SYS_ID,
     PTD_DIV_INCM_AMT,
     ERY_TRMT_DTM,
     LTD_OFS_TM_ID,
     NULLIF(AMORT_AMT, 0) as AMORT_AMT,
     CASE WHEN IMPRMT_IND = 1 THEN 'Y' ELSE 'N' END IMPRMT_IND
   FROM TF_PL_POSITION_PTD P;


   CREATE VIEW VF_PL_POSITION_PTD_CALC  AS 
   SELECT
     TM_ID,
     PL_POSN_ID
   FROM VF_PL_POSITION_PTD_BASE P;


   CREATE VIEW VF_PL_POSITION_PTD AS
   SELECT 
     P.TM_ID,
     P.PL_POSN_ID,
     FIRM_ACCT_ID,
     INSM_ID,
     SRC_SYS_ID,
     POSN_EXT_KEY_ID,
     PTD_DIV_INCM_AMT,
     CASE WHEN ERY_TRMT_DTM IS NULL
       THEN ''
       WHEN CHAR(ERY_TRMT_DTM)='1900-01-01'
       THEN ''
       ELSE CASE WHEN SIGN(INTEGER(CHAR(ERY_TRMT_DTM))-P.TM_ID) = 1 THEN 'Active' ELSE 'Terminated' END
     END DEAL_STATUS
   FROM VF_PL_POSITION_PTD_BASE P, VF_PL_POSITION_PTD_CALC C
   WHERE P.TM_ID = C.TM_ID
   AND   P.PL_POSN_ID = C.PL_POSN_ID;


   CREATE VIEW VF_PL_POSITION_QTD_YTD_BASE AS
   SELECT 
     TM_ID,
     PL_POSN_ID,
     FIRM_ACCT_ID,
     CCY_ID,
     YTD_DIV_INCM_AMT,
     QTD_USD_SD_ACCRETION_INV_AMT,
     QTD_USD_INV_AMT,
     QTD_CR_COST_WRTOFF_AMT,
     QTD_RTL_SC_AMT,
     QTD_MIDMKT_SC_AMT,
     QTD_IIG_SC_AMT,
     QTD_PRIN_CMSN_AMT,
     QTD_FLR_BRKG_CMSN_AMT,
     QTD_AGY_CMSN_AMT,
     QTD_CPS_INST_AGY_CMSN_AMT,
     QTD_REV_SHR_CMSN_AMT,
     YTD_INV_AMT,
     YTD_SD_ACCRETION_INV_AMT,
     YTD_GL_RLZD_AMT,
     YTD_UREL_PL_AMT,
     YTD_UREL_PL_FX_AMT,
     YTD_UREL_PL_PREM_AMT,
     NULLIF(YTD_FUNC_SELL_CNCES_POT2_AMT, 0) as YTD_FUNC_SELL_CNCES_POT2_AMT,
     NULLIF(UREL_DISP_FAC,1) UREL_DISP_FAC
   FROM TF_PL_POSITION_YTD;


   CREATE VIEW VF_PL_POSITION_QTD AS
   SELECT 
     TM_ID,
     PL_POSN_ID,
     (QTD_USD_INV_AMT + QTD_USD_SD_ACCRETION_INV_AMT) QTD_USD_INV_AMT,
     (QTD_CR_COST_WRTOFF_AMT + QTD_RTL_SC_AMT + QTD_MIDMKT_SC_AMT + QTD_IIG_SC_AMT) QTD_TOT_SC_AMT,
     (QTD_PRIN_CMSN_AMT + QTD_FLR_BRKG_CMSN_AMT + QTD_AGY_CMSN_AMT + QTD_CPS_INST_AGY_CMSN_AMT + QTD_REV_SHR_CMSN_AMT) QTD_TOT_INST_CMSN_AMT
   FROM VF_PL_POSITION_QTD_YTD_BASE P;


   CREATE VIEW VF_PL_POSITION_YTD AS
   SELECT 
     TM_ID,
     PL_POSN_ID,
     (YTD_INV_AMT + YTD_SD_ACCRETION_INV_AMT + YTD_UREL_PL_AMT + YTD_UREL_PL_PREM_AMT + YTD_UREL_PL_FX_AMT) YTD_FAIR_VAL_AMT,
     (YTD_INV_AMT + YTD_SD_ACCRETION_INV_AMT) YTD_INV_AMT
   FROM VF_PL_POSITION_QTD_YTD_BASE P;


   CREATE VIEW VF_PL_POSITION_QTD_YTD AS
   SELECT 
     P.TM_ID,
     P.PL_POSN_ID,
     FIRM_ACCT_ID,
     YTD_DIV_INCM_AMT,
     CCY_ID,
     Q.QTD_TOT_SC_AMT,
     Q.QTD_TOT_INST_CMSN_AMT,
     Y.YTD_FAIR_VAL_AMT
   FROM VF_PL_POSITION_QTD_YTD_BASE P, VF_PL_POSITION_QTD Q, VF_PL_POSITION_YTD Y 
   WHERE P.TM_ID = Q.TM_ID 
   AND P.PL_POSN_ID = Q.PL_POSN_ID 
   AND P.TM_ID = Y.TM_ID 
   AND P.PL_POSN_ID = Y.PL_POSN_ID;


   CREATE VIEW VF_PL_ADJUSTMENT_DLY AS
   SELECT 
     TM_ID,
     PL_POSN_ID,
     (DLY_USD_SD_FIN_INCM_EXPN_AMT + DLY_USD_DIV_INCM_AMT + DLY_USD_REV_SHR_INT_AMT + DLY_USD_REV_OFS_AMT + (DLY_USD_PRIN_CMSN_AMT + DLY_USD_FLR_BRKG_CMSN_AMT + DLY_USD_AGY_CMSN_AMT + DLY_USD_CPS_INST_AGY_CMSN_AMT + DLY_USD_REV_SHR_CMSN_AMT) + (DLY_USD_RTL_SC_RBT_AMT + DLY_USD_MIDMKT_SC_RBT_AMT + DLY_USD_IIG_SC_RBT_AMT + DLY_USD_RTL_CMSN_RBT_AMT + DLY_USD_MIDMKT_CMSN_RBT_AMT + DLY_USD_IIG_CMSN_RBT_AMT) + DLY_USD_FX_PL_AMT + DLY_USD_OCI_ACRTN_AMT + DLY_USD_IMPRMT_PL_AMT + DLY_USD_PYDN_RLZD_PL_AMT) DLY_USD_NET_ECON_PL_AMT
   FROM TF_PL_ADJ_REPORT P;


   CREATE VIEW VF_PL_ADJUSTMENT_PTD AS
   SELECT 
     TM_ID,
     PL_POSN_ID,
     ((PTD_POSN_PL_AMT         + PTD_TRD_FEE_AMT) + PTD_CUM_MARKDOWN_AMT + PTD_GL_RLZD_AMT + PTD_SYND_RLZD_AMT + (PTD_MGT_CMSN_AMT+PTD_UNDWR_CMSN_AMT+PTD_PRCPM_CMSN_AMT+ PTD_SELL_CNCES_POT_AMT+PTD_SELL_CNCES_CMSN_AMT+PTD_INVT_BANK_SHR_AMT+PTD_OTH_GL_REV_AMT+ PTD_GL_REV_AMT+PTD_LEAD_MGT_CSHFL_AMT+PTD_HDGE_ALOC_AMT+PTD_DEAL_EXPN_AMT+PTD_OVRSL_EXPN_AMT+ PTD_LGL_RSRVE_AMT+PTD_TRD_SELL_CNCES_AMT+PTD_REV_TRF_AMT+PTD_AGED_RSRVE_AMT+PTD_MBDDO_CMSN_AMT+ PTD_EXPN_RSRVE_AMT+PTD_SELL_CNCES_POT2_AMT+PTD_SELL_CNCES_POT3_AMT+PTD_SELL_CNCES_POT4_AMT) + PTD_CPS_REV_TRD_AMT) PTD_TOT_RLZD_AMT
   FROM TF_PL_ADJ_REPORT P;


   CREATE VIEW VF_PL_ADJUSTMENT AS
   SELECT 
     A.TM_ID,
     A.PL_POSN_ID,
     NULLIF(ERR_ID,0) ERR_ID,
     PTD_DIV_INCM_AMT,
     PTD_FUNC_UREL_PL_FX_AMT,
     PTD_FUNC_UREL_PL_PREM_AMT,
     D.DLY_USD_NET_ECON_PL_AMT,
     P.PTD_TOT_RLZD_AMT
   FROM TF_PL_ADJ_REPORT A, VF_PL_ADJUSTMENT_DLY D, VF_PL_ADJUSTMENT_PTD P
   WHERE A.TM_ID = D.TM_ID
   AND   A.PL_POSN_ID = D.PL_POSN_ID
   AND   A.TM_ID = P.TM_ID
   AND   A.PL_POSN_ID = P.PL_POSN_ID;



   CREATE VIEW VD_INSTRUMENT_SCD AS 
   SELECT INSM_ID,
     STRT_EFF_DT,
     END_EFF_DT,
     CURR_IND,
     SCR_FI_CD,
     CUSIP_CD,
     CUSIP_SRC_CD,
     UPPER(CUSIP_DESC) CUSIP_DESC,
     CASE
     WHEN UNDL_CUSIP_CD IS NULL THEN CUSIP_CD
     ELSE NULLIF(UNDL_CUSIP_CD, 'N/A')
     END UNDL_CUSIP_CD,
     NULLIF(CASE WHEN INSM_MAT_DT = DATE('1970-01-01') THEN NULL WHEN INSM_MAT_DT = DATE('1900-01-01') THEN NULL ELSE INSM_MAT_DT END, DATE(1)) INSM_MAT_DT,
     COUP_RT,
     UNIT_OF_PRC,
     UNIT_OF_TRD,
     CURR_RT,
     NO_OF_CON_RT,
     STRK_PRC,
     FIT_CD,
     FIT_DESC,
     GCT_CD,
     GCT_DESC,
     PUT_CALL_IND,
     SCR_NO_CD,
     SCR_IND_CD,
     SCR_TYP_CD,
     SCR_TYP_DESC,
     SCR_SUB_TYP_CD,
     SCR_TICKR_CD,
     SCR_OFFR_CD,
     SCR_CLAS_DESC,
     BNCHMARK_CUSIP_CD,
     BNCHMARK_DESC,
     BNCHMARK_MAT_DT,
     BNCHMARK_SPRD_AMT,
     UPPER(PROD_CLAS_CD) PROD_CLAS_CD,
     QUICK_CD,
     CDS_PROD_CD,
     LON_PROD_CD,
     TRESTEL_PROD_CD,
     EXPR_DT,
     UPPER(CUSIP_DEAL_TRAN_CD) CUSIP_DEAL_TRAN_CD,
     CASE WHEN CUSIP_DEAL_TRAN_CD = 'OASYS' THEN TRAN_ID ELSE NULL END TRAN_ID,
     UPPER(DEAL_CD) DEAL_CD,
     CASE WHEN CUSIP_SRC_CD = 'OASYS' THEN CORPUS_ID ELSE NULL END CORPUS_ID,
     OTC_CUSIP_CD,
     REC_STA_CD,
     REC_MDFY_USER_ID,
     REC_MDFY_DTM,
     REC_MDFY_METH_DESC,
     PROC_LOG_ID,
     ERR_ID,
     UNIT_OF_PRC * UNIT_OF_TRD * NO_OF_CON_RT PRC_FAC,
     CON_CD,
     VER_NO,
     EXCH_CD,
     GEO_CLAS_CD,
     GEO_CLAS_DESC,
     POOL_NO,
     MDY_RTNG,
     SNP_RTNG,
     SCR_OFFR_DESC,
     CCY_CD,
     RIC_CD,
     ISIN_CD,
     OCC_CD,
     ISS_ISIN_CD,
     MSD_CUSIP_CD,
     SEDOL_CD,
     MSD_TAX_CD
   FROM TD_INSTRUMENT_SCD;

