gfxdperf.tpch.TPCHPrms-indexes = 
  "CREATE INDEX q2_index1 ON partSupp (ps_partKey)"
  "CREATE INDEX q2_index2 ON partsupp (ps_suppkey)"
  "CREATE INDEX q2_index3 ON partsupp (ps_supplycost)"
  "CREATE INDEX q2_index4 ON part (p_partKey)"
  "CREATE INDEX q2_index5 ON part (p_size)"
  "CREATE INDEX q2_index6 ON part (p_type)"
  "CREATE INDEX q2_index7 ON supplier (s_suppkey)"
  "CREATE INDEX q2_index8 ON supplier (s_nationkey)"
  "CREATE INDEX q2_index9 ON region (r_regionkey)"
  "CREATE INDEX q2_index10 ON region (r_name)"
  "CREATE INDEX q2_index11 ON nation (n_nationkey)"
  "CREATE INDEX q2_index12 ON nation (n_regionkey)"
;
