-- import
CALL SYSCS_UTIL.import_data_ex ('MIGRATIONS', 'CURRENT_VERSION_TMP', null, null, '/export/varuna1/sample_code/dat/CURRENT_VERSION.dat', ',',NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('MIGRATIONS', 'VERSION_HISTORY_TMP', null, null, '/export/varuna1/sample_code/dat/VERSION_HISTORY.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
-- CALL SYSCS_UTIL.import_data_ex ('MIGRATIONS', 'VERSION_HISTORY_LOG_TMP', null, null, '/export/varuna1/sample_code/dat/VERSION_HISTORY_LOG.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'STORE_TMP', null, null, '/export/varuna1/sample_code/dat/STORE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'MASTER_FEE_TMP', null, null, '/export/varuna1/sample_code/dat/MASTER_FEE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'MASTER_LENDER_TMP', null, null, '/export/varuna1/sample_code/dat/MASTER_LENDER.dat', ',' , NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'CUSTOMER_TMP', null, null, '/export/varuna1/sample_code/dat/CUSTOMER.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'QUOTE_VEHICLE_TMP', null, null, '/export/varuna1/sample_code/dat/QUOTE_VEHICLE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PENCIL_DEFAULT_SETTING_TMP', null, null, '/export/varuna1/sample_code/dat/PENCIL_DEFAULT_SETTING.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PENCIL_DEFAULT_TMP', null, null, '/export/varuna1/sample_code/dat/PENCIL_DEFAULT.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'CALC_DEFAULT_TMP', null, null, '/export/varuna1/sample_code/dat/CALC_DEFAULT.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
-- CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'LENDER_TMP', null, null, '/export/varuna1/sample_code/dat/LENDER.dat', ',' , NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PENCIL_TMP', null, null, '/export/varuna1/sample_code/dat/PENCIL.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
-- CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'QUOTE_TMP', null, null, '/export/varuna1/sample_code/dat/QUOTE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'MASTER_TYPE_TMP', null, null, '/export/varuna1/sample_code/dat/MASTER_TYPE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'ACCESSORY_TMP', null, null, '/export/varuna1/sample_code/dat/ACCESSORY.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'ADDRESS_TMP', null, null, '/export/varuna1/sample_code/dat/ADDRESS.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'INSURANCE_COMPANY_TMP', null, null, '/export/varuna1/sample_code/dat/INSURANCE_COMPANY.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'CONTACT_TMP', null, null, '/export/varuna1/sample_code/dat/CONTACT.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'ADMIN_FEE_TMP', null, null, '/export/varuna1/sample_code/dat/ADMIN_FEE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'BALLOON_INFO_TMP', null, null, '/export/varuna1/sample_code/dat/BALLOON_INFO.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'DEFERRED_PAYMENT_TMP', null, null, '/export/varuna1/sample_code/dat/DEFERRED_PAYMENT.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'EMAIL_TMP', null, null, '/export/varuna1/sample_code/dat/EMAIL.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PHONE_TMP', null, null, '/export/varuna1/sample_code/dat/PHONE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'FINANCE_INFO_TMP', null, null, '/export/varuna1/sample_code/dat/FINANCE_INFO.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'LEASE_INFO_TMP', null, null, '/export/varuna1/sample_code/dat/LEASE_INFO.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PENCIL_OPTION_TMP', null, null, '/export/varuna1/sample_code/dat/PENCIL_OPTION.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'PRODUCT_TMP', null, null, '/export/varuna1/sample_code/dat/PRODUCT.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'QUOTE_FEE_TMP', null, null, '/export/varuna1/sample_code/dat/QUOTE_FEE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'QUOTE_LEAD_TMP', null, null, '/export/varuna1/sample_code/dat/QUOTE_LEAD.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
-- CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'REBATE_TMP', null, null, '/export/varuna1/sample_code/dat/REBATE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'SALES_PERSON_TMP', null, null, '/export/varuna1/sample_code/dat/SALES_PERSON.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'TERM_RATE_TMP', null, null, '/export/varuna1/sample_code/dat/TERM_RATE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('QUOTING', 'NOTE_TMP', null, null, '/export/varuna1/sample_code/dat/NOTE.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
CALL SYSCS_UTIL.import_data_ex ('TAXES', 'TAXRATES_TMP', null, null, '/export/varuna1/sample_code/dat/TAXRATES.dat', ',', NULL, NULL, 0, 0, 6, 0, null, null);
