-- export
CALL SYSCS_UTIL.EXPORT_TABLE ('MIGRATIONS', 'CURRENT_VERSION', '/export/varuna1/sample_code/dat/CURRENT_VERSION.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('MIGRATIONS', 'VERSION_HISTORY', '/export/varuna1/sample_code/dat/VERSION_HISTORY.dat', null, null, null);
-- CALL SYSCS_UTIL.EXPORT_TABLE ('MIGRATIONS', 'VERSION_HISTORY_LOG', '/export/varuna1/sample_code/dat/VERSION_HISTORY_LOG.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'STORE', '/export/varuna1/sample_code/dat/STORE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'MASTER_FEE', '/export/varuna1/sample_code/dat/MASTER_FEE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'MASTER_LENDER', '/export/varuna1/sample_code/dat/MASTER_LENDER.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'CUSTOMER', '/export/varuna1/sample_code/dat/CUSTOMER.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'QUOTE_VEHICLE', '/export/varuna1/sample_code/dat/QUOTE_VEHICLE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PENCIL_DEFAULT_SETTING', '/export/varuna1/sample_code/dat/PENCIL_DEFAULT_SETTING.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PENCIL_DEFAULT', '/export/varuna1/sample_code/dat/PENCIL_DEFAULT.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'CALC_DEFAULT', '/export/varuna1/sample_code/dat/CALC_DEFAULT.dat', null, null, null);
-- CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'LENDER', '/export/varuna1/sample_code/dat/LENDER.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PENCIL', '/export/varuna1/sample_code/dat/PENCIL.dat', null, null, null);
-- CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'QUOTE', '/export/varuna1/sample_code/dat/QUOTE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'MASTER_TYPE', '/export/varuna1/sample_code/dat/MASTER_TYPE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'ACCESSORY', '/export/varuna1/sample_code/dat/ACCESSORY.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'ADDRESS', '/export/varuna1/sample_code/dat/ADDRESS.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'INSURANCE_COMPANY', '/export/varuna1/sample_code/dat/INSURANCE_COMPANY.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'CONTACT', '/export/varuna1/sample_code/dat/CONTACT.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'ADMIN_FEE', '/export/varuna1/sample_code/dat/ADMIN_FEE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'BALLOON_INFO', '/export/varuna1/sample_code/dat/BALLOON_INFO.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'DEFERRED_PAYMENT', '/export/varuna1/sample_code/dat/DEFERRED_PAYMENT.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'EMAIL', '/export/varuna1/sample_code/dat/EMAIL.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PHONE', '/export/varuna1/sample_code/dat/PHONE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'FINANCE_INFO', '/export/varuna1/sample_code/dat/FINANCE_INFO.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'LEASE_INFO', '/export/varuna1/sample_code/dat/LEASE_INFO.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PENCIL_OPTION', '/export/varuna1/sample_code/dat/PENCIL_OPTION.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'PRODUCT', '/export/varuna1/sample_code/dat/PRODUCT.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'QUOTE_FEE', '/export/varuna1/sample_code/dat/QUOTE_FEE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'QUOTE_LEAD', '/export/varuna1/sample_code/dat/QUOTE_LEAD.dat', null, null, null);
-- CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'REBATE', '/export/varuna1/sample_code/dat/REBATE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'SALES_PERSON', '/export/varuna1/sample_code/dat/SALES_PERSON.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'TERM_RATE', '/export/varuna1/sample_code/dat/TERM_RATE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('QUOTING', 'NOTE', '/export/varuna1/sample_code/dat/NOTE.dat', null, null, null);
CALL SYSCS_UTIL.EXPORT_TABLE ('TAXES', 'TAXRATES', '/export/varuna1/sample_code/dat/TAXRATES.dat', null, null, null);
