CREATE SCHEMA MIGRATIONS;

CREATE SCHEMA TAXES;

CREATE SCHEMA QUOTING;

CREATE TABLE MIGRATIONS.CURRENT_VERSION (
	
	VERSION INTEGER,
	
	FORCE_DOWNGRADE_VERSION INTEGER,
	
	DEFAULT_SCHEMA VARCHAR(255),
	
	SEED_DATA_EXECUTED SMALLINT

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE MIGRATIONS.VERSION_HISTORY (
	
	ID INTEGER,
	
	VERSION INTEGER,
	
	MIGRATION_TYPE VARCHAR(255),
	
	MIGRATION_STATUS VARCHAR(255),
	
	MIGRATED_ON TIMESTAMP,
	
	MIGRATED_BY VARCHAR(255),
	

	
	CONSTRAINT VERSION_HISTORY_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE MIGRATIONS.VERSION_HISTORY_LOG (
	
	ID INTEGER,
	
	VERSION_HISTORY_ID INTEGER,
	
	SCHEMA_NAME VARCHAR(255),
	
	OBJECT_NAME VARCHAR(255),
	
	SQL_STATEMENT VARCHAR(4000),
	
	ERROR_MESSAGE VARCHAR(4000),
	
	EXECUTED_ON TIMESTAMP,
	

	
	CONSTRAINT VERSION_HISTORY_LOG_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT VERSION_HISTORY_LOG_VERSION_HISTORY_ID_FK FOREIGN KEY (VERSION_HISTORY_ID) REFERENCES MIGRATIONS.VERSION_HISTORY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE QUOTING.STORE (
	
	ENTERPRISE_ID VARCHAR(8),
	
	ID VARCHAR(40),
	
	CMF_NUM INTEGER,
	
	IS_ADDRESS_NORMALIZED SMALLINT,
	
	FEDERAL_TAX_ID INTEGER,
	
	STATE_TAX_ID INTEGER,
	
	STATE_DMV_CODE VARCHAR(255),
	
	DMS_STORE_NUMBER VARCHAR(255),
	
	MANUFACTURER_CODE VARCHAR(255),
	
	MANUFACTURER_ID VARCHAR(255),
	
	SYSTEM_ID INTEGER,
	
	DEALER_ID INTEGER,
	
	APPLICATION_CODE VARCHAR(255),
	
	IS_EXPERIAN SMALLINT,
	
	IS_EQUIFAX SMALLINT,
	
	IS_TRANSUNION SMALLINT,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	IS_DEFAULT_STORE SMALLINT,
	
	NAME VARCHAR(255),
	
	CONTACT_NAME VARCHAR(255),
	
	PHONE VARCHAR(255),
	
	FAX VARCHAR(255),
	
	EMAIL VARCHAR(255),
	
	INVENTORY_OWNER VARCHAR(255),
	

	
	CONSTRAINT STORE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY PRIMARY KEY;

CREATE TABLE QUOTING.MASTER_FEE (
	
	ID INTEGER,
	
	STATE VARCHAR(255),
	
	FEE_TYPE VARCHAR(255),
	
	DISPLAY_NAME VARCHAR(255),
	
	IS_TAXABLE SMALLINT,
	
	IS_ACTIVE SMALLINT,
	
	IS_NEW SMALLINT,
	
	IS_USED SMALLINT,
	
	NEW_FIN_BAL_FEE DECIMAL(18, 5),
	
	USED_FIN_BAL_FEE DECIMAL(18, 5),
	
	NEW_LEASE_FEE DECIMAL(18, 5),
	
	USED_LEASE_FEE DECIMAL(18, 5),
	
	LEASE_APPLICATION INTEGER,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	

	
	CONSTRAINT MASTER_FEE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE QUOTING.MASTER_LENDER (
	
	ID INTEGER,
	
	NAME VARCHAR(255),
	
	CODE VARCHAR(255),
	
	DAYS_IN_YEAR INTEGER,
	
	STATUS SMALLINT,
	
	IS_FINANCE_ACTIVE SMALLINT,
	
	IS_LEASE_ACTIVE SMALLINT,
	
	IS_BALLOON_ACTIVE SMALLINT,
	
	LENDER_ADDRESS1 VARCHAR(255),
	
	LENDER_CITY VARCHAR(255),
	
	LENDER_STATE VARCHAR(255),
	
	LENDER_ZIP_CODE VARCHAR(255),
	
	LENDER_ZIPCODE_FOUR VARCHAR(255),
	

	
	CONSTRAINT MASTER_LENDER_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE QUOTING.CUSTOMER (
	
	ID INTEGER,
	
	DMS_ID VARCHAR(255),
	
	TYPE INTEGER,
	
	TITLE VARCHAR(255),
	
	FIRST_NAME VARCHAR(255),
	
	MIDDLE_NAME VARCHAR(255),
	
	LAST_NAME VARCHAR(255),
	
	SUFFIX VARCHAR(255),
	
	DATE_OF_BIRTH TIMESTAMP,
	
	SSN VARCHAR(255),
	
	GENDER VARCHAR(255),
	
	SAVE_WITHOUT_ADDRESS SMALLINT,
	
	COMPANY_NAME VARCHAR(255),
	
	DOING_BUSINESS_AS VARCHAR(255),
	
	FEDERAL_ID VARCHAR(255),
	
	DRIVERS_LICENSE_NUMBER VARCHAR(255),
	
	DRIVERS_LICENSE_STATE VARCHAR(255),
	
	DRIVERS_LICENSE_EXPIRATION_DATE TIMESTAMP,
	
	INSURANCE_POLICY_NUMBER VARCHAR(255),
	
	POLICY_EFFECTIVE_DATE TIMESTAMP,
	
	POLICY_EXPIRATION_DATE TIMESTAMP,
	
	COLLISION_DEDUCTIBLE DECIMAL(18, 5),
	
	COMPREHENSIVE_DEDUCTIBLE DECIMAL(18, 5),
	
	FIRE_THEFT_DEDUCTIBLE DECIMAL(18, 5),
	
	INSURANCE_COMPANY_ID INTEGER,
	
	INSURANCE_AGENT_NAME VARCHAR(255),
	
	INSURANCE_AGENT_PHONE VARCHAR(255),
	
	INSURANCE_VERIFIED_BY VARCHAR(255),
	
	INSURANCE_VERIFIED_DATE TIMESTAMP,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	ENCRYPTION_KEY_ID VARCHAR(255),
	
	LEAD_PROVIDER VARCHAR(255),
	
	LEAD_CONSUMER_ID BIGINT,
	
	DMS_CHECK_SUM VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT CUSTOMER_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.QUOTE_VEHICLE (
	
	ID INTEGER,
	
	STOCK_NUMBER VARCHAR(255),
	
	MODEL_YEAR INTEGER,
	
	MAKE VARCHAR(255),
	
	MODEL VARCHAR(255),
	
	MODEL_NUMBER VARCHAR(255),
	
	BODY_STYLE VARCHAR(255),
	
	TRIM_STYLE VARCHAR(255),
	
	TYPE VARCHAR(255),
	
	SELLING_PRICE DECIMAL(18, 5),
	
	INVOICE_PRICE DECIMAL(18, 5),
	
	MSRP DECIMAL(18, 5),
	
	EXTERIOR_COLOR VARCHAR(255),
	
	VIN VARCHAR(255),
	
	STATUS VARCHAR(255),
	
	ODOMETER INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT QUOTE_VEHICLE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PENCIL_DEFAULT_SETTING (
	
	ID INTEGER,
	
	PENCIL_DEFAULT_ID INTEGER,
	
	CASH_DOWN_OPTIONS BLOB,
	
	TERM_RATE_RESIDUAL_OPTIONS BLOB,
	
	QUOTE_TYPE INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PENCIL_DEFAULT_SETTING_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PENCIL_DEFAULT (
	
	ID INTEGER,
	
	HEADER_TEXT VARCHAR(255),
	
	CUSTOMER_ACCEPTANCE_TEXT VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PENCIL_DEFAULT_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.CALC_DEFAULT (
	
	ID INTEGER,
	
	TERM INTEGER,
	
	SELL_RATE DECIMAL(18, 5),
	
	DAYS_TO_FIRST_PAYMENT INTEGER,
	
	MILEAGE_PROGRAM INTEGER,
	
	RESIDUAL_PERCENTAGE DECIMAL(18, 5),
	
	LENDER_ID INTEGER,
	
	IS_RATE_TYPE_PERCENTAGE SMALLINT,
	
	RATE_MF DECIMAL(18, 5),
	
	QUOTE_TYPE SMALLINT,
	
	CASH_APPLICATION SMALLINT,
	
	TRADES_APPLICATION SMALLINT,
	
	REBATES_APPLICATION SMALLINT,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT CALC_DEFAULT_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.LENDER (
	
	ID INTEGER,
	
	NAME VARCHAR(255),
	
	CODE VARCHAR(255),
	
	DATA_ID VARCHAR(255),
	
	STATUS SMALLINT,
	
	IS_FINANCE_ACTIVE SMALLINT,
	
	IS_LEASE_ACTIVE SMALLINT,
	
	IS_BALLOON_ACTIVE SMALLINT,
	
	NUMBER_OF_DAYS_IN_YEAR INTEGER,
	
	FINANCE_INFO_ID INTEGER,
	
	LEASE_INFO_ID INTEGER,
	
	BALLOON_INFO_ID INTEGER,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT LENDER_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT LENDER_STORE_ID_FK FOREIGN KEY (STORE_ID) REFERENCES QUOTING.STORE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PENCIL (
	
	ID INTEGER,
	
	CALCULATED_AT_TIME TIMESTAMP,
	
	IS_TRADE_INCLUDED SMALLINT,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PENCIL_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.QUOTE (
	
	ID INTEGER,
	
	PENCIL_ID INTEGER,
	
	LEAD_ID VARCHAR(255),
	
	VENDOR_ID VARCHAR(15),
	
	QUOTE_NUMBER INTEGER,
	
	BUYER_ID INTEGER,
	
	CO_BUYER_ID INTEGER,
	
	HAS_CO_BUYER SMALLINT,
	
	SALES_PERSON_ID VARCHAR(255),
	
	LENDER_ID INTEGER,
	
	QUOTE_TYPE INTEGER,
	
	STATUS SMALLINT,
	
	MSRP DECIMAL(18, 5),
	
	RESIDUAL_PERCENT DECIMAL(18, 5),
	
	RESIDUAL_AMOUNT DECIMAL(18, 5),
	
	EXCESS_MILEAGE BLOB,
	
	MILEAGE_PROGRAM DECIMAL(18, 5),
	
	SELLING_PRICE DECIMAL(18, 5),
	
	TRADE_AMOUNT DECIMAL(18, 5),
	
	TOTAL_DEFERRED_PAYMENTS DECIMAL(18, 5),
	
	DEFERRED_PAYMENTS BLOB,
	
	DEPOSIT DECIMAL(18, 5),
	
	CASH DECIMAL(18, 5),
	
	CASH_CAP_REDUCTION DECIMAL(18, 5),
	
	APPLIED INTEGER,
	
	PAYOFF_AMOUNT DECIMAL(18, 5),
	
	LAH_PREMIUM DECIMAL(18, 5),
	
	FRONT_GROSS DECIMAL(18, 5),
	
	TERM INTEGER,
	
	RATE DECIMAL(18, 5),
	
	RATE_TYPE VARCHAR(2),
	
	PAYMENT DECIMAL(18, 5),
	
	DAYS_TO_FIRST_PAYMENT INTEGER,
	
	SALE_DATE DATE,
	
	FIRST_PAYMENT_DATE DATE,
	
	CREATE_DATE TIMESTAMP,
	
	TRADES BLOB,
	
	TAXES BLOB,
	
	ADJUSTMENTS BLOB,
	
	PERIODS_PER_YEAR INTEGER,
	
	NEW_PAYMENT DECIMAL(18, 5),
	
	RATE_PER_PERIOD DECIMAL(18, 5),
	
	AMOUNT_FINANCED DECIMAL(18, 5),
	
	AMOUNT_FINANCED_DISCLOSED_PRODUCTS DECIMAL(18, 5),
	
	BUY_RATE DECIMAL(18, 5),
	
	RATE_PER_PERIOD_BUY_RATE DECIMAL(18, 5),
	
	ODD_DAYS INTEGER,
	
	ODD_DAYS_INTEREST DECIMAL(18, 5),
	
	LAST_PAYMENT DECIMAL(18, 5),
	
	PAYMENT_WITHOUT_PRODUCTS DECIMAL(18, 5),
	
	TOTAL_PAYMENTS DECIMAL(18, 5),
	
	FINANCE_CHARGE DECIMAL(18, 5),
	
	TOTAL_DOWN_PAYMENT DECIMAL(18, 5),
	
	DEFERRED_PRICE DECIMAL(18, 5),
	
	CASH_PRICE DECIMAL(18, 5),
	
	FINANCE_RESERVE DECIMAL(18, 5),
	
	BACK_GROSS DECIMAL(18, 5),
	
	TOTAL_GROSS DECIMAL(18, 5),
	
	PRODUCT_GROSS DECIMAL(18, 5),
	
	LTV_PERCENT DECIMAL(18, 5),
	
	FEES BLOB,
	
	QUOTE_NOTES BLOB,
	
	PRODUCTS BLOB,
	
	REBATES BLOB,
	
	ACCESSORIES BLOB,
	
	QUOTE_VEHICLE_ID INTEGER,
	
	LEAD_CORELATION_ID BIGINT,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(50),
	
	CREATED_BY VARCHAR(50),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(50),
	
	CASH_LEASE_APPLICATION INTEGER,
	
	CASH_AS_CAP_RED DECIMAL(18, 5),
	
	CASH_AS_DRIVE_OFF DECIMAL(18, 5),
	
	TOTAL_AS_CAP_RED DECIMAL(18, 5),
	
	TOTAL_AS_DRIVE_OFF DECIMAL(18, 5),
	
	MONTHLY_DEPRECIATION DECIMAL(18, 5),
	
	LEASE_CHARGE DECIMAL(18, 5),
	
	BASE_PAYMENT DECIMAL(18, 5),
	
	MONTHLY_TAX DECIMAL(18, 5),
	
	CAP_RED_TAX DECIMAL(18, 5),
	
	CASH_CAP_RED DECIMAL(18, 5),
	
	DEPOSIT_AMOUNT DECIMAL(18, 5),
	
	INCEPTION_FEES_TOTAL DECIMAL(18, 5),
	
	DRIVE_OFF_TOTAL DECIMAL(18, 5),
	
	AMOUNT_DUE_AT_START DECIMAL(18, 5),
	
	WAIVE_PAYMENT SMALLINT,
	
	NO_OF_DEPOSITS INTEGER,
	
	PENCIL_STATUS SMALLINT,
	
	QUOTE_REQUEST_ID BIGINT,
	
	TOTAL_PAYMENT DECIMAL(18, 5),
	
	TOTAL_UPFRONT_FEES DECIMAL(18, 5),
	
	UPFRONT_ACC_FEE_PROD_TAX DECIMAL(18, 5),
	
	DEAL_NO VARCHAR(255),
	
	SENT_TO_STORE_ID VARCHAR(255),
	
	CHECK_SUM VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT QUOTE_PK PRIMARY KEY(ID, PENCIL_ID),
		

	
	CONSTRAINT QUOTE_STORE_ID_FK FOREIGN KEY (STORE_ID) REFERENCES QUOTING.STORE(ID),
		

	
	CONSTRAINT QUOTE_BUYER_ID_FK FOREIGN KEY (BUYER_ID) REFERENCES QUOTING.CUSTOMER(ID),
		

	
	CONSTRAINT QUOTE_CO_BUYER_ID_FK FOREIGN KEY (CO_BUYER_ID) REFERENCES QUOTING.CUSTOMER(ID),
		

	
	CONSTRAINT QUOTE_LENDER_ID_FK FOREIGN KEY (LENDER_ID) REFERENCES QUOTING.LENDER(ID),
		

	
	CONSTRAINT QUOTE_QUOTE_VEHICLE_ID_FK FOREIGN KEY (QUOTE_VEHICLE_ID) REFERENCES QUOTING.QUOTE_VEHICLE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.MASTER_TYPE (
	
	ID INTEGER,
	
	CATEGORY SMALLINT,
	
	TYPE VARCHAR(255),
	
	DESCRIPTION VARCHAR(255),
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	

	
	CONSTRAINT MASTER_TYPE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW;

CREATE TABLE QUOTING.ACCESSORY (
	
	ACCESSORY_TYPE VARCHAR(255),
	
	DISCLOSURE_TYPE VARCHAR(255),
	
	DESCRIPTION VARCHAR(255),
	
	IS_ACTIVE SMALLINT,
	
	IS_APPLIED_TO_ALL_QUOTES SMALLINT,
	
	IS_APPLIED_TO_NEW SMALLINT,
	
	IS_APPLIED_TO_USED SMALLINT,
	
	SELLING_AMOUNT DECIMAL(18, 5),
	
	LEASE_APPLICATION INTEGER,
	
	COST_AMOUNT DECIMAL(18, 5),
	
	IS_COST_AMT_LOCKED SMALLINT,
	
	RESIDUAL_AMOUNT DECIMAL(18, 5),
	
	IS_TAXABLE SMALLINT,
	
	IS_DMV SMALLINT,
	
	MAX_PRICE DECIMAL(18, 5),
	
	MAX_PROFIT_PERCENTAGE DECIMAL(18, 5),
	
	MAX_PROFIT_AMOUNT DECIMAL(18, 5),
	
	WE_OWE_CODE VARCHAR(255),
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	ID INTEGER,
	
	MASTER_TYPE_ID INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT ACCESSORY_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT ACCESSORY_MASTER_TYPE_ID_FK FOREIGN KEY (MASTER_TYPE_ID) REFERENCES QUOTING.MASTER_TYPE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.ADDRESS (
	
	ID INTEGER,
	
	REFERENCE_ID VARCHAR(50),
	
	REFERENCE_TYPE_ID INTEGER,
	
	ADDRESS_TYPE SMALLINT,
	
	ADDRESS1 VARCHAR(255),
	
	ADDRESS2 VARCHAR(255),
	
	CITY VARCHAR(255),
	
	STATE VARCHAR(255),
	
	ZIP_CODE VARCHAR(255),
	
	ZIP_CODE_FOUR VARCHAR(255),
	
	COUNTY VARCHAR(255),
	
	COUNTRY VARCHAR(255),
	
	NORMALIZATION_STATUS SMALLINT,
	
	IS_PRIMARY SMALLINT,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT ADDRESS_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.INSURANCE_COMPANY (
	
	ID INTEGER,
	
	COMPANY_NAME VARCHAR(255),
	
	PHONE VARCHAR(255),
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT INSURANCE_COMPANY_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.CONTACT (
	
	ID INTEGER,
	
	NAME VARCHAR(255),
	
	CONTACT_NAME VARCHAR(255),
	
	PHONE VARCHAR(255),
	
	FAX VARCHAR(255),
	
	EMAIL VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT CONTACT_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.ADMIN_FEE (
	
	FEE_TYPE VARCHAR(255),
	
	DISPLAY_NAME VARCHAR(255),
	
	IS_ACTIVE SMALLINT,
	
	IS_USED SMALLINT,
	
	IS_NEW SMALLINT,
	
	NEW_FIN_BAL_FEE DECIMAL(18, 5),
	
	USED_FIN_BAL_FEE DECIMAL(18, 5),
	
	NEW_LEASE_FEE DECIMAL(18, 5),
	
	USED_LEASE_FEE DECIMAL(18, 5),
	
	IS_TAXABLE SMALLINT,
	
	DISCLOSURE_TYPE VARCHAR(255),
	
	LEASE_APPLICATION INTEGER,
	
	CREATED_DATE TIMESTAMP,
	
	CREATED_BY VARCHAR(255),
	
	USER_ID VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	ID INTEGER,
	
	MASTER_TYPE_ID INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT ADMIN_FEE_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT ADMIN_FEE_MASTER_TYPE_ID_FK FOREIGN KEY (MASTER_TYPE_ID) REFERENCES QUOTING.MASTER_TYPE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.BALLOON_INFO (
	
	ID INTEGER,
	
	LENDER_CONTACT_ID INTEGER,
	
	LIEN_HOLDER_CONTACT_ID INTEGER,
	
	LOSS_PAYEE_CONTACT_ID INTEGER,
	
	IS_RESIDUAL_PERCENTAGE_ACTIVE SMALLINT,
	
	RESERVE_PARTICIPATION_PERCENTAGE DECIMAL(18, 5),
	
	FORMULA_TYPE INTEGER,
	
	DMV_ELT_CODE VARCHAR(255),
	
	DMS_LENDER_CODE VARCHAR(255),
	
	CUSTOM_FORMULA VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT BALLOON_INFO_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.DEFERRED_PAYMENT (
	
	ID INTEGER,
	
	DAYS INTEGER,
	
	DATE DATE,
	
	AMOUNT DECIMAL(18, 5),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT DEFERRED_PAYMENT_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.EMAIL (
	
	ID INTEGER,
	
	REFERENCE_ID VARCHAR(50),
	
	REFERENCE_TYPE_ID INTEGER,
	
	EMAIL_ID VARCHAR(255),
	
	TYPE SMALLINT,
	
	IS_PRIMARY SMALLINT,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT EMAIL_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PHONE (
	
	ID INTEGER,
	
	REFERENCE_ID VARCHAR(50),
	
	REFERENCE_TYPE_ID INTEGER,
	
	NUMBER VARCHAR(255),
	
	TYPE SMALLINT,
	
	IS_PRIMARY SMALLINT,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PHONE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.FINANCE_INFO (
	
	ID INTEGER,
	
	LENDER_CONTACT_ID INTEGER,
	
	LIEN_HOLDER_CONTACT_ID INTEGER,
	
	LOSS_PAYEE_CONTACT_ID INTEGER,
	
	RESERVE_PARTICIPATION_PERCENTAGE DECIMAL(18, 5),
	
	FORMULA_TYPE INTEGER,
	
	DMV_ELT_CODE VARCHAR(255),
	
	DMS_LENDER_CODE VARCHAR(255),
	
	CUSTOM_FORMULA VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT FINANCE_INFO_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.LEASE_INFO (
	
	ID INTEGER,
	
	LENDER_CONTACT_ID INTEGER,
	
	LIEN_HOLDER_CONTACT_ID INTEGER,
	
	LOSS_PAYEE_CONTACT_ID INTEGER,
	
	LAST_PAYMENT_DAY_OF_MONTH INTEGER,
	
	IS_RESIDUAL_PERCENTAGE_ACTIVE SMALLINT,
	
	IS_RATE_TYPE_PERCENTAGE SMALLINT,
	
	RESERVE_PARTICIPATION_PERCENTAGE DECIMAL(18, 5),
	
	FORMULA_TYPE INTEGER,
	
	DMV_ELT_CODE VARCHAR(255),
	
	DMS_LENDER_CODE VARCHAR(255),
	
	CUSTOM_FORMULA VARCHAR(255),
	
	FEE_TYPE VARCHAR(255),
	
	FEE_DESCRIPTION VARCHAR(255),
	
	IS_TAXABLE SMALLINT,
	
	BASE_ACQ_FEE DECIMAL(18, 5),
	
	MAX_ACQ_FEE DECIMAL(18, 5),
	
	LEASE_APPLICATION INTEGER,
	
	PURCHASE_OPTION_FEE DECIMAL(18, 5),
	
	DEPOSIT_ROUNDING_AMOUNT DECIMAL(18, 5),
	
	DISPOSITION_FEE DECIMAL(18, 5),
	
	PURCHASED_MILEAGE_RATE DECIMAL(18, 5),
	
	EXCESS_MILEAGE_PENALTY_RATE DECIMAL(18, 5),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT LEASE_INFO_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PENCIL_OPTION (
	
	ID INTEGER,
	
	PENCIL_ID INTEGER,
	
	QUOTE_TYPE INTEGER,
	
	LENDER BLOB,
	
	TERM_RATE_RESIDUAL_OPTIONS BLOB,
	
	CASH_DOWN_OPTIONS BLOB,
	
	PAYMENT_OPTIONS BLOB,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PENCIL_OPTION_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT PENCIL_OPTION_PENCIL_ID_FK FOREIGN KEY (PENCIL_ID) REFERENCES QUOTING.PENCIL(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.PRODUCT (
	
	ID INTEGER,
	
	PRODUCT_TYPE VARCHAR(255),
	
	DISCLOSURE_TYPE VARCHAR(255),
	
	DESCRIPTION VARCHAR(255),
	
	STATUS SMALLINT,
	
	IS_ACTIVE SMALLINT,
	
	APPLIES_TO_USED SMALLINT,
	
	APPLIES_TO_NEW SMALLINT,
	
	IS_APPLIED_TO_ALL_QUOTES SMALLINT,
	
	TERM INTEGER,
	
	MILEAGE_LIMIT DECIMAL(18, 5),
	
	DEDUCTIBLE_AMOUNT DECIMAL(18, 5),
	
	SELLING_AMOUNT DECIMAL(18, 5),
	
	COST_AMOUNT DECIMAL(18, 5),
	
	IS_COST_AMOUNT_LOCKED SMALLINT,
	
	IS_TAXABLE SMALLINT,
	
	LEASE_APPLICATION INTEGER,
	
	MAX_PRICE DECIMAL(18, 5),
	
	MAX_PROFIT_PERCENTAGE DECIMAL(18, 5),
	
	MAX_PROFIT_AMOUNT DECIMAL(18, 5),
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	IS_DMV SMALLINT,
	
	MASTER_TYPE_ID INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT PRODUCT_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT PRODUCT_MASTER_TYPE_ID_FK FOREIGN KEY (MASTER_TYPE_ID) REFERENCES QUOTING.MASTER_TYPE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.QUOTE_FEE (
	
	ID INTEGER,
	
	FEE_TYPE VARCHAR(255),
	
	FEE_DISPLAY_NAME VARCHAR(255),
	
	FEE_AMOUNT DECIMAL(18, 5),
	
	IS_TAXABLE SMALLINT,
	
	LEASE_APPLICATION INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT QUOTE_FEE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.QUOTE_LEAD (
	
	ID INTEGER,
	
	QUOTE_TYPE INTEGER,
	
	QUOTE_NOTE VARCHAR(255),
	
	VENDOR_ID VARCHAR(255),
	
	ENTERPRISE_ID BIGINT,
	
	LEAD_CORELATION_ID BIGINT,
	
	DEALER_ID BIGINT,
	
	CUSTOMER_ID INTEGER,
	
	SALES_PERSON_ID VARCHAR(255),
	
	STATUS INTEGER,
	
	QUOTE_REQUEST_ID BIGINT,
	
	TRADE_INS BLOB,
	
	VEHICLE BLOB,
	
	USER_ID VARCHAR(50),
	
	CREATED_DATE TIMESTAMP,
	
	CREATED_BY VARCHAR(50),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(50),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT QUOTE_LEAD_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.REBATE (
	
	ID INTEGER,
	
	CODE VARCHAR(255),
	
	DESCRIPTION VARCHAR(255),
	
	REBATE_TYPE VARCHAR(255),
	
	IS_ACTIVE SMALLINT,
	
	AMOUNT DECIMAL(18, 5),
	
	LEASE_APPLICATION INTEGER,
	
	CREATED_DATE TIMESTAMP,
	
	USER_ID VARCHAR(255),
	
	CREATED_BY VARCHAR(255),
	
	LAST_MODIFIED_DATE TIMESTAMP,
	
	LAST_MODIFIED_BY VARCHAR(255),
	
	MASTER_TYPE_ID INTEGER,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT REBATE_PK PRIMARY KEY(ID),
		

	
	CONSTRAINT REBATE_MASTER_TYPE_ID_FK FOREIGN KEY (MASTER_TYPE_ID) REFERENCES QUOTING.MASTER_TYPE(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.SALES_PERSON (
	
	ID VARCHAR(255),
	
	ENTERPRISE_ID VARCHAR(255),
	
	NAME VARCHAR(255),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT SALES_PERSON_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.TERM_RATE (
	
	ID INTEGER,
	
	PENCIL_DEFAULT_ID INTEGER,
	
	TERM INTEGER,
	
	SELL_RATE DECIMAL(18, 5),
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT TERM_RATE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE QUOTING.NOTE (
	
	ID INTEGER,
	
	REFERENCE_ID VARCHAR(50),
	
	REFERENCE_TYPE_ID INTEGER,
	
	NOTE_TEXT VARCHAR(255),
	
	USER_NAME VARCHAR(255),
	
	CREATED_DATE TIMESTAMP,
	
	STORE_ID VARCHAR(40) NOT NULL,
	

	
	CONSTRAINT NOTE_PK PRIMARY KEY(ID)

	
)
	
	PERSISTENT ASYNCHRONOUS
	
	EVICTION BY LRUHEAPPERCENT EVICTACTION OVERFLOW
	
	REDUNDANCY 1
	
	RECOVERYDELAY 5000
	
	PARTITION BY COLUMN (STORE_ID)
	
	COLOCATE WITH (QUOTING.STORE);

CREATE TABLE TAXES.TAXRATES
(
	ZIP_CODE INTEGER,
	PLUS_4_LOW INTEGER,
	PLUS_4_HIGH INTEGER,
	HAS_PLUS_4 INTEGER,
	STATE_ABBREV CHAR(2),
	COUNTY_NAME VARCHAR(150),
	CITY_NAME VARCHAR(150),
	STATE_SALES_TAX DECIMAL(13,6),	
	COUNTY_SALES_TAX DECIMAL(13,6),	
	CITY_SALES_TAX DECIMAL(13,6),	
	MTA_SALES_TAX DECIMAL(13,6),	
	SPD_SALES_TAX DECIMAL(13,6),	
	OTHER1_SALES_TAX DECIMAL(13,6),	
	OTHER2_SALES_TAX DECIMAL(13,6),	
	OTHER3_SALES_TAX DECIMAL(13,6),	
	OTHER4_SALES_TAX DECIMAL(13,6),	
	TOTAL_SALES_TAX DECIMAL(13,6),	
	COUNTY_CODE VARCHAR(10),
	CITY_CODE VARCHAR(100),
	MTA_NAME VARCHAR(150),	
	SPD_NAME VARCHAR(150),	
	OTHER1_NAME VARCHAR(150),	
	OTHER2_NAME VARCHAR(150),	
	OTHER3_NAME VARCHAR(150),	
	OTHER4_NAME VARCHAR(150),		
	FIPS_GEOCODE CHAR(10),	
	COUNTY_TAXABLE_MAX DECIMAL(13,6),	
	CITY_TAXABLE_MAX DECIMAL(13,6),	
CONSTRAINT TAXRATES_PK PRIMARY KEY(
	ZIP_CODE,
	PLUS_4_LOW,
	PLUS_4_HIGH
)
)REPLICATE PERSISTENT
  EVICTION BY LRUHEAPPERCENT
  EVICTACTION OVERFLOW PERSISTENT ASYNCHRONOUS;;

CREATE TABLE Taxes.Alabama 
(
    LOCALITY_CODE INTEGER,
    LOCALITY_NAME VARCHAR(50),
    RATE DECIMAL(13,6),
    COUNTY_CODE VARCHAR(10),
    CITY_CODE VARCHAR(10)
)
REPLICATE PERSISTENT
EVICTION BY LRUHEAPPERCENT
EVICTACTION OVERFLOW PERSISTENT ASYNCHRONOUS;

CREATE INDEX AlabamaTaxes_CityCode ON Taxes.Alabama(CITY_CODE);

CREATE INDEX AlabamaTaxes_CountyCode ON Taxes.Alabama(COUNTY_CODE);

CREATE INDEX TAXRATESTaxes_ZIP_CODE ON Taxes.TAXRATES(ZIP_CODE);