CALL SYSCS_UTIL.IMPORT_TABLE ('RTRADM','RTR_REPORT_DATA','<path>/rtr.dat', ',', '"', null, 0);
CALL SYSCS_UTIL.IMPORT_TABLE ('RTRADM','SALES_CREDITS','<path>/SALES_CREDITS.dat', ',', '"', null, 0);
CALL SYSCS_UTIL.IMPORT_TABLE ('RTRADM','RESOURCE_ROLE_REF','<path>/RESOURCE_ROLE_REF.dat', ',', '"', null, 0);
CALL SYSCS_UTIL.IMPORT_TABLE ('RTRADM','SALES_GEOGRAPHY_REF','<path>/SALES_GEOGRAPHY_REF.dat', ',', '"', null, 0);
--CALL SYSCS_UTIL.IMPORT_TABLE ('RTRADM','TERRITORY_ASSIGNMENT','<path>/TERRITORY_ASSIGNMENT.dat', ',', '"', null, 0);
