-------------------------------------------------------------------------------
-- Delete all tables
DROP TABLE CDSDBA.XML_DOC_3;
DROP SYNONYM CDSUSR.XML_DOC_3;
DROP SYNONYM CDSUSRRO.XML_DOC_3;
DROP TABLE CDSDBA.XML_HST_3;
DROP SYNONYM CDSUSR.XML_HST_3;
DROP SYNONYM CDSUSRRO.XML_HST_3;

DROP TABLE CDSDBA.XML_IDX_20_1;
DROP SYNONYM CDSUSR.XML_IDX_20_1;
DROP SYNONYM CDSUSRRO.XML_IDX_20_1;

DROP TABLE CDSDBA.XML_IDX_21_1;
DROP SYNONYM CDSUSR.XML_IDX_21_1;
DROP TABLE CDSDBA.XML_IDX_21_2;
DROP SYNONYM CDSUSR.XML_IDX_21_2;
DROP SYNONYM CDSUSRRO.XML_IDX_21_2;

DROP TABLE CDSDBA.XML_IDX_23_1;
DROP SYNONYM CDSUSR.XML_IDX_23_1;
DROP SYNONYM CDSUSRRO.XML_IDX_23_1;

DROP TABLE CDSDBA.XML_IDX_24_1;
DROP SYNONYM CDSUSR.XML_IDX_24_1;
DROP SYNONYM CDSUSRRO.XML_IDX_24_1;
DROP TABLE CDSDBA.XML_IDX_24_2;
DROP SYNONYM CDSUSR.XML_IDX_24_2;
DROP SYNONYM CDSUSRRO.XML_IDX_24_2;
DROP TABLE CDSDBA.XML_IDX_24_3;
DROP SYNONYM CDSUSR.XML_IDX_24_3;
DROP SYNONYM CDSUSRRO.XML_IDX_24_3;
DROP TABLE CDSDBA.XML_IDX_24_4;
DROP SYNONYM CDSUSR.XML_IDX_24_4;
DROP SYNONYM CDSUSRRO.XML_IDX_24_4;

DROP TABLE CDSDBA.XML_IDX_25_1;
DROP SYNONYM CDSUSR.XML_IDX_25_1;
DROP SYNONYM CDSUSRRO.XML_IDX_25_1;
DROP TABLE CDSDBA.XML_IDX_25_2;
DROP SYNONYM CDSUSR.XML_IDX_25_2;
DROP SYNONYM CDSUSRRO.XML_IDX_25_2;
DROP TABLE CDSDBA.XML_IDX_25_3;
DROP SYNONYM CDSUSR.XML_IDX_25_3;
DROP SYNONYM CDSUSRRO.XML_IDX_25_3;

DROP TABLE CDSDBA.XML_IDX_26_1;
DROP SYNONYM CDSUSR.XML_IDX_26_1;
DROP SYNONYM CDSUSRRO.XML_IDX_26_1;

DROP TABLE CDSDBA.XML_IDX_27_1;
DROP SYNONYM CDSUSR.XML_IDX_27_1;
DROP SYNONYM CDSUSRRO.XML_IDX_27_1;
DROP TABLE CDSDBA.XML_IDX_27_2;
DROP SYNONYM CDSUSR.XML_IDX_27_2;
DROP SYNONYM CDSUSRRO.XML_IDX_27_2;

DROP TABLE CDSDBA.XML_IDX_30_1;
DROP SYNONYM CDSUSR.XML_IDX_30_1;
DROP SYNONYM CDSUSRRO.XML_IDX_30_1;

DROP TABLE CDSDBA.XML_IDX_33_1;
DROP SYNONYM CDSUSR.XML_IDX_33_1;
DROP SYNONYM CDSUSRRO.XML_IDX_33_1;
DROP TABLE CDSDBA.XML_IDX_33_2;
DROP SYNONYM CDSUSR.XML_IDX_33_2;
DROP SYNONYM CDSUSRRO.XML_IDX_33_2;
DROP TABLE CDSDBA.XML_IDX_33_3;
DROP SYNONYM CDSUSR.XML_IDX_33_3;
DROP SYNONYM CDSUSRRO.XML_IDX_33_3;
DROP TABLE CDSDBA.XML_IDX_33_4;
DROP SYNONYM CDSUSR.XML_IDX_33_4;
DROP SYNONYM CDSUSRRO.XML_IDX_33_4;
DROP TABLE CDSDBA.XML_IDX_33_5;
DROP SYNONYM CDSUSR.XML_IDX_33_5;
DROP SYNONYM CDSUSRRO.XML_IDX_33_5;
DROP TABLE CDSDBA.XML_IDX_33_6;
DROP SYNONYM CDSUSR.XML_IDX_33_6;
DROP SYNONYM CDSUSRRO.XML_IDX_33_6;
DROP TABLE CDSDBA.XML_IDX_33_7;
DROP SYNONYM CDSUSR.XML_IDX_33_7;
DROP SYNONYM CDSUSRRO.XML_IDX_33_7;

DROP TABLE CDSDBA.XML_IDX_38_1;
DROP SYNONYM CDSUSR.XML_IDX_38_1;
DROP SYNONYM CDSUSRRO.XML_IDX_38_1;

DROP TABLE CDSDBA.XML_IDX_41_1;
DROP SYNONYM CDSUSR.XML_IDX_41_1;
DROP SYNONYM CDSUSRRO.XML_IDX_41_1;

DROP TABLE CDSDBA.XML_IDX_47_1;
DROP SYNONYM CDSUSR.XML_IDX_47_1;
DROP SYNONYM CDSUSRRO.XML_IDX_47_1;

DROP TABLE CDSDBA.XML_IDX_50_1;
DROP SYNONYM CDSUSR.XML_IDX_50_1;
DROP SYNONYM CDSUSRRO.XML_IDX_50_1;

DROP TABLE CDSDBA.XML_IDX_57_1;
DROP SYNONYM CDSUSR.XML_IDX_57_1;
DROP SYNONYM CDSUSRRO.XML_IDX_57_1;
DROP TABLE CDSDBA.XML_IDX_57_2;
DROP SYNONYM CDSUSR.XML_IDX_57_2;
DROP SYNONYM CDSUSRRO.XML_IDX_57_2;

DROP TABLE CDSDBA.XML_IDX_65_1;
DROP SYNONYM CDSUSR.XML_IDX_65_1;
DROP SYNONYM CDSUSRRO.XML_IDX_65_1;
DROP TABLE CDSDBA.XML_IDX_65_2;
DROP SYNONYM CDSUSR.XML_IDX_65_2;
DROP SYNONYM CDSUSRRO.XML_IDX_65_2;

DROP TABLE CDSDBA.XML_IDX_78_1;
DROP SYNONYM CDSUSR.XML_IDX_78_1;
DROP SYNONYM CDSUSRRO.XML_IDX_78_1;
DROP TABLE CDSDBA.XML_IDX_78_2;
DROP SYNONYM CDSUSR.XML_IDX_78_2;
DROP SYNONYM CDSUSRRO.XML_IDX_78_2;

DROP TABLE CDSDBA.XML_IDX_79_1;
DROP SYNONYM CDSUSR.XML_IDX_79_1;
DROP SYNONYM CDSUSRRO.XML_IDX_79_1;

DROP TABLE CDSDBA.XML_IDX_87_1;
DROP SYNONYM CDSUSR.XML_IDX_87_1;
DROP SYNONYM CDSUSRRO.XML_IDX_87_1;

DROP TABLE CDSDBA.XML_IDX_98_1;
DROP SYNONYM CDSUSR.XML_IDX_98_1;
DROP SYNONYM CDSUSRRO.XML_IDX_98_1;

DROP TABLE CDSDBA.XML_IDX_99_1;
DROP SYNONYM CDSUSR.XML_IDX_99_1;
DROP SYNONYM CDSUSRRO.XML_IDX_99_1;

-------------------------------------------------------------------------------
-- Delete all control SQL
delete from DOMAIN_CONTROL where DOMAIN_ID_NBR = 3;
delete from INDEX_CONTROL where STRUCTURE_ID_NBR between 20 and 99;
delete from STRUCTURE_CONTROL where STRUCTURE_ID_NBR between 20 and 99;
delete from XSD_CONTROL where STRUCTURE_ID_NBR between 20 and 99;


-------------------------------------------------------------------------------
-- Delete all data
delete from XML_DOC_3;
delete from XML_HST_3;

-- delete all index data
delete from xml_idx_20_1;
delete from xml_idx_21_1;
delete from xml_idx_21_2;
delete from xml_idx_23_1;
delete from xml_idx_24_1;
delete from xml_idx_24_2;
delete from xml_idx_24_3;
delete from xml_idx_24_4;
delete from xml_idx_25_1;
delete from xml_idx_25_2;
delete from xml_idx_25_3;
delete from xml_idx_26_1;
delete from xml_idx_27_1;
delete from xml_idx_27_2;
delete from xml_idx_30_1;
delete from xml_idx_33_1;
delete from xml_idx_33_2;
delete from xml_idx_33_3;
delete from xml_idx_33_4;
delete from xml_idx_33_5;
delete from xml_idx_33_6;
delete from xml_idx_33_7;
delete from xml_idx_38_1;
delete from xml_idx_41_1;
delete from xml_idx_47_1;
delete from xml_idx_50_1;
delete from xml_idx_57_1;
delete from xml_idx_57_2;
delete from xml_idx_65_1;
delete from xml_idx_65_2;
delete from xml_idx_78_1;
delete from xml_idx_78_2;
delete from xml_idx_79_1;
delete from xml_idx_87_1;
delete from XML_IDX_98_1;
delete from XML_IDX_99_1;
