DROP TABLE IF EXISTS APP.ITEM_NOTA_FISCAL;
DROP TABLE IF EXISTS APP.NOTA_FISCAL;
DROP TABLE IF EXISTS APP.TEMPO;
DROP TABLE IF EXISTS APP.VENDEDOR;
DROP TABLE IF EXISTS APP.REVENDA;
DROP TABLE IF EXISTS APP.PRODUTO;
DROP TABLE IF EXISTS APP.TIPO_PRODUTO;
DROP TABLE IF EXISTS APP.CLIENTE;


CREATE TABLE APP.TEMPO (
	DAT_DIA date not null PRIMARY KEY,
	NUM_DIA_MES integer not null,
	NOM_DIA_SEMANA varchar(20) not null,
	NUM_MES integer not null,
	NOM_MES varchar(20) not null,
	NUM_ANO_MES integer not null,
	NUM_TRIMESTRE integer not null,
	NOM_TRIMESTRE varchar(20) not null,
	NUM_SEMESTRE integer not null,
	NOM_SEMESTRE varchar(20) not null,
	NUM_ANO integer not null,
	NOM_SEMANA_MES varchar(20) not null,
	NOM_SEMANA_ANO varchar(20) not null

) REPLICATE;

CREATE TABLE APP.CLIENTE (
	COD_CLIENTE INT NOT NULL PRIMARY KEY,
	NOM_CLIENTE VARCHAR(100)
) REPLICATE;

CREATE TABLE APP.TIPO_PRODUTO (
	COD_TIPO_PRODUTO INT NOT NULL PRIMARY KEY,
	NOM_TIPO_PRODUTO VARCHAR(100)
) REPLICATE;

CREATE TABLE APP.PRODUTO (
	COD_TIPO_PRODUTO INT NOT NULL CONSTRAINT FK_TIPO_PRODUTO_PRODUTO REFERENCES APP.TIPO_PRODUTO (COD_TIPO_PRODUTO),
	COD_PRODUTO INT NOT NULL,
	NOM_PRODUTO VARCHAR(100),
	PRIMARY KEY (COD_TIPO_PRODUTO, COD_PRODUTO)
) REPLICATE;


CREATE TABLE APP.REVENDA (
	COD_REVENDA INT NOT NULL PRIMARY KEY,
	NOM_REVENDA VARCHAR(100)
) PARTITION BY PRIMARY KEY;

CREATE TABLE APP.VENDEDOR (
	COD_REVENDA INT NOT NULL CONSTRAINT FK_REVENDA_VENDEDOR REFERENCES APP.REVENDA (COD_REVENDA),
	COD_VENDEDOR INT NOT NULL ,
	NOM_VENDEDOR VARCHAR(100),
	PRIMARY KEY (COD_REVENDA, COD_VENDEDOR)
) PARTITION BY COLUMN(COD_REVENDA) COLOCATE WITH (APP.REVENDA);


CREATE TABLE APP.NOTA_FISCAL (
	NUM_NF INT NOT NULL,
	COD_CLIENTE INT NOT NULL CONSTRAINT FK_CLIENTE_NF REFERENCES APP.CLIENTE (COD_CLIENTE),
	COD_REVENDA INT NOT NULL,
	COD_VENDEDOR INT NOT NULL,
	DAT_DIA DATE NOT NULL CONSTRAINT FK_TEMPO_NF REFERENCES APP.TEMPO (DAT_DIA),
	VLR_NF NUMERIC(15,2),
	VLR_IMPOSTO NUMERIC(15,2),
	PRIMARY KEY (NUM_NF,COD_CLIENTE,COD_REVENDA,COD_VENDEDOR,DAT_DIA),
	CONSTRAINT FK_VENDEDOR_NF FOREIGN KEY (COD_REVENDA,COD_VENDEDOR) REFERENCES APP.VENDEDOR (COD_REVENDA,COD_VENDEDOR)
) PARTITION BY COLUMN(COD_REVENDA) COLOCATE WITH (APP.REVENDA);


CREATE TABLE APP.ITEM_NOTA_FISCAL (
	NUM_NF INT NOT NULL,
	COD_CLIENTE INT NOT NULL,
	COD_REVENDA INT NOT NULL,
	COD_VENDEDOR INT NOT NULL,
	DAT_DIA DATE NOT NULL,
	COD_TIPO_PRODUTO INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	COD_ITEM_NF INT NOT NULL,
	VLR_ITEM_NF NUMERIC(15,2),
	PRIMARY KEY (NUM_NF,COD_CLIENTE,COD_REVENDA,COD_VENDEDOR,DAT_DIA,COD_TIPO_PRODUTO,COD_PRODUTO,COD_ITEM_NF),
	CONSTRAINT FK_NF_ITEM_NF FOREIGN KEY (NUM_NF,COD_CLIENTE,COD_REVENDA,COD_VENDEDOR,DAT_DIA) REFERENCES APP.NOTA_FISCAL (NUM_NF,COD_CLIENTE,COD_REVENDA,COD_VENDEDOR,DAT_DIA),
	CONSTRAINT FK_PRODUTO_ITEM_NF FOREIGN KEY (COD_TIPO_PRODUTO,COD_PRODUTO) REFERENCES APP.PRODUTO (COD_TIPO_PRODUTO,COD_PRODUTO)
) PARTITION BY COLUMN(COD_REVENDA) COLOCATE WITH (APP.REVENDA);

