

--COMMIT;

CREATE INDEX IX_TEMPO_01 ON APP.TEMPO (NUM_DIA_MES);
CREATE INDEX IX_TEMPO_02 ON APP.TEMPO (NUM_MES);
CREATE INDEX IX_TEMPO_03 ON APP.TEMPO (NUM_ANO);
CREATE INDEX IX_TEMPO_04 ON APP.TEMPO (NUM_ANO_MES);
CREATE INDEX IX_TEMPO_05 ON APP.TEMPO (NOM_MES);

CREATE UNIQUE INDEX IX_PRODUTO_01 ON APP.PRODUTO (COD_PRODUTO);
CREATE UNIQUE INDEX IX_PRODUTO_02 ON APP.PRODUTO (NOM_PRODUTO);

CREATE UNIQUE INDEX IX_VENDEDOR_01 ON APP.VENDEDOR (COD_VENDEDOR);

CREATE INDEX IX_NF_01 ON APP.NOTA_FISCAL (COD_REVENDA);
CREATE INDEX IX_NF_02 ON APP.NOTA_FISCAL (COD_VENDEDOR);
CREATE UNIQUE INDEX IX_NF_03 ON APP.NOTA_FISCAL (NUM_NF);

CREATE INDEX IX_ITEM_NF_01 ON APP.ITEM_NOTA_FISCAL (COD_CLIENTE);
CREATE INDEX IX_ITEM_NF_02 ON APP.ITEM_NOTA_FISCAL (COD_REVENDA);
CREATE INDEX IX_ITEM_NF_03 ON APP.ITEM_NOTA_FISCAL (COD_VENDEDOR);
CREATE INDEX IX_ITEM_NF_04 ON APP.ITEM_NOTA_FISCAL (DAT_DIA);
CREATE INDEX IX_ITEM_NF_05 ON APP.ITEM_NOTA_FISCAL (COD_TIPO_PRODUTO);
CREATE INDEX IX_ITEM_NF_06 ON APP.ITEM_NOTA_FISCAL (COD_ITEM_NF);
CREATE INDEX IX_ITEM_NF_07 ON APP.ITEM_NOTA_FISCAL (COD_PRODUTO);
CREATE INDEX IX_ITEM_NF_08 ON APP.ITEM_NOTA_FISCAL (NUM_NF);


CREATE UNIQUE INDEX IX_TIPO_PRODUTO_01 ON APP.TIPO_PRODUTO (NOM_TIPO_PRODUTO); 

--COMMIT;
